### ISSUE TITLE
Any chance you could compile for earlier glibc?

### ISSUE THREAD

**Issue by mp15** [nanoporetech/modkit#1]
Hi I get:
```
modkit-0.1.2/modkit: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by modkit-0.1.2/modkit)
modkit-0.1.2/modkit: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by modkit-0.1.2/modkit)
```
On Ubuntu 18.04. Alas it will likely be a few months before we can rid ourselves of this version of Ubuntu on our compute cluster. Any chance you could compile your binaries targeting an earlier glibc?

**Comment by ArtRand** [comment]
Hello @mp15, yes I can get U18 and U16 binaries released.

**Comment by ArtRand** [comment]
@mp15 I've placed an artifact built against an older version of glibc in [releases](https://github.com/nanoporetech/modkit/releases/tag/v0.1.2), marked modkit_centos7_x86_64.tar.gz. Please let me know if it works for you.

**Comment by mp15** [comment]
Works for me! Thank you
