### ISSUE TITLE
Option '--filter-threshold' of `summary`

### ISSUE THREAD

**Issue by qiangfu-eu** [nanoporetech/modkit#10]
Thanks for creating this exciting new tool. However, there seems to be a bug in the `summary` part.

I try to run `summary` with set filtering threshold, however it seems that it does not skip sampling process and it only processsed sampled reads (see total_reads_used)

```
modkit summary --filter-threshold 0.7324219 PAK67493_barcode02_sorted.bam
> sampling 10042 reads from BAM
> parsing user defined thresholds
> this output format will not be default in the next version, the table output (set with --table) will become default and this format will require the --tsv option
mod_bases       C
count_reads_C   10042
C_calls_modified_m      5735
C_frac_modified_m       0.1119155413316681
C_filtered_modified_m   1331
C_calls_unmodified      43073
C_frac_unmodified       0.8405471860120209
C_filtered_unmodified   2504
C_calls_modified_h      2436
C_frac_modified_h       0.04753727265631098
C_filtered_modified_h   1822
C_total_mod_calls       51244
C_total_filtered_mod_calls      5657
total_reads_used        10042
```

Only when I also use `--no-filtering` option, it processes all the reads.

```
modkit summary --no-filtering --filter-threshold 0.7324219 PAK67493_barcode02_sorted.bam
> performing no filtering
> parsing user defined thresholds
> this output format will not be default in the next version, the table output (set with --table) will become default and this format will require the --tsv option
mod_bases       C
count_reads_C   112489
C_calls_modified_m      54735
C_frac_modified_m       0.09675349468637974
C_filtered_modified_m   13888
C_calls_unmodified      484487
C_frac_unmodified       0.8564138189480234
C_filtered_unmodified   27845
C_calls_modified_h      26494
C_frac_modified_h       0.04683268636559687
C_filtered_modified_h   19498
C_total_mod_calls       565716
C_total_filtered_mod_calls      61231
total_reads_used        112489
```

I would assume that when `--filter-threshold`, no sampling is needed and all reads should be processed. Is this a bug or intended behavior?

Many thanks.

**Comment by ArtRand** [comment]
Hello @qiangfu-eu,

Yes, there is a bug where `--no-filtering` will cause summary to sample the whole BAM. I'll fix this in the release this week. As a workaround, you could set `--filter-threshold 0.0` combined with `--num-reads` or `--sampling-frac`. You also exposed that `--no-filtering` should conflict with `--filter-threshold F` so I'll fix that too. 

As far as the read count discrepancy, could you add the `--log-filepath <file>` option? The iterator will remove secondary, supplementary, and duplicate records, but that doesn't explain all of it. It also removes records where there is no query sequence or it fails to parse the MM/ML tags. Some of these errors are logged in the log-file and may provide a clue. Setting `--sampling-frac 1.0` should cause modkit to use the whole BAM also, missing reads will be logged to the file. 

Thanks for the bug report.

**Comment by qiangfu-eu** [comment]
Thanks for the information. I actually noticed some issue with my BAM files that actually caused some of the observed issues above. For example, inconsistency between reads reported by `summary`.  I think I better also report it here, as I see there is some issue with certain aspect of the tool.

1. `pileup` does NOT report skipped read in stderr, only report them in the log file when `--log-filepath` is set, although it reports other error in the stderr.

This is the reason that I did not realize the my BAM file is actually having issues. The issue I have is that we performed porechop on fastq before alignment with minimap2. However the MM/ML tags called by dorado are simply carried over from original SAM file. Hence after trimming, the content in MM especially does not match timmed read sequence anymore.

I did not realize this as I did NOT see any error message in stderr, hence I thought that modkit runs without issue. It is my bad that I did not try to generate log file using  `--log-filepath` instead piped only stderr as log. 

It would be better to show at lest some statistics in stderr about skipped reads to help alert user possible issues.

2. `summary` does NOT report skipped read in either stderr and/or log file specified `--log-filepath`. When I run `summary` with `--sampling-frac 1.0`, I think it skipped many reads possibly with issues, as shown in the output file above, however nothing is reported. But similarly, it might be better to show some statistics in stderr or log file if reads are skipped... I wonder does `summary` check MM field, as it is not necesary to check MM to generate statistics... In this case, how does it detect reads with issues and filter them?

Many thanks.

**Comment by ArtRand** [comment]
Hello @qiangfu-eu,

Thanks for noticing this. In general, `modkit` will log errors such as skipped reads, erronious tags, etc. to the log file. The only messages to the terminal should be warnings or information about the run. I agree that all of the commands should log the number of reads that failed and their reasons, or at the very least the logging to the logfile should be consistent. Could you open a new issue essentially with your above comment. I should be able to get those fixes into the next release.

**Comment by qiangfu-eu** [comment]
Sorry, I just realize. I might not be the right person to close it. I will leave it for you to decide.

**Comment by ArtRand** [comment]
@qiangfu-eu No worries. Feel free to close this issue (and maybe #8 ) when you feel they have been resolved.
