### ISSUE TITLE
Skipping reads with supplementary alignments

### ISSUE THREAD

**Issue by samim21** [nanoporetech/modkit#101]
Hi there,

I was wondering if there is a way to force modkit extract to include reads with supplementary alignments? It seems that if any reads have supplementary alignments they are being skipped.

Thank you!

**Comment by ArtRand** [comment]
Hello @samim21, 

Yes supplementary and secondary alignments will be dropped by `modkit`. This has been mentioned in #79  as well, and is [documented](https://nanoporetech.github.io/modkit/intro_adjust.html). 

I'm investigating ways to remove this limitation and if they show to work robustly the next version of modkit will allow supplementary and secondary alignments.

**Comment by ArtRand** [comment]
Hello @samim21,

As of [v0.2.4](https://github.com/nanoporetech/modkit/releases/tag/v0.2.4) you can get secondary and supplementary alignment information with `modkit extract` so long as the MN tag is correct. You can find information on how to make sure your alignments have a correct MN tag in the [troubleshooting docs](https://nanoporetech.github.io/modkit/troubleshooting.html#missing-secondary-and-supplementary-alignments-in-output).

**Comment by ArtRand** [comment]
@samim21 feel free to re-open this issue if you have any problems with `modkit extract` and supplementary alignments.
