### ISSUE TITLE
failed to get modbase info for record & Skipped: no mod tags

### ISSUE THREAD

**Issue by Modernism-01** [nanoporetech/modkit#102]
Hi,

when I ran modkit pileup command, I got the wrong report that all the records did not have mod tags like this: 

> calculated chunk size: 6, interval size 100000, processing 600000 positions concurrently
> filtering to only CpG motifs
> attempting to sample 10042 reads
> failed to get modbase info for record 527758ce-04c6-42ee-bbb2-6fe42d7a89cf, Skipped: no mod tags
> failed to get modbase info for record 442b1abf-0a29-4715-8788-423fff5d9d73, Skipped: no mod tags
> failed to get modbase info for record ce1f058a-616f-40d9-9c4d-9720db121dea, Skipped: no mod tags
> failed to get modbase info for record 9030f652-8b70-4a27-afc9-4007ee720491, Skipped: no mod tags
> failed to get modbase info for record 40773bfa-4aff-4594-8f21-dcf00e3915bf, Skipped: no mod tags

My modkit command is below:

modkit pileup $bam $output/test.pileup.bed.tsv --cpg --ref $reference

so when I checked the BAM file originating from Dorado and minimap2, I did not find any "MM" & "ML" tags, seeing below:

527758ce-04c6-42ee-bbb2-6fe42d7a89cf NM:i:2555 ms:i:20367       AS:i:19713      nn:i:0  tp:A:P  cm:i:697        s1:i:5816       s2:i:67 de:f:0.1119     rl:i:1649       ts:i
442b1abf-0a29-4715-8788-423fff5d9d73 NM:i:98 ms:i:3625  AS:i:3598       nn:i:0  tp:A:P  cm:i:255        s1:i:1654       s2:i:0  de:f:0.035      rl:i:30 ts:i:910
ce1f058a-616f-40d9-9c4d-9720db121dea NM:i:448 ms:i:4231 AS:i:4098       nn:i:0  tp:A:P  cm:i:168        s1:i:1347       s2:i:0  de:f:0.0985     rl:i:263        ts:i:490

I do not know how to solve this problem, could you give me some advice?

**Comment by ArtRand** [comment]
Hello @Modernism-01,

How did you basecall/modification call your data? `modkit` does not generate the `MM`/`ML` tags, it only uses them. Looks to me like your data is missing the modification calls.

**Comment by Modernism-01** [comment]
Yes, Thank you for your positive reply. I missed a reference for the alignment, so it did not generate `MM/ML` tags.
