### ISSUE TITLE
How to understand Ndiff and Ndelete?

### ISSUE THREAD

**Issue by cqhhui** [nanoporetech/modkit#105]
Dear all，
In the realm of genomic sequencing, understanding the precise terminology is essential for accurate data interpretation. To this end, I would like to inquire about the definitions of "Ndiff" and "Ndelete" as used in your publications/software/documentation. Specifically, my question revolves around whether these terms align with the typical concepts we encounter in SNP analysis, such as base swapping, transversion, insertion, and deletion.
Understanding these definitions will greatly assist in ensuring that my analysis aligns correctly with the intended interpretations of these terms.
I appreciate your time and assistance in this matter and look forward to your response.
Thanks
CQH

**Comment by cjw85** [comment]
These terms are defined in the README: https://github.com/nanoporetech/modkit?tab=readme-ov-file#definitions

**Comment by cqhhui** [comment]
> These terms are defined in the README: https://github.com/nanoporetech/modkit?tab=readme-ov-file#definitions

Thank you very much for taking the time to answer my question amidst your busy schedule. I previously used the modbam2bed software to obtain information on DNA methylation sites and noticed that its output files are slightly different from those of modkit. Therefore, I am reaching out for clarification. My current focus is on the base mutation situations at 5mC sites, and the modbam2bed software results include Nsub and Ndel. I would like to inquire whether there are different interpretations of these records between the two software, and if it's possible to determine the mutation situation at a site based on the sum of Nsub and Ndel (as the modbam2bed output file does not record Nsub and Ndel separately).

**Comment by cjw85** [comment]
Ndiff and Ndelete in modkit are equivalent to Nsub and Ndel in modbam2bed respectively.

These quantities should not be used to impute mutations, for that you should use a variant caller. They are provided only for the context for evaluating modified base calls and frequencies.

**Comment by cqhhui** [comment]
Thank you for your response.
