### ISSUE TITLE
Trouble accessing m6A sites

### ISSUE THREAD

**Issue by kylepalos** [nanoporetech/modkit#107]
Hi,

Thanks for maintaining a really nice tool for the community.

I ultimately want a bed file of m6A sites from my direct RNA-sequencing experiments, however I am having a variety of issues. My workflow is as follows:

**Basecall (v0.5.0)**:
```
dorado basecaller sup pod5_pass/ --estimate-poly-a --modified-bases m6A_DRACH > dorado_basecall.bam
```

**Convert to fastq**:
```
samtools fastq -@ 15 -T "*" dorado_basecall.bam > dorado_basecall.fastq
```

**Map using Minimap2 and convert to bam**:
```
minimap2 -ax splice -uf -k14 -G 10000 -t 16 -y --secondary=no \
reference.fa \
dorado_basecall.fastq \
| samtools sort -@ 16 -o dorado_basecall_mapped.bam -
```

Up to this point, everything seemed to go okay. Based on reading a variety of issues, I believe that I have carried over my modification tags correctly, and the next step seems to use [modbam2bed](https://github.com/epi2me-labs/modbam2bed) to extract out modified sites. However, I have noticed a number of issues:

1. There is no m6A model, there only appears to be models for DNA.
2. modbam2bed is deprecated and development has gone to [modkit](https://github.com/nanoporetech/modkit). 

To try to get modbam2bed to work with my data, I performed the following:

```
modbam2bed --combine -m modA -t 16 -e reference.fa dorado_basecall_mapped.bam > dorado_basecall_modbam2bed.bed
```

using the generic "modA" model setting. This runs to completion, however columns 11-16 are all either NA or 0, suggesting that no modified sites were found.

The last thing I tried to do was use the more recently developed modkit, but got a warning for every read about AUX data not being found:

```
> failed to get modbase info for record db99ae0a-9657-4ccc-8501-d5436cff4de9, Skipped: AUX data not found
> failed to get modbase info for record ba989280-b6c0-4c48-b359-d7d46e7abfbc, Skipped: AUX data not found
> failed to get modbase info for record fe2b1897-8c57-482e-abab-c1d48d873de8, Skipped: AUX data not found
> failed to get modbase info for record e1a1ace5-ba7c-42d7-ba7a-513195e6729a, Skipped: AUX data not found
> failed to get modbase info for record 8e80a464-f59f-488e-ac07-e27df67d40ce, Skipped: AUX data not found
```

Sorry for a really long message, and if a lot of this is outside the scope of Dorado, but I'm unsure how to proceed to obtain a bed file of modified sites. Can you offer any alternatives/troubleshooting that I may follow up with? Thank you very much.

**Comment by ArtRand** [comment]
Hello @kylepalos, 

I apologize for the slow reply. `modkit` should support the analysis you're looking for. It looks like the MM and ML tags are getting lost somewhere. Could you check that all of the records with query names reported by `modkit` have MM and ML tags? It's possible that the minimap step with `-x splice` is loosing them - I'll check to see how this affects the output tags. You can do a quick check by running `modkit summary [--no-sampling]` and look at the logs. If you can let me know what's happening to the tags, I can give you a way to fix them.

**Comment by kylepalos** [comment]
Hi @ArtRand 

Thank you for your response and help with this issue. I ran ```modkit summary --no-sampling dorado_basecall.bam``` (for the bam file that dorado produces) and ```modkit summary --no-sampling dorado_basecall_mapped.bam``` (for the bam file that minimap2 produces).

In both instances, the logs appear to report that all reads do not have any AUX data, here are the last 15 or so lines:

```
> failed to get modbase info for record a5e6e091-9ef8-4576-866d-9044f7b85811, Skipped: AUX data not found
> failed to get modbase info for record 9e2b1562-e106-42ee-8b22-d5fc39836e61, Skipped: AUX data not found
> failed to get modbase info for record 99c55279-5e69-4c7a-a2f8-a6db8e5f8a35, Skipped: AUX data not found
> failed to get modbase info for record 32535e24-57b9-43ac-b174-ba9a15771361, Skipped: AUX data not found
> failed to get modbase info for record 3c8f5ef7-0fb9-4fdd-86bf-d1de5a695c70, Skipped: AUX data not found
> failed to get modbase info for record 2b371d33-84a0-44c5-b946-89156385865b, Skipped: AUX data not found
> failed to get modbase info for record 6acaa0a2-189c-4a51-b2fe-c78b9f3ca4f1, Skipped: AUX data not found
> failed to get modbase info for record 0e2651d7-ecc6-44e0-b252-854cfb69724e, Skipped: AUX data not found
> calculating threshold at 10% percentile
> calculated thresholds:
# bases
# total_reads_used  0
 base  code  pass_count  pass_frac  all_count  all_frac
```

and produced an empty output table.

I have tried using Samtools view to extract the MM and ML tags from all bam files, and I am getting no output.

I went back to the beginning and ran Dorado on a single Pod5 file without the --estimate-poly-a argument (I noticed this tag was in all of the read alignments for every bam file):

```
/home/kylep/dorado-0.5.0-linux-x64/bin/dorado basecaller sup pod5_pass/PAO12511_pass_a9fbd774_bc6df692_990.pod5 --modified-bases m6A_DRACH > sb_native_1_pod5_no_polya.bam
```

then ran Modkit summary, again getting the "AUX data not found" warning/error.

I've made the pod5 file that I used and the resulting sam/bam files available here: []https://drive.google.com/drive/folders/1XsPuYaXP8baY2A4y1kflKKbavIhobJ1u?usp=sharingl).

At this point, I'm guessing this is actually a Dorado issue (or potentially the way that I'm calling Dorado and/or the model specification?). I can re-post the issue in Dorado if necessary.

Again, thank you for your help.

**Comment by ArtRand** [comment]
@kylepalos , 

I'll take a look, thanks for sharing the data, it really helps debug the problem.

**Comment by kylepalos** [comment]
Hi @ArtRand 

Thanks again for your quick response. I have actually solved the issue, it appears that I was doing something incorrect with Dorado. Following the Dorado issue [here](https://github.com/nanoporetech/dorado/issues/521) and specifying the model explicitly (as well as the --min-qscore 10 --verbose --emit-moves arguments):

```
model=/mnt/Gofsef/new_nanopore_rna_chemistry/rna004_130bps_sup@v3.0.1

/home/kylep/dorado-0.5.0-linux-x64/bin/dorado basecaller --min-qscore 10 --verbose --emit-moves $model pod5_pass/PAO12511_pass_a9fbd774_bc6df692_990.pod5 --modified-bases m6A_DRACH > 1_pod5_no_polya.bam
```

I have gotten MM and ML tags:

```
kylep@VASH:/mnt/Gofsef/new_nanopore_rna_chemistry$ modkit summary sb_native_1_pod5_no_polya.bam
> sampling 10042 reads from BAM
> calculating threshold at 10% percentile
> calculated thresholds: A: 0.9277344
# bases             A
# total_reads_used  3937
# count_reads_A     3937
# pass_threshold_A  0.9277344
 base  code  pass_count  pass_frac    all_count  all_frac
 A     -     46366       0.9529741    50235      0.93072593
 A     a     2288        0.047025938  3739       0.0692741
```

Sorry for wasting your time, I naively assumed that whatever I was doing previously with Dorado was "close enough" to these commands. Thanks again though for the support.

**Comment by ArtRand** [comment]
@kylepalos ,

No worries, glad you got it working.
