### ISSUE TITLE
Modkit BED file impropperly formatted.

### ISSUE THREAD

**Issue by KloostermanJoukje** [nanoporetech/modkit#108]
Hello,

Another issue (#97) had the same issue as i had. And It was written that the issue would be fixed by relase 0.2.4 however when using this release, still the bed file is impropperly formatted:

> improperly formatted BED line chr22	18890487	18890487	
> improperly formatted BED line chr22	38110048	38110048	
> improperly formatted BED line chrX	153909598	153909598	

any idea when this will be implemented? Or how to fix it?

**Comment by JoukjeKloosterman** [comment]
To create the bed file I perform the following:

    local args=()
    args+=("view")
    args+=("--no-header")
    args+=("--no-version")
    args+=("--threads" "!{task.cpus}")
    args+=("!{vcf}")
    
    # -1 because positions in .bed are 0-based and 1-based in .vcf
    ${CMD_BCFTOOLS} "${args[@]}" | awk -v FS='\t' -v OFS='\t' '{print $1 "\t" $2-1 "\t" $2-1 "\t"}' > "!{vcf.simpleName}.bed"

**Comment by ArtRand** [comment]
Hello @JoukjeKloosterman, 

In the latest release `modkit` still requires the strand information in the `--include-bed` files. I wanted to remove this requirement in 0.2.4, but it didn't make it. If you add `.` as the strand for all of your BED lines, that should fix the problem (as suggested in #97). The plan is to remove this requirement (default to both strands) in the next release.

**Comment by ArtRand** [comment]
This feature has been implemented.
