### ISSUE TITLE
modkit pileup --region error

### ISSUE THREAD

**Issue by kwglam** [nanoporetech/modkit#110]
When I tried to pileup at specific regions using the command "modkit pileup --region" , I have got the following error message:
"Error! failed to find matching reference sequence for ./cpgIslandsExt_modkit_pileup.bed in BAM header parsing region ./cpgIslandsExt_modkit_pileup.bed"

The format of the file "cpgIslandsExt_modkit_pileup.bed":
chr1:3531624-3531843
chr1:3670619-3671074
chr1:3671654-3672156
chr1:4491701-4493673
chr1:4496947-4497608
chr1:4571641-4572075
chr1:4689184-4689397

Any idea?? Thanks!!

**Comment by ArtRand** [comment]
Hello @kwglam, 

The `--region` option can only be used for one region at a time. You wan to use the `--include-positions` option. `modkit` is a little strict about the format of this BED file, it needs to be lines such as:
```
<chrom>\t<start>\t<stop>\t.\t0\t<strand>
```
for example:
```
oligo_1512_adapters	63	64	.	0	+
```
The strand can be "+", "-", or "." where "." means both strands. For large regions like you have you probably want ".", hope this helps.

**Comment by kwglam** [comment]
It works!! Thanks a lot!!

**Comment by ArtRand** [comment]
@kwglam Glad it worked. Feel free to re-open this issue or another one if you have any additional questions or problems.

**Comment by kwglam** [comment]
Thanks, Arthur! Just noticed that --include-positions pileups CpG sites a base level in a provided region. Does modkit have a function that pileups and accumulates all CpG sites within a region? Something like the "dmr" function but without comparisons between samples. Thx!
