### ISSUE TITLE
Missing data chrM bedMethyl file

### ISSUE THREAD

**Issue by Macdot3** [nanoporetech/modkit#112]
Hi everyone! I'm using Dorado for the first time to identify the presence of methylated bases on mitochondrial DNA. 
After having installed and correctly used the modkit tool to create the bedMethyl file, we realized that the data referring to chrM was missing from the file. This aspect was also confirmed by the alignment, using the aligner function of dorado no reads map to the chrM, the fastq files of the same sample however give a coverage on the chrM of around 80-90x on average when normally aligned with minimap2 or ngmlr.
From the original pod5 it seems that many aligned reads are lost and the chrM is essentially not covered by any sequence. 
Below, I'm writing the commands I've used.

dorado basecaller dna_r10.4.1_e8.2_400bps_hac@v4.1.0/ /home.../POD_5/ --modified-bases 5mCG_5hmCG --device cpu > /calls_U.bam
samtools fastq -T'*' /calls_U.bam > /calls_Ufast.fastq
/minimap2 -ax map-ont -y -t 10 /datasets/genomes/hg38/hg38.fa /calls_Ufast.fastq > /calls_U_alignedfast.sam
samtools view -bS /calls_U_alignedfast.sam > /calls_U_alignedfast_1.bam
samtools sort /calls_U_alignedfast_1.bam -o /calls_U_alignedfast_1_sorted.bam
samtools index /calls_U_alignedfast_1_sorted.bam
modkit pileup /calls_U_alignedfest_1_sorted.bam /calls_U_alignedfest_1_sorted.bam_pileup.bed --log-filepath pileup.log

Is anyone else working on the same project and can help me? Thank you very much.

**Comment by ArtRand** [comment]
Hello @Macdot3,

Sounds like you're getting taken care of over at [dorado](https://github.com/nanoporetech/dorado/issues/581). If you're having a hard time getting pileups to work after you're successfully getting read alignments - let me know.
