### ISSUE TITLE
Ignore soft-clippings in pileup

### ISSUE THREAD

**Issue by SophieValk** [nanoporetech/modkit#115]
Hi,

I have been using modkit for calling 5mC modification on CpGs from Nanopore data. Thanks for providing such useful software. 
I was wondering about how modkit pileup deals with soft-clipped parts of a read. 
In the guide I can find that all secondary and unmapped alignments are ignored in modkit pileup. And I see there is an --only-mapped flag in the sample-probs function that ignores the soft-clipppings. Are soft-clipping parts of reads included when generating modification calls using modkit pileup? Or, if this is not the case, is there a flag  I can use to ignore the soft-clippings when using the pileup function?

Thanks and best regards, 
Sophie

**Comment by marcus1487** [comment]
As soft-clipped reads do not have a mapped reference base they will not contribute to the counts in the pileup results. 

By default the soft-clipped bases will not contribute to threshold estimation either (akin to the behavior described in `sample-probs --only-mapped`). The `--include-unmapped` pileup option allows soft-clipped positions to contribute to threshold estimation.

**Comment by SophieValk** [comment]
Thanks a lot!

**Comment by ArtRand** [comment]
@SophieValk feel free to re-open this issue if you have additional questions about which base modification probabilities are used in the various calculations.
