### ISSUE TITLE
 Plans to make modkit able to output MetH5 format files?

### ISSUE THREAD

**Issue by bernardo-heberle** [nanoporetech/modkit#117]
Hello.

There are several analysis tools for nanopore base modifications that are based on the `MetH5` format that was used by [nanopolish](https://github.com/jts/nanopolish)—the standard tool for analyzing nanopore methylation data before R10 flowcells.

Adding an option allowing users to output `MetH5` files would greatly increase the compatibility of `modkit` with other tools that can complement it such as [pycoMeth](https://github.com/PMBio/pycoMeth). 

I was wondering if you would consider adding an option to modkit so that it can also output `MetH5` format files instead of only `bedMethyl` files? 

Alternatively, do you know of an easy way to convert the `bedMethyl` files from `modkit` into the `MetH5` format from Nanopolish?

I really like the ease of use and great features included in `modkit`. It would be great to be able to easily integrate it with previous tools used for modified base analysis that existed before the R10 flowcells became widely adopted.

**Comment by cjw85** [comment]
Beyond pycoMeth, we are not aware of any tools that use the MetH5 format. Contrary to your statement, Nanopolish does not use the format.

The MM and ML SAM tags are now a community standard. I'm not sure what adding MetH5 output to modkit would constitute; both the SAM tags and MetH5 are concerned with storage of the underlying read data. Modkit tools perform analyses on the read data. So if anything MetH5 support in modkit would be to allow input of such files, not output. Given that basecallers output SAM MM and ML tags it would seem rather redundant for modkit to support MetH5 as input (a conversion to MetH5 would first need to take place).

There is no specification of the MetH5 format, beyond a vague description in the appendix of the pycoMeth paper. Any attempt at a second party implementation is going to likely lead to files that are not strictly identical to the original (the original Python implementation itself does not carefully define the data types of data data stored into thr HDF container).

For these reasons support for MetH5 in modkit is not being considered at this time.

**Comment by bernardo-heberle** [comment]
Thank you for the quick reply @cjw85. Yeah, you are right about that, after re-reading the documentation nanopolish just generates a ".tsv" file for methylation calls and then pycoMeth converts it to MetH5 format.

Thank you for the explanation, now it makes sense to me.
