### ISSUE TITLE
Extract 5mCG/5hmCG modification from 5mC_5hmC BAM file.

### ISSUE THREAD

**Issue by miwi610** [nanoporetech/modkit#118]
I have BAM files from dorado with sup,5mC_5hmC,6mA option and would like to visualize only 5mC/5hmC at CpG sequence in IGV.
`modkit adjust-mods` seemed the closest tool to do this, but I couldn't find how to specify option (`--ignore` or `--convert `?).
Is it possible to extract or exclude modification of target sequence from BAM file for visualization in IGV ?
I tried to manipulate `MM:Z` and `ML:B` tags by myself, but had not figured out how so far.
It would be better if target could be specified as `--motif `option of `modkit pileup`.

**Comment by ArtRand** [comment]
Hello @miwi610,

You can remove the 6mA calls with `modkit adjust-mods`:

```bash
$ modkit adjust-mods $modbam $adjusted --ignore a
```

As of IGV [2.17.0](https://igv.org/doc/desktop/#DownloadPage/) there are a lot more options for coloring base modifications. Maybe there is a way to disable some modifications - I haven't played around with it enough to say. 

Currently there is not a way to filter base modifications to specific motifs _on reads_ in a modBAM. Probably the closest thing is `modkit extract $modbam $extract_tsv --cpg --ref $ref --read-calls $calls_tsv` where you'll only get rows for base modification calls that are aligned to reference CpGs. I think what you're asking for is a reasonable feature, so we can add it to the roadmap for a future release.

**Comment by miwi610** [comment]
Thank you @ArtRand for your quick response and taking my question reasonable.
For visualization of 5mC at only CpG, but not CpH, I will go through IGV 2.17.X when the bug fix version, 2.17.1 for mac is released.
And I found the output of `modkit extract --cpg` could also be used to obtain what I needed to know, next.
After visualization, I would like to know the average or local 5mC level at CpG in each read and correlate with duplex pair or other modifications.
Extracting 5mC at CpG only can be done by re-running `dorado basecaller` with `5mCG_5hmCG` model, but it costs another few days and computer resources for each ONT run😢
Thank you for developing nice tool👍

**Comment by ArtRand** [comment]
@miwi610 
> And I found the output of modkit extract --cpg could also be used to obtain what I needed to know, next.
You should be aware that this will filter the output to _reference_ CpG dinucleotides - not base call CpGs. 
> After visualization, I would like to know the average or local 5mC level at CpG in each read and correlate with duplex pair or other modifications.
If you need read-level information `modkit extract` is the way to go. 
> Extracting 5mC at CpG only can be done by re-running dorado basecaller with 5mCG_5hmCG model, but it costs another few days and computer resources for each ONT run
I would not re-basecall just to subset the calls to CpGs! The information is already in there and the predictions will be the same.

**Comment by charlenelawdes** [comment]
I would also like to second this enhancement request

**Comment by KunFang93** [comment]
Hi @ArtRand,

Sorry for bothering you but I wondered if there is good way to only keep 6mA information (call both 5mC_5hmC and 6mA) by using adjust-mods? I tried to use 
```
modkit adjust-mods bc.srt.filt.ori.bam bc.srt.filt.ori.onlyA.bam -t 30 --motif AT 0
```
but got
```
error: unexpected argument '--motif' found

  tip: to pass '--motif' as a value, use '-- --motif'

Usage: modkit adjust-mods <IN_BAM|OUT_BAM|--log-filepath <LOG_FILEPATH>|--ignore <IGNORE>|--threads <THREADS>|--ff|--convert <CONVERT> <CONVERT>|--edge-filter <EDGE_FILTER>|--invert-edge-filter|--output-sam|--filter-probs|--num-reads <NUM_READS>|--sample-region <SAMPLE_REGION>|--sampling-interval-size <SAMPLING_INTERVAL_SIZE>|--filter-percentile <FILTER_PERCENTILE>|--filter-threshold <FILTER_THRESHOLD>|--mod-threshold <MOD_THRESHOLDS>|--only-mapped|--suppress-progress>

For more information, try '--help'.
```

The --motif seems deprecated though it still in the documentation. 

Will these works or if there is a better way to do it?
```
modkit adjust-mods bc.srt.filt.ori.bam bc.srt.filt.ori.tmp.bam --ignore h
modkit adjust-mods bc.srt.filt.ori.tmp.bam bc.srt.filt.ori.onlyA.bam --ignore m
```

Thanks in advance!

Best,
Kun
