### ISSUE TITLE
Possible option to constrain `summary` only to the aligned bases?

### ISSUE THREAD

**Issue by qiangfu-eu** [nanoporetech/modkit#12]
We have some cfDNA sample sequenced, and we would like to also check methylation information. However, we noticed a big difference between statistics generated by counting from bed file, and calculated by `summary`. See below.

Note that in this sample, we used 5mC only model to do base calling.

First, I run `pileup` with default setting, then I calculate statistic using `awk`. I also show the log file of `pileup` run. There is no error or issues showing.

```
> modkit pileup PAK67493_barcode19_5mC_sorted.bam puc19.pileup.bed --ref neb_puc19.fa --log-filepath puc19.pileup.log 
> awk '$4=="m" {can+=$13; mod+=$12; oth+=$14; valid+=$10; del+=$15; filter+=$16; diff+=$17; nocall+=$18} END{print (can) " ("(can/valid)") CpG canonical\n" (mod) " (" (mod/valid) ") 5mCpG modified\n" (oth) " (" (oth/valid) ") 5hmCpG modified\n" (valid) " total valid \n" (filter) " filtered, " (diff) " diff nt, " (del) " del, " (nocall) " nocall."}' puc19.pileup.bed
163204 (0.139098) CpG canonical
1010099 (0.860902) 5mCpG modified
0 (0) 5hmCpG modified
1173303 total valid
101811 filtered, 4990799 diff nt, 52618 del, 3183387 nocall.
> cat puc19.pileup.log
[src/logging.rs::54][2023-05-04 12:04:26][DEBUG] command line: modkit pileup PAK67493_barcode19_5mC_sorted.bam puc19.pileup.bed --ref neb_puc19.fa --log-filepath puc19.pileup.log
[src/commands.rs::122][2023-05-04 12:04:26][INFO] sampling 10042 reads from BAM
[src/reads_sampler.rs::190][2023-05-04 12:04:26][DEBUG] sampled 10042 records
[src/commands.rs::700][2023-05-04 12:04:26][WARN] Threshold of 0.6074219 for base C is low. Consider increasing the filter-percentile or specifying a higher threshold.
[src/commands.rs::839][2023-05-04 12:04:42][INFO] Done, processed 2452 rows.
```

Then I run `summary`, I show output of `summary`, and the log file. I used `--sampling-frac 1.0` option to summarize from all reads.

```
>modkit summary --log-filepath puc19.summary.log --sampling-frac 1.0 PAK67493_barcode19_5mC_sorted.bam > puc19.summary
> cat puc19.summary
mod_bases       C
count_reads_C   139229
C_calls_unmodified      1114267
C_frac_unmodified       0.39316085211485025
C_filtered_unmodified   172961
C_calls_modified_m      1719858
C_frac_modified_m       0.6068391478851497
C_filtered_modified_m   130193
C_total_mod_calls       2834125
C_total_filtered_mod_calls      303154
total_reads_used        139229
> cat  puc19.summary.log
[src/logging.rs::54][2023-05-04 12:11:40][DEBUG] command line: modkit summary --log-filepath puc19.summary.log --sampling-frac 1.0 PAK67493_barcode19_5mC_sorted.bam
[src/commands.rs::90][2023-05-04 12:11:40][INFO] sampling 100% of reads
[src/reads_sampler.rs::190][2023-05-04 12:11:43][DEBUG] sampled 139229 records
[src/summarize.rs::88][2023-05-04 12:11:43][INFO] calculating threshold at 10% percentile
[src/thresholds.rs::98][2023-05-04 12:11:43][DEBUG] calculating per base thresholds
[src/thresholds.rs::101][2023-05-04 12:11:44][DEBUG] probs per base took 1s
[src/thresholds.rs::111][2023-05-04 12:11:44][DEBUG] filter thresholds took 0s
[src/thresholds.rs::116][2023-05-04 12:11:44][INFO] calculated thresholds: C: 0.6074219
[src/summarize.rs::172][2023-05-04 12:11:45][DEBUG] computing summary took 0s
[src/writers.rs::268][2023-05-04 12:11:45][WARN] this output format will not be default in the next version, the table output (set with --table) will become default and this format will require the --tsv option
```

However, the calculated statistics are quite different.  

Then I recalled that when doing alignment, only half of the bases are aligned in our sample, as we run Short Fragment Mode of nanopore as our sample are cfDNA of short length. Without trimming of adapter (due to the issue associated with MM/ML see #11), almost half of the bases are not mapped (softclip). I suppose during `pileup`, the methylation calls on those bases do not contributing to Nmod, Ncanonical, and Nothermod (hence counted as valid), rather assigned to Nnocall (?). As the fraction are high in our case, the statistics `summary` calculated are then very different from what is summerized from BED file.

I wonder whether it is possible to provide an option to restrict `summary` calculation only on mapped region of the read sequence. However, that might be against the whole purpose of `summary` as a quick alternative to generate statistics before doing full `pileup` calculation.

But at least, it is then worth mentioning in the document that the base mapping rate will strongly influence the `summary` outcome when compared with the statistics calculated from BED file.

Thanks.

**Comment by ArtRand** [comment]
Hello @qiangfu-eu 

If you're doing 5mCG analysis, you may consider using the `--cpg` flag (I see you have the reference there), which will restrict the output to CpG sites only. Softclipped bases aren't counted in `pileup`, as you noticed, but N_nocall bases are where the read has the correct base, but there isn't a base modification call (see the [docs](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#definitions)). This can happen with the CG models when the C is followed by something other than a G in the read sequence. You may also consider updating to 0.1.5 for `summary` which allows more flexibility with respect to estimating thresholds while still summarizing the whole BAM. 

In response to your question, however, I've also thought about this feature (summary with mapped only). It becomes very similar to pileup, however, and pileup can offer more downstream utility. In the mean time, I'd recommend using the `--cpg` option with pileup if you want to calculate statistics on mapped bases only.

**Comment by qiangfu-eu** [comment]
Thanks. I also think it might be best just use `pileup` for more precise statistics.
