### ISSUE TITLE
Pull different methylation types from different bam files

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#124]
Hi Arthur,

Rerio currently has separate models for calling 4mC, 5mC, and 6mA (in different combinations). 

I was wondering if you have a method, or perhaps (if useful) could add on to modkit, to get the methylation modifications for the same reads from different `bam` files output by the different models. The idea here would be to pick one of the bam files as the reference, then append the methylation types missing from the secondary bams onto a copy of that reference. I assume this might be a bit complicated, a need to match up read IDs, resolve conflicts, etc. 

Would this be a good use case of the `--combine` flag?

**Comment by ArtRand** [comment]
Hello @Ge0rges,

Yes, I've had something in mind like that. We're going to have a few more "quality of life" features coming out in the next few releases. 

Just so you know, you can basecall + modcall with `dorado` using multiple models at once:

```
dorado basecaller .. \
    --modified-bases-models ${4mC_5mC_model},${6mA_model}
    > ${reads_w_4mC_5mC_and_6mA.bam}
```

A

**Comment by Ge0rges** [comment]
Thank you that's a good solution. Feel free to close this issue.

**Comment by ArtRand** [comment]
You're welcome, thanks for the suggestion as well.
