### ISSUE TITLE
% in modkit pileup Vs modkit extract 

### ISSUE THREAD

**Issue by Macdot3** [nanoporetech/modkit#129]
Hi, 
I ran analysis of my mod.bam files with modkit pileup and modkit extract and I don't understand why my methylated bases have different positions in some cases with these two commands.
Also, I read about to generate % methylation by base position in this iusse #87 
Can I use the same polars code for all my locations? Even though it is written max_read_position = 200?
Thanks for the support and explanation.

**Comment by ArtRand** [comment]
Hello @Macdot3,

> I ran analysis of my mod.bam files with modkit pileup and modkit extract and I don't understand why my methylated bases have different positions in some cases with these two commands.

Could you give me a little more detail about what you're seeing, and maybe provide an example? The output from `modkit extract` has the read position and the aligned reference position for each read whereas `pileup` aggregates all the reads at each reference position. 

You can use the same polars code to aggregate on read position. If you have long reads, and thus a lot of unique read positions, this could be compute intensive - but not impossible. If you want to aggregate on reference position I recommend just using `modkit pileup` since that's what it's designed to do.

**Comment by Macdot3** [comment]
For example:
```
chr1	17483	17484	h	1	-	17483	17484	255,0,0	1 0.00 0 0 1 0 0 0 0
chr1	17483	17484	m	1	-	17483	17484	255,0,0	1 100.00 1 0 0 0 0 0 0
and
6cf7668c-efcd-427e-8a2b-a12e06350d6f	376	17452	chr1	+	-	-	37	401	986	0.41210938	h	7	.	CACGC	C	C	false	16
6cf7668c-efcd-427e-8a2b-a12e06350d6f	376	17452	chr1	+	-	-	37	401	986	0.5761719	m	7	.	CACGC	C	C	false	16

```
It seems like you note a different position on the ref, am I wrong? Maybe you already answered me in your comment above but I would like to understand.

Regarding the percentage, yes, I would like to add the value to each base therefore called to the ref position. So in your polaris script do I have to use modkit pileup output bed? Do I need to add any other options in your opinion?

Thank you

**Comment by ArtRand** [comment]
@Macdot3 

Would you be willing to share the BAM file containing this read (`6cf7668c-efcd-427e-8a2b-a12e06350d6f`) as well as the reference (if it's not something easily publicly available). You can just attach it to this thread.

> Regarding the percentage, yes, I would like to add the value to each base therefore called to the ref position.

All you need to do is `modkit pileup`, it will aggregate the base modification counts for each base modification detected at all of the covered reference positions. The polars code is to aggregate the modification counts _per read position_ which is a pretty specific use case that sounds different from what you're doing here. As far as options, running `modkit pileup` with just the defaults ([documentation](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#basic-usage)) is a sensible way to start. If you know you're going to be doing CpG analysis, you may consider using `--cpg` (and `--ref`).

**Comment by Macdot3** [comment]
Here is the BAM filtered for the reads ID. 
[bar6.zip](https://github.com/nanoporetech/modkit/files/14295352/bar6.zip)
To create this BAM I aligned to hg38 reference. 
To create both BED and TSV files I simply used `modkit pileup` and `modkit extract`.

Let me explain better about the percentage. I'd like to create  to create something similar to what the calculate_methylation_frequency.py script does on nanopolish's tsv output. And in fact you are right about what you tell me. I apologize for the confusion.
So should I work using your polaris script on `modkit extract --read-calls` output file? It's correct?

**Comment by ArtRand** [comment]
Hello @Macdot3,

Thanks for sending the modBAM over. I ran the following commands on your file

```text
# try with filtering threshold 0.8 since I can't estimate the threshold with only 1 read.
modkit pileup ./bar6.bam pileup_ft08.bed \
  --log-filepath log.txt \
  --filter-threshold 0.8
modkit extract ./bar6.bam extract_ft08.tsv \
  --read-calls calls_ft08.tsv \
  --log-filepath log.txt \
  --force --filter-threshold 0.8

# try without filtering
modkit pileup ./bar6.bam pileup.bed \
  --no-filtering --log-filepath log.txt
````

In both cases what I'm seeing makes sense:

The pileup without filtering reports 32 reference positions with modification calls. Position 17452 and 17483 are there
In the pileup without filtering:
```text
chr1    17452   17453   h       1       -       17452   17453   255,0,0 1 0.00 0 0 1 0 0 0 0
chr1    17452   17453   m       1       -       17452   17453   255,0,0 1 100.00 1 0 0 0 0 0 0

chr1    17483   17484   h       1       -       17483   17484   255,0,0 1 0.00 0 0 1 0 0 0 0
chr1    17483   17484   m       1       -       17483   17484   255,0,0 1 100.00 1 0 0 0 0 0 0
```

However in the pileup _with_ filtering at 0.8 only 17483 is reported and 17452 is filtered out.

If I look at the calls_ft08.tsv I can see that this position fails:
```text
read_id                               forward_read_position  ref_position  chrom  mod_strand  ref_strand  ref_mod_strand  fw_soft_clipped_start  fw_soft_clipped_end  read_length  call_prob  call_code  base_qual  ref_kmer  query_kmer  canonical_base  modified_primary_base  fail   inferred  within_alignment  flag
6cf7668c-efcd-427e-8a2b-a12e06350d6f  376                    17452         chr1   +           -           -               37                     401                  986          0.5761719  m          7          .         CACGC       C               C                      true   false     true              16
```
because the `call_prob` is only 0.57 which is lower than the requires 0.80. Similarly if you look at the extract_ft08.tsv:
```text
read_id                               forward_read_position  ref_position  chrom  mod_strand  ref_strand  ref_mod_strand  fw_soft_clipped_start  fw_soft_clipped_end  read_length  mod_qual     mod_code  base_qual  ref_kmer  query_kmer  canonical_base  modified_primary_base  inferred  flag
6cf7668c-efcd-427e-8a2b-a12e06350d6f  376                    17452         chr1   +           -           -               37                     401                  986          0.41210938   h         7          .         CACGC       C               C                      false     16
6cf7668c-efcd-427e-8a2b-a12e06350d6f  376                    17452         chr1   +           -           -               37                     401                  986          0.5761719    m         7          .         CACGC       C               C                      false     16
```

I am not super familiar with the calculate_methylation_frequency.py script, but from a quick read of the [docs](https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html) it sounds like the fraction modified in the `modkit pileup` output is what you want.

**Comment by Macdot3** [comment]
Thank you very much, I understood that the difference I saw was related to the threshold filter, otherwise it couldn't have been different. I run without threshold filter.
So, I'll try using the output from modkit pileup as input for your Polars script. I just have one more thing to ask you. Can you explain the setting `read_position_max = 200?` If I wanted to calculate the percentage for all reads at the reference position, should I remove this limitation? Thank you so much for your support.

**Comment by ArtRand** [comment]
@Macdot3

> So, I'll try using the output from modkit pileup as input for your Polars script.
I wouldn't do this - this isn't what the polars code is for. The output from `pileup` ([documented here](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#bedmethyl-column-descriptions)) already has the %modification at that reference position.

**Comment by Macdot3** [comment]
It is true! I hadn't noticed the `fraction modified` and it wasn't easy to read it visually from the bed numbers since the header is missing. Perfect!
Thank you so much @ArtRand  for the support and discussion

**Comment by ArtRand** [comment]
@Macdot3 Great, feel free to re-open this issue if you have any further questions.
