### ISSUE TITLE
pyspoa

### ISSUE THREAD

**Issue by kawito** [nanoporetech/modkit#138]
I am installing:
git clone https://github.com/bioinfo-biols/CIRI-long.git CIRI-long 
 
It worked before when I was analyzing last June.
 
Today, it says "error" at this step.
Are there any helps for this problem?
 
Thank you for your help.
 
###
Collecting pyspoa>=0.0.5
  Using cached pyspoa-0.2.1.tar.gz (52 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyspoa
  Building wheel for pyspoa (pyproject.toml) ... error
  error: subprocess-exited-with-error
 
  × Building wheel for pyspoa (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      running bdist_wheel
      running build
      running build_ext
      -- The CXX compiler identification is GNU 4.8.5
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at /tmp/pip-build-env-odbh3g96/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find ZLIB: Found unsuitable version "1.2.7", but required is at
        least "1.2.8" (found /usr/lib64/libz.so, )
      Call Stack (most recent call first):
        /tmp/pip-build-env-odbh3g96/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
        /tmp/pip-build-env-odbh3g96/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.28/Modules/FindZLIB.cmake:199 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
        build/_deps/bioparser-src/CMakeLists.txt:22 (find_package)
 
 
      -- Configuring incomplete, errors occurred!
      make[1]: Entering directory `/tmp/pip-install-7zlblq_f/pyspoa_d8a5b273ea63440f810e29167fb63d8c/src/build'
      make[1]: *** No targets specified and no makefile found.  Stop.

**Comment by ArtRand** [comment]
Hello @kawito, 

Pardon my confusion, but it seems like this issue is not related to [modkit](https://github.com/nanoporetech/modkit/)? Perhaps you meant to open an issue on the repo for the [CIRI-long](https://github.com/bioinfo-biols/CIRI-long/issues) project?

**Comment by kawito** [comment]
I got a comment from CIRI-long project:
you could first install pyspoa 0.05 by running pip install pyspoa==0.0.5, then try to install CIRI-long again.

But I got an error message:
$ pip install pyspoa==0.0.5
ERROR: Could not find a version that satisfies the requirement pyspoa==0.0.5 (from versions: 0.0.6, 0.0.7, 0.0.8a0, 0.0.8, 0.1.0, 0.2.0, 0.2.1)
ERROR: No matching distribution found for pyspoa==0.0.5

How can I install pyspoa 0.05?

**Comment by kawito** [comment]
I am writing comment under the direction of  ONT customer services: 

Thank you for writing into ONT.

Regarding your question, pyspoa is our development phase product, 
Therefore, would you please post your question on issue page of pyspoa in Github page.

[https://github.com/nanoporetech/pyspoa/issues](https://github.com/nanoporetech/modkit/issues)

With posting your question in Github, you will receive answer from our development team directly.

If you have no other question, I will proceed to close this case in our support system.

Best regards,

Guihua Jin PhD
Technical Application Scientist (Japan)
K.K. Oxford Nanopore Technologies
email: [support@nanoporetech.com](mailto:support@nanoporetech.com)
