### ISSUE TITLE
Using multiple samples in modkit dmr

### ISSUE THREAD

**Issue by ArnavBharti** [nanoporetech/modkit#140]
I have 5 control samples and 2 treatment samples. I used dmr multi and got multiple bed files since it does pairwise dmr. 
Is it viable to use 'samtools merge' to combine the bam files and run modkit dmr pair?

These are not biological replicates. They are different and I have bam files for each of them individually.

**Comment by ArtRand** [comment]
Hello @ArnavBharti,

Funny you should ask, the [modkit v0.2.5](https://github.com/nanoporetech/modkit/releases/tag/v0.2.5) will do just what you're thinking. You can use `modkit dmr pair` with multiple replicates ([docs](https://nanoporetech.github.io/modkit/intro_dmr.html#3-detecting-differential-modification-at-single-base-positions)). That being said, without more details on your experimental design it is difficult for me to make strong recommendations.

**Comment by PRIYANKA-22091995** [comment]
Hello Team,

Could you please elaborate more on modkit v0.2.5, as i also have the same query that if i have multiple control samples and treatment samples(with same disease condition) and i have concatenated all the bam files and if i run dmr pair, is it advisable to follow this approach. It would be nice to have your insights on the same.
Thanks in advance.

**Comment by lance0499** [comment]
Hi @ArnavBharti, 

I am having trouble inputting multiple replicates into modkit dmr pair, because the command is not allowing me to. Were you able to manage? 

Lance

**Comment by ArnavBharti** [comment]
Have you upgraded the modkit program? It was throwing an error on my side too saying "error: the argument '-a <CONTROL_BED_METHYL>' cannot be used multiple times".

I pulled the repo again and built it. It is running and finishing succesfully

**Comment by lance0499** [comment]
Hi @ArnavBharti,

Thanks a lot. Pulling the repo manually again made it work.
Much appreciated.

**Comment by ArnavBharti** [comment]
> Hello @ArnavBharti,
> 
> Funny you should ask, the [modkit v0.2.5](https://github.com/nanoporetech/modkit/releases/tag/v0.2.5) will do just what you're thinking. You can use `modkit dmr pair` with multiple replicates ([docs](https://nanoporetech.github.io/modkit/intro_dmr.html#3-detecting-differential-modification-at-single-base-positions)). That being said, without more details on your experimental design it is difficult for me to make strong recommendations.

The sample I have is sequencing of same vector, one carrying disease and one not. The control is from 5 sources. And the treatment from 2.

I used this command. It is showing the output `finished, processed 0 sites successfully, 2327053 failed`.

**Comment by ArtRand** [comment]
@ArnavBharti 

> I used this command. It is showing the output finished, processed 0 sites successfully, 2327053 failed.

Could you show me the command you're using?

**Comment by ArnavBharti** [comment]
```
modkit dmr pair \
  -a sequencing/SEQUENCING_ANALYSIS/.../pass/pileup.bed.gz \
  -a sequencing/SEQUENCING_ANALYSIS/.../pass/barcode01/pileup.bed.gz \
  -a sequencing/SEQUENCING_ANALYSIS_1/.../pass/barcode02/pileup.bed.gz \
  -a sequencing/SEQUENCING_ANALYSIS_1/.../pass/barcode01/pileup.bed.gz \
  -a sequencing/SEQUENCING_ANALYSIS/.../pass/barcode01/pileup.bed.gz \
  -b sequencing/SEQUENCING_ANALYSIS/.../pass/barcode02/pileup.bed.gz \
  -b sequencing/SEQUENCING_ANALYSIS/.../pass/barcode10/pileup.bed.gz \
  --ref PlasmoDB-..._Genome.fasta \
  --base C \
  -o dmr_out \
  -t 10 \
  -f
```
>Maybe decrease the valid coverage requirement?

I will try this

**Comment by ArtRand** [comment]
@ArnavBharti there is currently a limitation that requires the number of `a` samples to be the same as the number of `b` samples. The debug log would mention this. I can get you a build without this restriction, (it shouldn't exist anyways).

**Comment by ArtRand** [comment]
@ArnavBharti any luck?

**Comment by ArnavBharti** [comment]
It is working all right
