### ISSUE TITLE
Modkit dmr pair not taking in multiple replicates

### ISSUE THREAD

**Issue by lance0499** [nanoporetech/modkit#142]
Hi,

According to the intro dmr html file, "dmr pair" should be able to take in mutliple replicates by repeating the -a and -b options. 

However, an error appears stating "the argument '-a <CONTROL_BED_METHYL>' cannot be used multiple times"

Here is the code I am using:

 modkit dmr pair -a Norm1.bed.gz -a Norm2.bed.gz -b Test1.bed.gz -b Test2.bed.gz -o dmrpair.bed --ref GCF_000001405.39_GRCh38.p13_genomic_chr_only_plus_mt.fa --base C --log-filepath dmr.log

Any help or info will be much appreciated. 
Thanks.

**Comment by ArtRand** [comment]
Hello @lance0499,

Could you check the version of modkit you have? You should see:

```text
$ modkit --version
# mod_kit 0.2.5
```

Using multiple samples in `dmr pair` is a new feature in 0.2.5.

**Comment by lance0499** [comment]
Hi @ArtRand, 

Yes, I do have the latest version 0.2.5 and it is still not working.

![image](https://github.com/nanoporetech/modkit/assets/162445489/151cc640-c311-40b2-a10e-f2c2cfa3668b)

**Comment by lance0499** [comment]
Hi!

I would also like to mention that I have tried reinstalling modkit and updating all my packages, to no avail.

Thanks for the help.

**Comment by lance0499** [comment]
Hi!

I would also like to mention that I have tried reinstalling modkit and updating all my packages, and it did not fix the problem.

Thanks for the help.
