### ISSUE TITLE
Is there a way to run dmr pair with multiple replicates with a region BED file?

### ISSUE THREAD

**Issue by lance0499** [nanoporetech/modkit#143]
Hi,

I have 5 control samples and 5 treated samples, and would like to run dmr analysis on only the CpG islands to compare the two groups. 

However, the only option I can see for multiple replicates is at single base positions (dmr pair with multiple -a and -b). Using dmr multi will just do pairwise comparisons as well, which will not compare all replicates in a group-based setting. 

Is there any way to be able to run DMR analysis with multiple replicates comparing two groups, while only focusing on specific regions like CpG islands? 

Thanks a lot for the help!

**Comment by ArtRand** [comment]
Hello @lance0499,

Currently there isn't a way to perform a region-based pairwise comparison using multiple replicates where the replicates are combined in some way. I'm working on something, but it's not ready yet. What I recommend is to run `dmr multi` like you have then look at regions that rank highly in all treatment/normal comparisons.

**Comment by wietingj** [comment]
@ArtRand, since I have the same problem as described above, I was wondering if you were able to implement some way to use modkit dmr pair with a regions bed with multiple samples at once per group in the meantime? 

Output (modkit v0.3.1):
> Error! in order to perform multiple comparisons over regions use modkit dmr multi

Many thanks for your feedback!

**Comment by ArtRand** [comment]
@wietingj Others have [asked](https://github.com/nanoporetech/modkit/issues/232) for this functionality as well, it'll get into the next big release.

**Comment by Yang990-sys** [comment]
Hello,
Is this feature added in this new version ?

**Comment by ArtRand** [comment]
Hello @Yang990-sys , @lance0499 , @wietingj 

As of [v0.4.0](https://github.com/nanoporetech/modkit/releases/tag/v0.4.0) when you use the same sample name in `modkit dmr multi` the samples will be combined. 

I'm working on some other ways to tease apart multiple samples and allow for exploration of within and inter-sample variablility bt it's not quite ready. Let me know if the current version solves your use case.
