### ISSUE TITLE
Is there a way to have modkit handle duplicate reads?

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/modkit#145]
I'm currently fighting a dorado bug right now where it is creating identical duplicate reads (not supp alignments, but literal duplicates). These are picked up by modkit during the sampling process but throws a ton of warnings during the pileup. Is there a way to process it with modkit to ignore the duplicate? Or is there a quick way to process the bam file? I'd rather not have to re-basecall everything when the bug is fixed in dorado as that is a lot of A100 usage...

**Comment by ArtRand** [comment]
@billytcl 

Definitely don't re-basecall everything.

Could you try `samtools markdup $basecalls_sorted.bam $basecalls_sorted_markdup.bam`? Records marked as duplicates should be quietly ignored.

I've attached a build where the logging has been suppressed, slightly. Please find it attached to this thread.
[modkit-dev0e8f7ae_centos7_x86_64.tar.gz](https://github.com/nanoporetech/modkit/files/14530921/modkit-dev0e8f7ae_centos7_x86_64.tar.gz)

**Comment by billytcl** [comment]
This looks great! Will give it a shot.

**Comment by ArtRand** [comment]
@billytcl , could you tell me if using `samtools markdup` solved the problem or you needed the custom build? (you can test with any released modkit version).

**Comment by ArtRand** [comment]
I have not included this fix into the latest release since it should be possible to pre-process the reads with `samtools`. I'd rather keep the verbose logging until we find that it cannot be handled upstream.
