### ISSUE TITLE
Failed modification calls

### ISSUE THREAD

**Issue by pwh124** [nanoporetech/modkit#15]
Hello,

I had a question about exactly what a "failed" modification call means. 

I am running the following modkit command on a modbam that includes both 5mC and 5hmC calls.

```
~/software/modkit_0.1.5/modkit pileup --log-filepath mod_calls/mod_forebrain.log \
-t24 \
--filter-threshold 0.8 \
--cpg \
--ref ~/references/mm39/mm39.fa \
--only-tabs \
alignments/mod.bam mod_calls/mods.bed
```
I've noticed that the number of "failed" modification calls (column 16 of pileup output) seems to be affected by changes in the thresholding. 

I have tested thresholds 0.8 and 0.1 just to see what happens. It appears that if I change the threshold from 0.8 to 0.1, calls that were formerly counted as "failed" are now counted as either 5mC or 5hmC.

Is this because at the 0.8 threshold, both probabilities for the modifications and the canonical base did not exceeded the threshold (>0.8)? So, for example, the base call would be called "failed" if the probabilities of canonical, 5hmC, and 5mC were something like 0.1, 0.6, 0.3? If neither modification meets the threshold, could it or should it be called canonical? Do the probabilities of the 3 states equal 1?

That brings me to a slightly broader question about how everything is being called. Let's say I am using the 0.8 threshold, do these scenarios below seem correct? Probabilities are listed as canonical, 5hmC, 5mC:
1. 0.9, 0.05, 0.05 - called canonical
2. 0.05, 0.9, 0.05 - called 5hmC
3. 0.05, 0.05, 0.9 - called 5mC
4. 0.20, 0.4, 0.4 - called as failed

Thanks for your help!

**Comment by ArtRand** [comment]
Hello @pwh124 ,

It looks like you're on the right track. Changing the threshold for 0.8 to 0.1 will allow more low-confidence base calls to end up counting towards `N_mod` or `N_canonical` ([columns reference](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#bedmethyl-column-descriptions)). 

>Is this because at the 0.8 threshold, both probabilities for the modifications and the canonical base did not exceeded the threshold (>0.8)? So, for example, the base call would be called "failed" if the probabilities of canonical, 5hmC, and 5mC were something like 0.1, 0.6, 0.3? 

That is correct.

> If neither modification meets the threshold, could it or should it be called canonical? 

If none of the output probabilities are above the threshold, no call is made (+1 N_fail). 

> Do the probabilities of the 3 states equal 1?

Yes. Or at least they should according to the ML tag specification.


```
1.    0.9, 0.05, 0.05 - called canonical
2.    0.05, 0.9, 0.05 - called 5hmC
3.    0.05, 0.05, 0.9 - called 5mC
4.    0.20, 0.4, 0.4 - called as failed
```
These are all correct. 

In the next release there will be the ability to have a different threshold for each class so you'll be able to do something like this:

```
thresh_5mC = 0.9
thresh_5hmC = 0.9
thresh_C = 0.7

0.75, 0.10, 0.15 - called canonical
0.15, 0.10, 0.75 - called failed
```

**Comment by pwh124** [comment]
Thanks for answering all my questions @ArtRand, I appreciate it!

All of this is great to know!

I am going to close this, but it could be opened back up the info is useful to anyone.

**Comment by ArtRand** [comment]
@pwh124 One last bit. Version 0.1.5 added a `--hist` (requires `-o <dir>`) option to `sample-probs` that will show you the per-primary base/per-mod output probability distributions. Looking at these can be handy for EDA.
