### ISSUE TITLE
--ignore argument doesn't ignore modifications properly

### ISSUE THREAD

**Issue by kaanokay** [nanoporetech/modkit#151]
Hi,

I ran the samples using `MinKNOW` `v23.07.12` and `Guppy` `v7.1.4`. Only 5mC and 5hmC modifications were called with `MinKNOW`. I combined the bam files in the bam_pass folder and then aligned the unaligned bam files to the reference genome with `minimap2`. Using aligned bam files, I ran the `modkit` `v0.2.0` with and without the `--ignore` argument. The results I got for 5mC and 5hmC were different for the same CpGs when I used the `--ignore` argument and when I did not. Below you can see the results I got.

for `chr10:3103871-3103872` coordinate:

without `--ignore` argument, number of reads with 5mC is 11 in 5mC bedMethly file, number of reads with 5hmC is 1 in 5hmC bedMethly file, number of reads with canonical bases is 6 in both 5mC and 5hmC bedMethly files. FYI, after getting one bedMethly file without `--ignore `argument, I subset bed file to 5mC and 5hmC by using `m` and `h` tags.

However, with `--ignore` argument, number of reads with 5mC is 12 in 5mC bedMethly file (5hmC ignored by `--ignore h`), number of reads with 5hmC is 18 in 5hmC bedMethly file (5mC ignored by `--ignore m`), number of reads with canonical bases is 6 in 5mC bedMethly file but number of reads with canonical bases is 7 in 5hmC bedMethly file.

![Screenshot from 2024-04-04 10-42-27](https://github.com/nanoporetech/modkit/assets/42235353/87bc28ad-89a3-4f85-9921-1a188a93c68b)

However:

for `chr10:3100520-chr10:3100521` coordinate: number of reads for 5mC and 5hmC is consistent between without `--ignore` and with `--ignore` arguments:

without `--ignore` argument:

number of reads with 5mC is 12 in 5mC bedMethly file, number of reads with canonical bases is 3 in 5mC bedMethly file. The number of reads with 5hmC is 2 and number of reads with canonical bases is 3 in 5hmC bedMethly file.

with `--ignore` argument:

The number of reads with 5mC is 12, number of reads with canonical reads is 3 in 5mC bedMethly file (5hmC ignored by `--ignore h`). The number of reads with 5hmC is 14, number of reads with canonical bases is 3 in 5hmC bedMethly file (5mC ignored by `--ignore m`). In 5hmC bedMethly file, number of reads with supposed to be 2 rather than 14? does 5hmC file has both 5mC and 5hmC reads that's why number of reads is 14 (12 5mC reads + 2 5hmC reads)?

![Screenshot from 2024-04-04 11-29-15](https://github.com/nanoporetech/modkit/assets/42235353/dbfad5f7-958d-4c61-a30c-a471d383dd27)

Should I use `--ignore` argument to get number of reads or not? In my opinion, number of reads with 5hmC should be less than number of reads with 5mC, so in this case, I'm feeling like I should not use `--ignore` argument instead I should run modkit without` --ignore` argument to get bedMethly file with both 5mC and 5hmC modifications and then subset those modifications manually in R.

Should `modkit` `v0.2.0` be updated to latest version to do modification calling more accurately?

All the best.

**Comment by ArtRand** [comment]
Hello @kaanokay,

From the snippets you've shown me, everything is adding up correctly. Let's take the first example:

| default settings | |     |
|------------|------|------|
| file       |  5mC | 5hmC |
| valid_cov  |  18  | 18   |
| m          |  11  | 11   |
| canonical  |   6  |  6   |
| h          |   1  |  1   |
| fail       |   8  |  8   |
| total      |  26  | 26   |


| ignore m or h | |     |
|------------|------|------|
| file       |  5mC | 5hmC |
| valid_cov  |  18  | 25   |
| m          |  12  |  0   |
| canonical  |   6  |  7   |
| h          |   0  | 18   |
| fail       |   8  |  1   |
| total      |  26  | 26   |

Where `total = valid_cov + fail` and `valid_cov` _should equal_ sum(mod_counts) + canonical. This assertion checks in both cases. The `total` should be the same in both settings (ignore or default).

Then for the second example:

| default settings | |     |
|------------|------|------|
| file       |  5mC | 5hmC |
| valid_cov  |  17  | 17   |
| m          |  12  | 12   |
| canonical  |   3  |  3   |
| h          |   2  |  2   |
| fail       |   1  |  1   |
| total      |  18  | 18   |


| ignore m or h | |     |
|------------|------|------|
| file       |  5mC | 5hmC |
| valid_cov  |  15  | 17   |
| m          |  12  |  0   |
| canonical  |   3  |  3   |
| h          |   0  | 14   |
| fail       |   3  |  1   |
| total      |  18  | 18   |

In both cases using `--ignore m` is changing the number of `Nfail` calls, likely by lowering the threshold and including more reads. You can see the first and second example the `fail` goes from 8 to 1 and 3 to 1, respectively.

The purpose of `--ignore` is to remove one of the modifications from the analysis, the details on how this is done is provided in the [documentation](https://nanoporetech.github.io/modkit/collapse.html).

> I'm feeling like I should not use --ignore argument instead I should run modkit without --ignore argument to get bedMethly file with both 5mC and 5hmC modifications and then subset those modifications manually in R.

You are correct. If you want to subset the calls, I would not use `--ignore` and instead filter the output for rows with the appropriate modification code.

**Comment by kaanokay** [comment]
Dear @ArtRand

Thank you so much for your quick response.

I have additional questions, I'd happy to have answer for them too.

1. In first example, once 5hmC ignored, a read with 5hmC is being added to reads with 5mC? because number of reads with 5hmC is 1 and number of reads with 5mC is 11 in default settings. Once 5hmC is ignored, number of reads with 5hmC became 0 but number of reads with 5mC became 12 from 11. So, number of reads with 5mC has actually both 5mC and 5hmC modifications? That's confusing to me.


2. Once I want to split modkit output to 5mC and 5hmC in R, as below:

`subset.5hmC <- subset(both.5mC.and.5hmC, both.5mC.and.5hmC$modified_base_code == "h")`

`subset.5mC <- subset(both.5mC.and.5hmC, both.5mC.and.5hmC$modified_base_code == "m")`

in each subset, total number of reads (coverage) should be calculated like: `Nmod + Ncanonical`. So I should not use Nvalid_cov column as coverage because it has reads with 5mC, 5hmC, and canonical bases, right? For each 5mC and 5hmC subset, I should calculate coverage separately by summing `Nmod + Ncanonical` columns?


3. I want to use `--cpg` argument to keep only CpGs in the genome but I'm unsure about `--mask` argument to respect soft masking in the reference FASTA. What is aim of this argument in case of CpG-level analysis? What does that argument do?

All the best.

**Comment by ArtRand** [comment]
Hello @kaanokay 

To your first question.

In the first example when `--ignore h` is passed, it appears that the single read reporting `h` is classified as `m`. However, this may not always be the case. Here's a worked example:


```text
# take P_m to mean the probability of m or h and P_can to be the probability of a canonical base

P_m = 0.3
P_h = 0.6
P_can = 0.1

# if we ignore h we redistribute P_h over the other classes

P_m = 0.3 + (0.6 / 2) = 0.9
P_can = 0.1 + (0.6 / 2) = 0.4

# If the pass threshold is < 0.9, the most likely call, the call will be `m` - this is what you observe in this example.
# Now consider if the probabilities were slightly different

P_m = 0.1
P_h = 0.6
P_can = 0.3 # notice that P_can is higher now

# doing the same transformation to ignore h

P_m = 0.1 + (0.6 / 2) = 0.4
P_can = 0.3 + (0.6 / 2) = 0.9

# if the threshold is the same, the call will now be a canonical base.
```

The behaviour that you're looking for might be similar to `--combine-mods` where all modification calls are summed together, please review the [documentation](https://nanoporetech.github.io/modkit/collapse.html) for details.

To your second question. 

Once you subset the bedMethyl records, the correct total coverage is `N_valid_cov` not `N_mod + N_canonical`.

Lastly, the `--mask` option will ignore regions that have been designated as "soft masked" which is denoted as [lower case](https://biology.stackexchange.com/questions/45275/significance-of-upper-case-lower-case-and-ns-in-ucsc-dna-files) nucleotide letters. Usually these are repeats or similar. I can't advise you on whether or not you want to use this option for your specific experiment. We don't use the `--mask` option in our [workflows](https://github.com/epi2me-labs/wf-human-variation/blob/master/workflows/methyl.nf#L1) if that helps you make a decision.

**Comment by ArtRand** [comment]
@kaanokay Great, feel free to re-open this issue if you have any additional questions.

**Comment by kaanokay** [comment]
Hi Arthur again,

I'm confused about probability distribution. Once 5hmC probability re-distributed over probabilities of 5mC and unmodified bases, sum of probability still supposed to be equal to 1? Its not the case.

`P_m = 0.3 + (0.6 / 2)` = 0.9 supposed to be `P_m = 0.3 + (0.6 / 2) = 0.6`?
`P_can = 0.3 + (0.6 / 2)` = 0.9 supposed to be `P_can = 0.3 + (0.6 / 2) = 0.6`?

Now then, sum of probability is being 1.
