### ISSUE TITLE
modkit installation

### ISSUE THREAD

**Issue by mocherry** [nanoporetech/modkit#152]
Dear all,

I have a very very basic question about installing Modkit on a Windows system running Ubuntu in WSL:
It is said: Pre-compiled binaries are provided for Linux from the [release page](https://github.com/nanoporetech/modkit/releases).

Now there I find a ...tar.gz file.

Alas, I do not know how to proceed with this. Do I just unpack it and be done, or do I have to use some fancy command like conda install or similar?

Sorry for this naive question, but I am just learning how to do things with Ubuntu and do not know all the ins and outs. Maybe someone has mercy with me and can point me in the right direction.

Thanks and best,
Matthias

**Comment by jubelik** [comment]
Dear,

If anyone has a solution for the explained issue, I would be happy to read the answer. Conda environment is not a possibility for me. 

Thanks.
