### ISSUE TITLE
Modification codes

### ISSUE THREAD

**Issue by IanCodes** [nanoporetech/modkit#157]
Is there a reference for the possible modification codes represented by modKit?  I have seen C, m , h, etc, but no explanation to their exact meaning.  Apologies if this is already explained.

**Comment by IanCodes** [comment]
I think I answered this myself:
https://samtools.github.io/hts-specs/SAMtags.pdf

**Comment by ArtRand** [comment]
Hello @IanCodes, 

That specification is exactly what I would recommend. One additional detail is, since there is no "code" for canonical bases (`C` means "any C-mod, for example). The output in `modkit` will often use `-` to mean canonical.

**Comment by IanCodes** [comment]
Just a point for future readers, in the above "C means "any C-mod", looks like a lower case c, but is uppercase.
