### ISSUE TITLE
error: failed to run custom build command for `libz-sys v1.1.16`

### ISSUE THREAD

**Issue by habibsaky** [nanoporetech/modkit#167]

**Comment by habibsaky** [comment]
Can you please help me to install  modkit software.. i am getting some error.

(base) [mmolla@dg-gpunode05 bin]$ cd
(base) [mmolla@dg-gpunode05 ~]$ cargo install --git https://github.com/nanoporetech/modkit.git
    Updating git repository `https://github.com/nanoporetech/modkit.git`
  Installing mod_kit v0.2.7 (https://github.com/nanoporetech/modkit.git#3e75aa4d)
    Updating crates.io index
Compiling hts-sys v2.1.1
   Compiling arc-swap v1.7.1
error: failed to run custom build command for libz-sys v1.1.16 #167

error: failed to compile `mod_kit v0.2.7 (https://github.com/nanoporetech/modkit.git#3e75aa4d)`, intermediate artifacts can be found at `/tmp/cargo-installYiDnjI`.

**Comment by ArtRand** [comment]
Hello @habibsaky could you tell me a what kind of environment you're using? Is there more output you're getting from `cargo` my guess is that you need some system libraries.

**Comment by habibsaky** [comment]
(base) [mmolla@dg-gpunode05 ~]$ cargo install --git https://github.com/nanoporetech/modkit.git
    Updating git repository `https://github.com/nanoporetech/modkit.git`
  Installing mod_kit v0.2.7 (https://github.com/nanoporetech/modkit.git#3e75aa4d)
    Updating crates.io index
   Compiling serde v1.0.198
   Compiling libz-sys v1.1.16
   Compiling thiserror v1.0.58
   Compiling lzma-sys v0.1.20
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling enum-map v2.7.3
   Compiling openssl-sys v0.9.102
   Compiling nalgebra v0.29.0
   Compiling num v0.4.2
   Compiling peroxide v0.32.1
   Compiling nom v7.1.3
   Compiling indicatif v0.17.8
   Compiling clap v4.5.4
error: failed to run custom build command for `libz-sys v1.1.16`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installUBdG6y/release/build/libz-sys-1cd3e1c84db4683a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
  cargo:rerun-if-changed=build.rs
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/tmp/cargo-installUBdG6y/release/build/libz-sys-60316e55d3f05b32/out/build" && CMAKE_PREFIX_PATH="" "cmake""/gpfs1/home/m/m/mmolla/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libz-sys-1.1.16/src/zlib-ng" "-DBUILD_SHARED_LIBS=OFF" "-DZLIB_COMPAT=ON" "-DZLIB_ENABLE_TESTS=OFF" "-DWITH_GZFILEOP=ON" "-DCMAKE_INSTALL_PREFIX=/tmp/cargo-installUBdG6y/release/build/libz-sys-60316e55d3f05b32/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/bin/cc" "-DCMAKE_BUILD_TYPE=Release"

  --- stderr
  CMake Error: Could not find CMAKE_ROOT !!!
  CMake has most likely not been installed correctly.
  Modules directory not found in

  CMake Error: Error executing cmake::LoadCache(). Aborting.

  thread 'main' panicked at /users/m/m/mmolla/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mod_kit v0.2.7 (https://github.com/nanoporetech/modkit.git#3e75aa4d)`, intermediate artifacts can be found at `/tmp/cargo-installUBdG6y`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
(base) [mmolla@dg-gpunode05 ~]$

**Comment by ArtRand** [comment]
@habibsaky ,

Looks like you need `cmake`, unfortunately this is still a required dependency for some of the older dependencies. Depending on the permissions you have you may be able to install it with a package manager like `apt`

```bash
$ apt-get update && apt-get install -y cmake
```

Or (what I do) is just [download it](https://cmake.org/download/) from the internet and put it in your path. If you're not allowed to do that due to privileges or security, I can tell you that I have `cmake-3.24.2-linux-x86_64` on my linux machine and it builds just fine.

**Comment by habibsaky** [comment]
thank you solve it.

**Comment by ArtRand** [comment]
Great!
