### ISSUE TITLE
modkit dmr pair - no significance values in output

### ISSUE THREAD

**Issue by lilypeck** [nanoporetech/modkit#168]
Hello

Thanks for this great tool

I am running your differential methylation pipeline, following `modkit pileup` to call methylated sites. This is a plant genome so I have methylation in CG, CHG and CHH contexts. 

The `dmr` pipeline seems to be running fine, but I am missing the final columns from the output with p-values which as per the manual should be included when performing single-site analysis and there is an equal number of an and b samples. 

My command is 
```
/u/home/l/ldpeck/project-vlsork/longreads/dist/modkit dmr pair \
  -a ${dmr1}_CHH.bedmethyl.gz \
  --index-a ${dmr1}_CHH.bedmethyl.gz.tbi \
  -b ${dmr2}_CHH.bedmethyl.gz \
  --index-b ${dmr2}_CHH.bedmethyl.gz.tbi \
  -o dmr/te_${dmr1_nams}-${dmr2_nams}.tab \
  -r Qlob.repeats.bed \
  --ref /u/home/l/ldpeck/genome_resources/GCF_001633185.2_ValleyOak3.2_genomic.fna \
  --base C \
  -t 6 \
  -f \
  --log-filepath dmr/dmr_${dmr1_nams}-${dmr2_nams}.log
```

And my output is
```
head -n 20 te_667_D2_T1-667_D2_T3.tab 
NC_044904.1	0	3376	(ACCCTAA)N	-0.30738523369655013	m:17279	122297	m:13476	95665	m:14.13m:14.09
NC_044904.1	3398	3483	(ATTT)N	0	m:0	1	.	0	m:0.00	.
NC_044904.1	3598	3653	RF:5.1395_Unknown	0	.	0	.	0	.	.
NC_044904.1	3861	3979	RF:5.1964_Unknown	0	.	0	.	0	.	.
NC_044904.1	4318	4364	RF:1.540_Unknown	0	.	0	.	0	.	.
NC_044904.1	4456	4484	(TATTT)N	0	.	0	.	0	.	.
NC_044904.1	4502	4530	(AT)N	0	.	0	.	0	.	.
NC_044904.1	4763	4805	RF:1.287_Unknown	0	.	0	.	0	.	.
NC_044904.1	4997	5044	(A)N	0	.	0	.	0	.	.
NC_044904.1	5055	5160	RF:1.301_Unknown	0	.	0	.	0	.	.
NC_044904.1	5073	5181	RF:1.767_Unknown	0	.	0	.	0	.	.
NC_044904.1	5161	5380	RF:6.684_Unknown	0	.	0	.	0	.	.
NC_044904.1	5543	7005	RF:1.42_LTR/Copia	0	.	0	.	0	.	.
NC_044904.1	7601	7625	(C)N	0	.	0	.	0	.	.
NC_044904.1	8550	8607	(TC)N	0	.	0	m:0	1	.	m:0.00
NC_044904.1	8669	8778	(TTTGGA)N	0	.	0	m:0	28	.	m:0.00
NC_044904.1	9024	9070	(TTCTGC)N	0	.	0	m:0	4	.	m:0.00
NC_044904.1	9082	9151	(TTG)N	0	.	0	m:0	14	.	m:0.00
NC_044904.1	12898	12944	(TTTTCT)N	0	.	0	.	0	.	.
NC_044904.1	14705	14862	RF:1.117_Unknown	0	.	0	.	0	.	.
```

Thank you in advance for any help with this

Lily

**Comment by ArtRand** [comment]
Hello @lilypeck, 

Could you double check which version of modkit you have `modkit --version`? (The MAP-based p-value was added in 0.2.5).

As mentioned in the [documentation](https://nanoporetech.github.io/modkit/intro_dmr.html#3-detecting-differential-modification-at-single-base-positions) the MAP-based p-value is only generated when running "single site analysis". To run single-site analysis, omit the `--regions` (`-r`) option.

**Comment by lilypeck** [comment]
Hello

Thank you for your reply. My version is `mod_kit 0.2.4` so I will install the latest and try again - I tried both single site and regions, that explains why neither included the significance values.

Will the p-values be included with `--regions` in the future do you know? Running the single site is very slow (I am working with assemblies ~ 830 Mb) whereas `--regions` finishes in a couple of hours.

Thank you for this great tool!

**Comment by lilypeck** [comment]
ps`mod_kit 0.2.7` is infinitely faster, finishing in 45 mins, than `mod_kit 0.2.4` which was taking over a day to run, so thank you for those improvements too

**Comment by ArtRand** [comment]
Hello @lilypeck,

Hopefully you found that the more recent versions are quite a bit quicker at "single-site analysis". You only get columns 16-19 when you have multiple replicates of paired samples, such as:

```bash
modkit dmr pair \
  -a ${norm_pileup_1}.gz \
  -a ${norm_pileup_2}.gz \
  -b ${tumor_pileup_1}.gz \
  -b ${tumor_pileup_2}.gz \
```

Notice multiple `-a` and `-b`, your command has one replicate per condition (one `-a` and one `-b`).

**Comment by ArtRand** [comment]
@lilypeck feel free to re-open this issue if you have any more questions. If you run into a bug where the program panics when you have multiple "matched" samples, you might try the build [here](https://github.com/nanoporetech/modkit/issues/165), I'll get a patch release with the fix out soon.
