### ISSUE TITLE
Error! unable to open SAM/BAM/CRAM index

### ISSUE THREAD

**Issue by habibsaky** [nanoporetech/modkit#169]
(base) [mmolla@dg-gpunode05 ~]$ modkit pileup /gpfs2/scratch/mmolla/Z/calls.bam output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log

Error! unable to open SAM/BAM/CRAM index for /gpfs2/scratch/mmolla/Z/calls.bam; please create an index
(base) [mmolla@dg-gpunode05 ~

**Comment by ArtRand** [comment]
Could you check that `/gpfs2/scratch/mmolla/Z/calls.bam.bai` exists? If it doesn't 

```bash
$ samtools inded /gpfs2/scratch/mmolla/Z/calls.bam
```
will do it.

**Comment by habibsaky** [comment]
> Could you check that `/gpfs2/scratch/mmolla/Z/calls.bam.bai` exists? If it doesn't
> 
> ```shell
> $ samtools index /gpfs2/scratch/mmolla/Z/calls.bam
> ```
> 
> will do it.

no it is not bam.bai

i run again with samtools but i got error like this...

(base) [mmolla@dg-gpunode05 ~]$ modkit pileup /gpfs2/scratch/mmolla/Z/calls.bam output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log
> Error! unable to open SAM/BAM/CRAM index for /gpfs2/scratch/mmolla/Z/calls.bam; please create an index
(base) [mmolla@dg-gpunode05 ~]$ modkit pileup samtools index /gpfs2/scratch/mmolla/Z/calls.bam output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log
error: unexpected argument '/gpfs2/scratch/mmolla/Z/calls.bam' found

Usage: modkit pileup [OPTIONS] <IN_BAM> <OUT_BED>

For more information, try '--help'.
(base) [mmolla@dg-gpunode05 ~]$

**Comment by ArtRand** [comment]
@habibsaky 

Sorry for not being clear. 

First run:
```bash
$ samtools index /gpfs2/scratch/mmolla/Z/calls.bam
```
this command creates the .bai BAM index file. Then you can run `modkit pileup` like you were before:

```bash
modkit pileup /gpfs2/scratch/mmolla/Z/calls.bam output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log
```

**Comment by habibsaky** [comment]
oh i did both but still now error

(base) [mmolla@dg-gpunode05 ~]$ modkit pileup /gpfs2/scratch/mmolla/Z/ output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log
> Error! unable to open SAM/BAM/CRAM file at /gpfs2/scratch/mmolla/Z/
(base) [mmolla@dg-gpunode05 ~]$ modkit pileup /gpfs2/scratch/mmolla/Z/index.bai output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log
> Error! unable to open SAM/BAM/CRAM file at /gpfs2/scratch/mmolla/Z/index.bai
(base) [mmolla@dg-gpunode05 ~]$ modkit pileup /gpfs2/scratch/mmolla/Z/sorted.bam output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log
> Error! unable to open SAM/BAM/CRAM index for /gpfs2/scratch/mmolla/Z/sorted.bam; please create an index
(base) [mmolla@dg-gpunode05 ~]$ modkit pileup /gpfs2/scratch/mmolla/Z/ output/gpfs2/scratch/mmolla/Z/pileup.bed --log-filepath pileup.log
> Error! unable to open SAM/BAM/CRAM file at /gpfs2/scratch/mmolla/Z/
(base) [mmolla@dg-gpunode05 ~]$

**Comment by ArtRand** [comment]
You need to specify the file, not just the directory. See my command:
```bash
modkit pileup \
  /gpfs2/scratch/mmolla/Z/calls.bam \
  output/gpfs2/scratch/mmolla/Z/pileup.bed \
  --log-filepath pileup.log
```

**Comment by habibsaky** [comment]
(base) [mmolla@dg-gpunode05 Z]$ modkit pileup sorted.bam pileup.bed --log-filepath pileup.log
> calculated chunk size: 6, interval size 100000, processing 600000 positions concurrently
> attempting to sample 10042 reads
> Error! zero reads found in bam index
(base) [mmolla@dg-gpunode05 Z]$

**Comment by ArtRand** [comment]
Sounds like you need to align your reads first. I would use `dorado aligner` for this, see the [documentation](https://github.com/nanoporetech/dorado/?tab=readme-ov-file#alignment) on how to do this.

**Comment by ArtRand** [comment]
Sounds like we took care of this in #171.
