### ISSUE TITLE
DMR: processed 0 sites successfully

### ISSUE THREAD

**Issue by Hannah1746** [nanoporetech/modkit#175]
I am attempting to run modkit dmr pair one some old reads and new reads. 

My old_reads.bed are for a R9 cell and when I finish calling methylation I get an output file like:
Lhe_Chr1        69      70      m       3       +       69      70      255,0,0 3 0.00 0 3 0 0 0 0 0                                                    
Lhe_Chr1        70      71      m       4       -       70      71      255,0,0 4 0.00 0 4 0 1 0 0 0                                                    
Lhe_Chr1        77      78      m       1       -       77      78      255,0,0 1 100.00 1 0 0 0 0 4 0                                                  
Lhe_Chr1        99      100     m       1       -       99      100     255,0,0 1 0.00 0 1 0 0 0 4 0                                                    
Lhe_Chr1        125     126     m       2       +       125     126     255,0,0 2 0.00 0 2 0 0 0 1 1 
My new_reads.bed are from R10 cell and when I finish calling methylation I get an output file like:
Lhe_Chr1        69      70      h       1       +       69      70      255,0,0 1 0.00 0 1 0 0 0 0 0
Lhe_Chr1        69      70      m       1       +       69      70      255,0,0 1 0.00 0 1 0 0 0 0 0
Lhe_Chr1        125     126     h       1       +       125     126     255,0,0 1 0.00 0 1 0 0 0 0 0
Lhe_Chr1        125     126     m       1       +       125     126     255,0,0 1 0.00 0 1 0 0 0 0 0

When I run it through 'modkit dmr pair  -a old_reads.bed.gz -b new_reads.bed.gz -o ${f}DMR_RAW.bed --ref ref.fasta --base C -t 20 -f --log-filepath out.log' I am getting an output of:
> reading reference FASTA at "ref.fasta"                                                                                
> running single-site analysis                                                                                                                          
> using default prior, Beta(α: 0.55, β: 0.55)                                                                                                           
> estimating max coverages from data                                                                                                                    
> sampled 364329 a records and 1920747 b records, calculating max coverages for 95th percentile                                                         
> calculated max coverage for a: 22 and b: 8                                                                                                            
> finished, processed 0 sites successfully, 41178664 failed 

I was hoping I could get an Idea of why nothing is passing. Is it because the old reads do not have h rows in them. Is it normal for older reads to not get h calls?

Thank you for your time!

**Comment by ArtRand** [comment]
Hello @Hannah1746, 

Could you tell me if you see any messages in `out.log` that indicate that a scoring has failed?

**Comment by Hannah1746** [comment]
I'm sorry for wasting your time. A and B have to be the same number of individuals.

**Comment by ArtRand** [comment]
No problem. Glad you figured it out.
