### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by molecule53** [nanoporetech/modkit#180]
Hello,

I run:
git clone https://github.com/nanoporetech/modkit.git
cd modkit

After, I am running 
cargo install --path .
but I am getting the error bellow:

 running cd "/Data1/modkit/target/release/build/openssl-sys-fc6a0e7de0c255d6/out/openssl-build/build/src" && "make" "depend"

  --- stderr
  thread 'main' panicked at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:

  Error building OpenSSL dependencies:
      Command: cd "/Data1/modkit/target/release/build/openssl-sys-fc6a0e7de0c255d6/out/openssl-build/build/src" && "make" "depend"
      Failed to execute: No such file or directory (os error 2)

      
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mod_kit v0.2.8 (/Data1/modkit)`, intermediate artifacts can be found at `/Data1/modkit/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Thank you!

**Comment by ArtRand** [comment]
Hello @molecule53, 

Could you tell me about the operating system and environment you're installing into? It looks like Open SSL is failing to build. From the error, it looks like your system doesn't have `make`, could you check if that's the case? The dependencies of `modkit` require CMAKE as well, so you might want to install that once you have a chance.

**Comment by molecule53** [comment]
Hello and Thank you!

Installing CMAKE helped!

I was able to run modkit.

I have a couple of questions:

  1.
I run /home/ubuntu/.cargo/bin/modkit pileup /Data1/dorado_output.sorted.bam /Data1/dorado_modkit_pileup_CpG.bed --cpg --ref /Data1/genome_reference.fasta --ignore h --combine-strands

     
     In the 4th column of the .bed file I got not only modification code m but also modification      code a. Is it something expected or am I missing something? I am interested in mC.

    2) Is there any way to look at mC in CHH and CHG (H is anybase but G)?

Thank you!

    

________________________________
From: Arthur Rand ***@***.***>
Sent: Monday, May 6, 2024 2:58 PM
To: nanoporetech/modkit ***@***.***>
Cc: McKinlay, Anastasia ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [nanoporetech/modkit] Error during installation (Issue #180)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Hello @molecule53<https://github.com/molecule53>,

Could you tell me about the operating system and environment you're installing into? It looks like Open SSL is failing to build. From the error, it looks like your system doesn't have make, could you check if that's the case? The dependencies of modkit require CMAKE as well, so you might want to install that once you have a chance.

**Comment by ArtRand** [comment]
Hello @molecule53

If you performed basecalling and modification calling with a 6mA and 5mC model (sounds like you did) then you'll get a base modification call at all Cs and As in each read. What can happen is, if a read has a C-to-A alignment mismatch you'll still get a 6mA canonical/modified call at that site (even though it's a reference C). It's usually clear this is the case because the valid coverage will be much lower than the median for the run. If you only care about 5mC, you can filter out the records with `a` in the mod-code column. 

If you want to look at CpG, CHH, and CHG, you can use the `--motif` option, the [documentation](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#narrowing-output-to-specific-motifs) is on github.

**Comment by molecule53** [comment]
Hello,

Thank you!
I did see --motif option. I am not sure if can I look at  CHH or CHG using one line of code (H can be either A, T, or C). Any suggestions?

Best,
Anastasia

________________________________
From: Arthur Rand ***@***.***>
Sent: Friday, May 10, 2024 6:06 PM
To: nanoporetech/modkit ***@***.***>
Cc: McKinlay, Anastasia ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [nanoporetech/modkit] Error during installation (Issue #180)


This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Hello @molecule53<https://github.com/molecule53>

If you performed basecalling and modification calling with a 6mA and 5mC model (sounds like you did) then you'll get a base modification call at all Cs and As in each read. What can happen is, if a read has a C-to-A alignment mismatch you'll still get a 6mA canonical/modified call at that site (even though it's a reference C). It's usually clear this is the case because the valid coverage will be much lower than the median for the run. If you only care about 5mC, you can filter out the records with a in the mod-code column.

If you want to look at CpG, CHH, and CHG, you can use the --motif option, the documentation<https://nanoporetech.github.io/modkit/intro_bedmethyl.html#narrowing-output-to-specific-motifs> is on github.

**Comment by ArtRand** [comment]
Hello @molecule53,

Sorry for the slow reply. You can use `--motif CHH 0 --motif CHG 0` the parser in `modkit` understands [iupac](https://www.bioinformatics.org/sms/iupac.html) codes.

**Comment by molecule53** [comment]
Thank you!



________________________________
From: Arthur Rand ***@***.***>
Sent: Monday, May 20, 2024 11:22 AM
To: nanoporetech/modkit ***@***.***>
Cc: McKinlay, Anastasia ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [nanoporetech/modkit] Error during installation (Issue #180)


This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Hello @molecule53<https://github.com/molecule53>,

Sorry for the slow reply. You can use --motif CHH 0 --motif CHG 0 the parser in modkit understands iupac<https://www.bioinformatics.org/sms/iupac.html> codes.

**Comment by ArtRand** [comment]
Great, let me know if you have any more questions.
