### ISSUE TITLE
modkit pileup incorrect column name?

### ISSUE THREAD

**Issue by josiegleeson** [nanoporetech/modkit#182]
Hi, I've been using modkit pileup on BAMs generated with dorado and the m6A model for RNA004. 

I've noticed that in the bedMethyl output, column 11 seems to be a percentage of modified reads, not a fraction as stated in the documentation. Just wanted to point this out so others don't assume its a fraction or proportion.

**Comment by ArtRand** [comment]
Hello @josiegleeson, thanks for noticing this. I've updated the [documentation](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#bedmethyl-column-descriptions) to reflect that the value is a percentage.
