### ISSUE TITLE
Does modkit --traditional take into account reverse CpG spots?

### ISSUE THREAD

**Issue by mvolar** [nanoporetech/modkit#184]
Hello,

I presume that when finding probabilities for a CpG the reads mapped to the reverse strand are taken into account, but does modkit ignore the reference positions which are GpC in the forward strand (reference, so CpG in reverse)?

I ask because dinucleotide composition of my genome is:

```
sum of #CGs 21922699 
sum of #GCs 107851156
```
And my resulting tables have about 21.8-21.9 million rows corresponding obviously to the forward strand CpG number whilst ignoring the reverse strand completely.

**Comment by ArtRand** [comment]
Hello @mvolar,

Could you tell me which command you're referring to (just so I know how best to assist)?

If you use the `--cpg` shorthand or `--motif CG 0` the motif finding method will find `5' CG  3'` (+)-strand sequences as well as (-)-strand sequences (which are the same):

```text
5' NNCGNN 3'
3' NNGCNN 5'
```

If you want to specifically find GC motifs you can use `--motif GC 1`. 

Hope this helps.

**Comment by mvolar** [comment]
I was reffering to `--traditional` preset. The problem was my genome was reversed not reverse complemented so the numbers didn't match when comparing dinucloetides with the number of table rows.
