### ISSUE TITLE
error: unrecognized subcommand 'find-motifs' (Find highly modified motif sequences)

### ISSUE THREAD

**Issue by saky7009** [nanoporetech/modkit#187]
Why does it show like that?  unrecognized subcommand 'find-motifs'

(base) [mmolla@dg-gpunode01 ~]$ modkit find-motifs -i /gpfs2/scratch/mmolla/Longread_1/LB1/LB1_A/hemi_duplex_pileup.bed.gz.tbi -r /gpfs2/scratch/mmolla/Z/HL4.fsa -o /gpfs2/scratch/mmolla/Longread_1/LB1/result/./motifs.tsv  --threads 32  --log ./modkit_find_motifs_log.txt

**Comment by ArtRand** [comment]
Hello @saky7009, 

Could you tell me the output of `modkit --version`? You will need version 0.3.0 to use the `find-motifs` function.

**Comment by ArtRand** [comment]
@saky7009 any luck?
