### ISSUE TITLE
Error! should be at least 1 contig

### ISSUE THREAD

**Issue by james-e-barrett** [nanoporetech/modkit#189]
Hi,

I get the following error running

```
./modkit pileup \
~/Data/nanopore/mysample.pass.sorted.bam \
~/Data/nanopore/mysample.pileup.bed \
--ref ~/Data/hg38.fa \
--cpg
> calculated chunk size: 6, interval size 100000, processing 600000 positions concurrently
> filtering to only CpG motifs
> attempting to sample 10042 reads
> Using filter threshold 0.7207031 for C.
> Error! should be at least 1 contig
```

It runs fine without the --ref and --cpg arguments.

Any help appreciated thanks.

**Comment by ArtRand** [comment]
Hello @james-e-barrett, 

Could you check that the reference you're using with `modkit` is the same as the one you used in alignments (i.e. the contigs should have the same names)?

**Comment by james-e-barrett** [comment]
Hi @ArtRand, 

The reference used was indeed different (somebody else did the alignment). In my .bam file the chromosomes are labelled "1", "2", etc., but in the reference genome I used from UCSC (hg38.fa) they are labelled "chr1", "chr2", etc. 

Changing the chromosome names in my .bam file fixed this. Using the same reference genome throughout would presumably avoid the problem also.

Thanks for your help.

**Comment by ArtRand** [comment]
Great, feel free to re-open this issue if you have any additional questions or encounter another related problem.

**Comment by dgordon562** [comment]
I got the same error.  So I checked and the contig names in the reference match those in the centromere file and match those in the reference.  I tried an experiment of taking the first 100 or so lines in the bam file and making a fake centromere file that overlaps those reads.  Still got the error "Error!  should be at least 1 contig".  Any thoughts?

**Comment by dgordon562** [comment]
OK.  I was able to get it to work, but I don't understand why.  My reference was PNG16_both_haps.fa.bgzip  If I instead have the reference be the (uncompressed) PNG16_both_haps.fa, it works.   This is NOT because modkit can't read compressed references because I've used compressed references before.  It might be due to the .bgzip extension--I don't know.
