### ISSUE TITLE
Output tsv has some minor code duplication issues in find-motif code part.

### ISSUE THREAD

**Issue by bgdga** [nanoporetech/modkit#195]
Output tsv has some minor code duplication issues in find-motif code part. It's printing same details 2 times, giving out an error with output after printing just 1st row. 
Error message geeting at end of run everytime: "> Error! CSV error: found record with 9 fields, but the previous record has 7 fields"
Please fix it soon. Attaching a screenshot  of output tsv for example. 

![Screenshot from 2024-05-31 15-38-32](https://github.com/nanoporetech/modkit/assets/131662469/489183ce-0cca-4437-a29b-a15210fe479a)

**Comment by ArtRand** [comment]
Hello @bgdga,

Could you show me the command you're using so I can debug the problem?

**Comment by bgdga** [comment]
Using as: $modkit_path find-motifs -o $master_path/${sample}_a.tsv  --mod-code a --min-sites 10 --min-coverage 20 --in-bedmethyl $master_path/${sample}_AC.bed --ref $fasta_path/$sample.contigs.fasta

**Comment by ArtRand** [comment]
Hello @bgdga, 

There is a bug in the current release. Please find a build attached with the fix. The [branch](https://github.com/nanoporetech/modkit/tree/ar/gh-195) includes the code change. I will be sure to release a patch this week including this fix.

Just a heads up that setting `--min-sites 10`  may increase the search time substantially, if you find this to be the case on other samples try using `--skip-search`. 
[modkit_dev1c19442_centos7_x86_64.tar.gz](https://github.com/user-attachments/files/15540894/modkit_dev1c19442_centos7_x86_64.tar.gz)

**Comment by bgdga** [comment]
It's working thankyou.
