### ISSUE TITLE
How does modkit handle secondary/supplementary alignments?

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/modkit#20]
I'm feeding in MinKNOW/guppy's output (merged with samtools) straight into modkit v0.1.6. How does modkit handle the secondary/supplementary alignments? Here are some basic stats for one file, which indicates this may be a significant number:

```
$ /mnt/ix1/Resources/tools/samtools/v1.15.1/samtools-1.15.1/samtools flagstat -@ 40 ./cases/P10227_30544.D01.merged.sorted.bam
69326287 + 0 in total (QC-passed reads + QC-failed reads)
53240227 + 0 primary
10567988 + 0 secondary
5518072 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
64771719 + 0 mapped (93.43% : N/A)
48685659 + 0 primary mapped (91.45% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

For megalodon, does it only take in the primary alignments when looking at mod_mappings.bam? Trying to figure out whether this needs to be taken into account or not.

Edit: Seems like mod_mappings.bam from megalodon is looking only at primary alignments:

```
$ /mnt/ix1/Resources/tools/samtools/v1.15.1/samtools-1.15.1/samtools flagstat -@ 40 mod_mappings.bam 
941703 + 0 in total (QC-passed reads + QC-failed reads)
941703 + 0 primary
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
941703 + 0 mapped (100.00% : N/A)
941703 + 0 primary mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

**Comment by ArtRand** [comment]
Hello @billytcl,

`modkit` only uses primary alignments for all of its operations. I'll make sure this is clear in the docs for the next release. The reason is partially due to the implementation of the MM tag. Do you have a specific use case for the non-primary alignments?

**Comment by billytcl** [comment]
Nope! All good. Just wanted to make sure.

**Comment by ArtRand** [comment]
I've added some clarifying [documentation](https://nanoporetech.github.io/modkit/intro_bedmethyl.html) around how primary alignments are used, please re-open this issue if you have further questions.
