### ISSUE TITLE
`pileup` output both bedMethyl and bedGraph

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#204]
Hi Arthur,

I was wondering if I pass `--bedgraph` to `modkit pileup` can I get both the bedMethyl and the bedGraph out or must I redo the computation?

**Comment by ArtRand** [comment]
@Ge0rges

I advise people to make a bedGraph _from_ the bedMethyl, it's relatively easy to do with `awk` or similar - don't re-do the computation.

**Comment by Ge0rges** [comment]
Thanks for that.
