### ISSUE TITLE
Getting error when running modkit dmr pair 

### ISSUE THREAD

**Issue by agoel13** [nanoporetech/modkit#208]
Hi,
 
I am trying to run modkit (v0.3.0) dmr pair using replicates and getting following error
 
**Error msg : 
running with replicates, but not matched samples
thread 'main' panicked at src/hmm.rs:330:9:
e_s is not finite -inf
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**
 
 
 For your reference here is my script:
 
_modkit dmr pair \
-a Norm1.bed.gz \
-a Norm2.bed.gz \
-b Tum1.bed.gz \
-b Tum2.bed.gz \
-b Tum3.bed.gz \
-b Tum4.bed.gz \
-o dmr_replicates_pair_segment.bed \
--header \
--segment dmr_segements.bed \
--ref hg38.fa \
--base C \
--threads 16 \
--log-filepath dmr_pair_segment.log_
 
While when I run the same script with only one pair of samples and no replicates, it completes without any errors.

PS: Without turning on the segment argument, the above script runs fine.

**Comment by ArtRand** [comment]
Hello @agoel13, 

Sorry about that. Could you try the attached build and tell me if you continue to encounter the crash? 

[modkit_dev88c2107_centos7_x86_64.tar.gz](https://github.com/user-attachments/files/15874620/modkit_dev88c2107_centos7_x86_64.tar.gz)

**Comment by agoel13** [comment]
Many thanks. Completed successfully without any error msgs. 
When would this version be released? I would then update my pipeline with the released version.

**Comment by ArtRand** [comment]
@agoel13 Great. Yes this fix and a few others will be released this week. Thanks for testing it!

**Comment by agoel13** [comment]
Thanks. Looking forward to it.

**Comment by ArtRand** [comment]
This fix has been released in [v0.3.1](https://github.com/nanoporetech/modkit/releases/tag/v0.3.1).
