### ISSUE TITLE
Empty bed file

### ISSUE THREAD

**Issue by Violeta-de-Anca** [nanoporetech/modkit#21]
Hello!
I have been trying to run modkit pileup but I get no output.
Command I ran:
```
./dist/modkit pileup --log-filepath pileup.log ../mod.bases.basecalling/5mC.CpG.mod.bases.mitochondria.bam pileup.5mC.CpG.mitochondria.bed
```
Log file output:

>[src/commands.rs::133][2023-05-25 03:33:23][INFO] sampling 10042 reads from BAM
[src/reads_sampler.rs::228][2023-05-25 03:33:23][DEBUG] sampled 0 mapped records, sampling unmapped records
[src/reads_sampler.rs::249][2023-05-25 03:33:23][DEBUG] sampled 10042 unmapped records
[src/reads_sampler.rs::256][2023-05-25 03:33:23][DEBUG] sampled 10042 records
[src/commands.rs::675][2023-05-25 03:33:23][WARN] Threshold of 0.6484375 for base C is low. Consider increasing the filter-percentile or specifying a higher threshold.
[src/commands.rs::843][2023-05-25 03:33:23][INFO] Done, processed 0 rows. Processed ~0 reads and skipped zero reads.

And I have checked and I have the correct tags in the BAM file:

>c5c0d295-80d5-4469-8da8-3a1fd92fd843    4       *       0       0       *       *       0       247     GGTAATACTTCGTTCAGTTACGTATTGCTTAGTTTTGCTGGGGGATAAGAGGGCTGTGGGCAAGAGTATGATTGTTGGTAGGATGATCTTTAGCATTGTAGAAAGTTTAGGTTGTGTAGGTGGTCAGAGCCATGTGTTCGTGCAGAAGCTACTAGTATGGCTTAGGCCTGTGCCAGCTTCGCATGTGGATGCAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGCGTCGTGTAAGGAAAAGAGGGGAA '((('&%$''98:;<><<<9887::;+'''&%%')7>?>9222014A=BA=>>;<;<<<=?>;3('-.257:96666200113=?BCBCD?;:8:?=>>>@??>;97760/5587990/)((*5;))*&''36>?DCC@>777266A?<==@A;10-,+,..))+5;;=>?B??:333465778=;89;<=;87(666=;=?DDDA?==999:?<<37>54CA?<;::;<>821411,+-)(*-*+* **MM**:Z:C+h?,1,1,9,9,2,0,0,0,0;**C+m**?,1,1,9,9,2,0,0,0,0;     **ML**:B:C,1,1,0,13,0,1,0,1,0,4,10,18,9,2,1,0,0,1   qs:i:13 mx:i:4  ch:i:288        rn:i:202        st:Z:2023-02-20T14:35:34Z       f5:Z:FAW45780_pass_7fb25cdd_59cf256b_0.fast5    ns:i:4598       ts:i:330        sm:f:69.3264    sd:f:10.2165    sv:Z:med_mad    RG:Z:59cf256be47a641beb65be04367cb11db5b86801_2021-05-17_dna_r9.4.1_minion_384_d37a2ab9

When I ran modkit summary it works but I get a warning:
```
./dist/modkit summary --no-sampling --no-filtering --log-filepath ./summary.log /home/viole/nanopore/mod.bases.basecalling/5mC.CpG.mod.bases.mitochondria.bam >  summary.modifications.stats
```

> double added base mod calls for base C and read eae1c9de-30c3-4b23-bb98-b98bcece579b,potentially a logic error!

This warning is shown multiple times (> 100), but I get the stats for each modification:
bases             C
 total_reads_used  120725
 count_reads_C     120725
 base  code  pass_count  pass_frac    all_count  all_frac
 C     m     1145242     0.0930746    1145242    0.0930746
 C     h     722809      0.058743183  722809     0.058743183
 C     -     10436509    0.8481822    10436509   0.8481822

I don't truly know what I am doing wrong, I should have a bed file with at least those 0.1% of modified bases?
I have also tried to run pileup with the --force-allow-implicit to at least get also the canonical C but I get the same log output (and an empty bed file):

>[src/commands.rs::133][2023-05-25 03:34:02][INFO] sampling 10042 reads from BAM
[src/reads_sampler.rs::228][2023-05-25 03:34:02][DEBUG] sampled 0 mapped records, sampling unmapped records
[src/reads_sampler.rs::249][2023-05-25 03:34:03][DEBUG] sampled 10042 unmapped records
[src/reads_sampler.rs::256][2023-05-25 03:34:03][DEBUG] sampled 10042 records
[src/commands.rs::675][2023-05-25 03:34:03][WARN] Threshold of 0.6484375 for base C is low. Consider increasing the filter-percentile or specifying a higher threshold.
[src/commands.rs::843][2023-05-25 03:34:03][INFO] Done, processed 0 rows. Processed ~0 reads and skipped zero reads.

Could you pinpoint what I am doing wrong?
Thank you so much!
Violeta de Anca

**Comment by ArtRand** [comment]
Hello @Violeta-de-Anca, 

From what you have here, it looks like none of the reads in your modBAM are mapped. One clue is here in the log file:
```
[src/reads_sampler.rs::228][2023-05-25 03:33:23][DEBUG] sampled 0 mapped records, sampling unmapped records
[src/reads_sampler.rs::249][2023-05-25 03:33:23][DEBUG] sampled 10042 unmapped records
```
When estimating the filter threshold `modkit` will first sample from mapped reads then unmapped ones, looks like it is only finding unmapped ones. (The example read you have also appears to be unmapped). The `pileup` operation requires that the reads are mapped to a reference in order to work. As you discovered, `summary` does not require mapping so you get the statistics from the base modification tags. 

As far as the error, the log level should be changed to be less alarming. If you have duplicate reads in your modBAM, you'll see this error message. You can check out the conversation on [#18](https://github.com/nanoporetech/modkit/issues/18). Long story short, the next version will still log when it encounters duplicated reads, but it won't count the second one towards the total when sampling. Hope this helps!

**Comment by Violeta-de-Anca** [comment]
Hi!
First, thank you so much for your fast response! 
Yes indeed, this bam file is not mapped as I only performed the modified basecall with guppy, so you would suggest to do the basecalling again with guppy but also with the mapping flag at the same time? 
I thought that even with unmapped files modkit would still work because of the no reference required in the readme file, sorry for the confusion...

Thank you so much!
Violeta de Anca

**Comment by ArtRand** [comment]
Ah ha, I'll update the docs to make this clear. Basically, `pileup` doesn't require a reference _sequence_ in order to process the reads, but it still needs to know which genome coordinates the reads are aligned to. 

It's up to you if you want to re-do basecalling or simply map the reads you have. If it were me, I'd extract the reads to fastq with `samtools fastq -T "*"` you need the `-T` in order to capture the flags, then map them, then perform pileup.

**Comment by Violeta-de-Anca** [comment]
Hej, I redid the basecalling with guppy with the aligning, it now works!
I am closing this issue, thank you so much!!
Violeta de Anca

**Comment by cherlynty** [comment]
Hi,

thanks for answering the above questions. I am having similar issues with an empty bedfile.

I have performed Adaptive Sampling on a GridIon and used guppy for basecalling and alignment.

`guppy_basecaller \
-i ${input_fast5s} -s ${output_folder} \
-c res_dna_r941_min_modbases_5mC_5hmC_v001.cfg \
--align_ref ${reference_fasta} \
--compress_fastq --bam_out --recursive` 

and have checked that they are mapped from bamfiles and samtools idxstats. However, the bed files were empty, and I received an error

`[src/pileup/subcommand.rs::632][2023-07-12 22:30:19][INFO] Done, processed 0 rows. Processed ~0 reads and skipped ~3901 reads.`
`[src/read_cache.rs::372][2023-07-12 22:30:19][DEBUG] read bbe24401-4164-4742-a27a-bb2e121ca5a9, Skipped: record bbe24401-4164-4742-a27a-bb2e121ca5a9 has un-allowed mode (ImplicitProbModified), use '--force-allow-implicit' or 'modkit update-tags --mode ambiguous'`

bam eg:
> 3e2975b6-36df-4d6e-95fa-679aa0ea5111	16	chr1	2371141	60	86M9I29M1D54M2D42M1D13M3I98M1I25M2D22M3D18M1D10M1I30M8D17M25S	*	0	483	GGAGCTTGCAGTGAGCCAAGATCGTGCCACCGCACTCCAGCCTGGGTGACACAGCGAGACTCTGTCTCCAAACAACAACAACAACCACAACCACAACAACAACAACAACACCATGAAGAAAGATTCCTGGGTTTCAGTGATCCTCGCACCTCAGCCTCCCGAAGTGCTGGGATTTTAGGTGAGCCACTGTGCCTGACTGATAGTCTAATTTTAAAAAAATAAAACAATATTTGGGTAATAGACATTTCTCCAAAGAAGATAAACAAACAGCCAATCAACACAGCGAGAGCCACTCATCGTCATCACTCGTTAGGGAAATGCGAATCAAAATCACTGAGGAACTATCACTTCACACCCACAGCAGCTATTACAAAAAGACACACCAAGTGTTGGGAAGACGAGAGAAATCTGGAACCTTCATGCATTACTGGTGGGACTGCACAGCAATTTTGGAAAAAGCAATAATGTAACTGAAACGAAGTG	&,7,'(/.*.),)*,/$.)5&(%*%'))&,(*/+(%*2,+/-$,;),-*5/4+(,7=44*6891.962-9>;'01&&**/4(59.9(25808(,0,+3%,'1)4')*6'&.)0).-;<,<66'313<6):4&-&$((.,3+5*%(()&7:-=1(47*5:/5>;=:7++6B:'-71*%%&(,6:+<)06,*)+?5.+*5+<96-*<-,21;3,)9;;:0&*.11)#.&)/0.)%$##1&$)(6178;*0-<+/;61,=,40-84)==0-91(2.+.+18(5+:*.65,,*2=+'))%'*5;/-),'+*+%&%%)42)>:96*/4'8-2:>.:51&%$&/(1%:9*9/6'*%'-*2+.(++0'8,:08=.>&,1=@?>6''6)0%*.'(1):/2;7'7)1+*&,52>@.<=>)0)0792=;';)17>,>7:),*&*.%%%%#%$&"%*7':7)+-)9<;62'((''%%'%1$28**8%%#&$##$	AS:i:708	MD:Z:17G24C61A10^C7C1C0T43^GT34T7^G0G0G0T113G19^GG22^ATT18^C38T1^AAATGCTG17	NM:i:44	cm:i:32	de:f:0.0505	ms:i:735	nn:i:0	s1:i:228	s2:i:0	tp:A:P	MM:Z:C+h,2,17,12,4,0,2,22,1,10,6,0,0,7;C+m,2,17,12,4,0,2,22,1,10,6,0,0,7;	ML:B:C,0,0,0,0,0,0,0,0,0,0,0,0,0,254,254,255,254,255,255,255,255,255,255,110,254,248	qs:i:9	mx:i:3	ch:i:49	rn:i:118	st:Z:2023-07-06T12:28:29Z	f5:Z:FAV71569_pass_1c3972e3_f5114067_0.fast5	ns:i:5661	ts:i:45	sm:f:78.563	sd:f:10.0631	sv:Z:med_mad	RG:Z:f511406703c9d9eafbc59f28229b17deccce7224_unknown

I have then ran the pile up with `--force-allow-implicit` and got an output bedfile. could you explain the cause for the ImplicitProbModified error?

do you also suggest setting `--sampling-frac 1.0` for adaptive sampling, and/or `--filter-threshold`?
