### ISSUE TITLE
Contig names source

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#213]
Hi Art,

I was wondering where does modkit get the contig name for the bedmethyl outputs of pileup? I'm encountering an odd issue where one of the contigs output doesn't exist in the reference file under the same name. But there might be more at play here than a bug in modkit.

**Comment by ArtRand** [comment]
Hello @Ge0rges, 

The contig names come from the header in the modBAM (@SQ lines). Whatever reference you use to align the reads needs to be carried through downstream steps.

**Comment by Ge0rges** [comment]
@ArtRand does it make sense that `modkit dmr multi`, `modkit dmr pair` or `modkit find-motifs` complete successfully if there is no overlap between contig names in the `.fna` and the and the bedmethyl?
