### ISSUE TITLE
About the output of modkit

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/modkit#22]
Hi, thank you so much for sharing this tool.

It seems that the output bedMethyl file will be the summary at the site level, which means each line corresponds to each site summarized from the reads covering this site. I just would like to know is there any way to create the output where each read for each line.

Because I want to know the status of each CG on each read. Although there is the status of each CG on each read in the modbam file, but there is not the coordinate of each CG, and MM/ML tag only provides the relative location to the sequence, not the position on the reference.

Thank you so much!

**Comment by Flower9618** [comment]
Hi, @ArtRand 
Thank you so much for your reply.

By using `modkit extract` function, can I get the coordinate of each CG on the read?

**Comment by ArtRand** [comment]
That's correct. If you are using one of the CG-context models, base modification calls will only be made at CpG dinucleotides in the read sequence. All rows with canonical base `C` will be CGs in the read sequence. Keep in mind that these may not always correspond to CpGs in the reference. If you are using one of the newer "all-context" models then you'll need to filter the table on the `query_kmers` that have CGs (see the [column descriptions](https://nanoporetech.github.io/modkit/intro_extract.html#description-of-output-table)). 

If you want to just use the CGs in the _reference_ sequence, with an aligned modBAM you can use the `--include-only <CG_motifs.bed>` option to include only Cs in the query that align to CGs in the reference.

**Comment by Flower9618** [comment]
Thank you so much!
