### ISSUE TITLE
modkit extract: OUT_PATH versus READ-CALL-PATH tables

### ISSUE THREAD

**Issue by BenoitM-I2BC** [nanoporetech/modkit#230]
Hi, 
I'm a new use or modkit and thanks for putting all these tools together. I spend some time reading the documentation and trying `modkit extract` on a small test dataset, and I'm still somewhat confused.

What is the **essential difference between the MainOutput table** (described [here](https://nanoporetech.github.io/modkit/intro_extract.html#description-of-output-table)) **and the `read-calls-path` table** (described [here](https://nanoporetech.github.io/modkit/intro_extract.html#tabulating-base-modification-calls-for-each-read-position))? In which cases should we rely on one versus the other?

At first sight, they look very similar (correct me if I'm wrong):

- The first 10 columns seems to be the same
- `mod_qual` (MainOutput) => probability of base being modified<BR>`call_prob` (read-calls) => probability  of the base (modified or not) called in the following `call_code` column
- The `base_qual` `ref_kmer` `query_kmer` `canonical_base` `modified_primary_base` `inferred` and `flag` columns of the two tables contains the same information.
- There are two additional columns in the `read-calls-path` table, notably the `fail` column which indicates if the base, modified or not, passes the filtering threshold.

Are the `--filter-threshold` and `--mod-thresholds` of `modkit extract` suppose to impact the MainOutput and/or the read-calls tables?

Thanks so much for your help!

**Comment by ArtRand** [comment]
Hello @BenoitM-I2BC,

> Are the --filter-threshold and --mod-thresholds of modkit extract suppose to impact the MainOutput and/or the read-calls tables?

These two options **only the read-calls table**. In the next release I'll make it so these options require `--read-calls` option, right now they're silently ignored.

You can think of the `MainOutput` table as a straight translation of the modified base information in the BAM into a tabular form. There is no filtering or processing of the data so this table is useful for debugging and exploratory data analysis (usually for expert users). The `read-calls` table, on the other hand, is meant to enable inspection of the base modification calls as they would be processed in commands such as `pileup` where a "call" is made on every potentially modified base using the [thresholding algorithm](https://nanoporetech.github.io/modkit/filtering.html) designed to maximize accuracy.

One additional note, both commands potentially create large tables, so I generally recommend only using `modkit extract` on regions or subsets of reads of particular interest. If you want to look at information over the whole genome the output from `pileup` is a better choice.

**Comment by ArtRand** [comment]
Hello @BenoitM-I2BC, 

Yes I'll update the documentation. 

One thing you may try is streaming the output like this:

```bash
$ modkit extract ${bam} stdout --region ${region_of_interest} | processing_script.py
```
You can rely on the rows from each read being in a contiguous block so you can process each read at a time.

**Comment by BenoitM-I2BC** [comment]
Hi, 
piping `modkit extract` is indeed what the strategy I'm using now. Thanks for the tip!

**Comment by ArtRand** [comment]
@BenoitM-I2BC feel free to re-open this issue if you have any additional questions.

**Comment by ShakibaMashini** [comment]
I have (-1) in the ref_position column and (.) in the chrome column, but I don't know how to utilize them. Do they contain any critical information?
