### ISSUE TITLE
Request: consider adding threading to output BAM compression

### ISSUE THREAD

**Issue by mrvollger** [nanoporetech/modkit#233]
Hello,

I have found in my code using `rust_htslib` that adding threads to output bam writers is a pretty big performance boost. Often linear up to about 16 threads on my HPC. 

You might consider setting this with:
```rust
out_bam.set_threads(threads)?;
```
After lines like:
https://github.com/nanoporetech/modkit/blob/827a4ecf86f7b27fe57c072c8b5a66d455aceb67/src/commands.rs#L219-L220

If I misunderstood the code or missed where you already set this up, I apologize. 

Cheers,
Mitchell

**Comment by ArtRand** [comment]
@mrvollger Thanks for the suggestion, I'll be sure to add "out-threads" to the BAM-to-BAM commands in the next release.

**Comment by ArtRand** [comment]
Added in [v0.3.2](https://github.com/nanoporetech/modkit/releases/tag/v0.3.2).
