### ISSUE TITLE
Zero reads found in index file

### ISSUE THREAD

**Issue by esh97** [nanoporetech/modkit#239]
Hello,

I am trying to extract methylation data from a modbam file basecalled with Dorado using the RNA004 kit. I have sorted and indexed the file with samtools, but when I run modkit pileup, it outputs the error that zero reads have been found in the index file. I have tried updating the tags with modkit, but it simply skips over all the reads. Is this because I am using RNA data and not DNA?

Thanks

**Comment by ArtRand** [comment]
Hello @esh97, 

DNA and RNA both work. Could you make sure that there are mapped reads in your BAM? 

```bash
$ samtools view -F 2308 ${bam} | wc -l
```

**Comment by ArtRand** [comment]
@esh97 great, happy to answer any additional questions.
