### ISSUE TITLE
offset in motif-bed

### ISSUE THREAD

**Issue by Violeta-de-Anca** [nanoporetech/modkit#24]
Hej!
I am using the version 0.1.7 and in motif-bed now you need to specify an offset along with the motif you what to have. I tried to search in the advanced documentation and in the modkit motif-bed --help but I don't find anything about this offset. what it is? There is only one example with a 0, but I don't understand why is a 0.

Thank you so much,
Violeta de Anca

**Comment by ArtRand** [comment]
Hey @Violeta-de-Anca,
The offset is the 0-based position of the modified base in the motif. For example, if your motif is `GATC` and you're looking for 6mA, to genereate the BED file the command would be 

```
modkit motif-bed <fasta_file> GATC 1
#                                     1 means ^ this position
```

Hope this clears it up. I can add another example to the documentation as well.

**Comment by Violeta-de-Anca** [comment]
Hej Arthur,

I understand now, thank you so much!!

Violeta de Anca
