### ISSUE TITLE
DMR specify strand for regions?

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#240]
Hi Art,

I was wondering if it would be possible to specify the strand when defining regions for DMR.

My issue is that I am trying to connect gene annotation back to DMR regions, and the gene caller (prodigal in this case) gives two gene calls for overlapping position as it recognizes different directions. 

Let me know if this makes any sense given the nature of nanopore data. I guess strand is not necessarily known when doing simplex sequencing so perhaps this is more complicated than I think. Somehow however, you have this information output in pileup.

**Comment by ArtRand** [comment]
Hello @Ge0rges, 

I think stranded region-based DMR makes sense. It should be pretty easy to implement, give me a day and I can get you a test build.

**Comment by ArtRand** [comment]
Hello @Ge0rges 

Give this build a try. The command line is the same, only now if the regions file is a BED with a strand column such as:

```text
chr20   9838623 9839213 CpG127  0   -
```

it will only use counts on the specified strand ((-)-strand in this case). The `score` [column](https://en.wikipedia.org/wiki/BED_(file_format)) is ignored.
[modkit_u16_devc85ce27_x86_64.tar.gz](https://github.com/user-attachments/files/16461862/modkit_u16_devc85ce27_x86_64.tar.gz)

**Comment by Ge0rges** [comment]
Hi @ArtRand should the input be a 6 column TSV then? i.e. the software looks for the strand in the 6th column and ignore columns 4/5.

**Comment by ArtRand** [comment]
@Ge0rges It should be `+, -` or `.`, corresponding to positive, negative, or both strands. Does that work?

**Comment by Ge0rges** [comment]
Yep that works!
