### ISSUE TITLE
strand bias filtration

### ISSUE THREAD

**Issue by weishwu** [nanoporetech/modkit#247]
I used modkit to generate per-CpG methylation percentage data:
```
modkit pileup -t 20 --cpg --ref genome.fa sample_A.bam - | awk '{if (($4 == "m") {
print $0}}' > sample_A.modkit_pileup.strand_split.bed
```

I set up a filter to select only the CpGs where there are data from both strands, and the difference of meth-percent between the strands is lower than 20. It turned out that 63% of the CpGs have data from both strands, and out of these 78% have the strand-difference below 20. Overall, half of the CpGs were filtered out by this filtration.

Is this ratio normal, and is it reasonable to use only the filtered CpGs for my downstream analysis?

Thanks.

**Comment by ArtRand** [comment]
Hello @weishwu, 

Could you tell me roughly what coverage your data is? Only 63% of your CpGs having modification calls on the (+)-strand C and (-)-strand C seems low. Could you show me the code you use to perform this aggregation? If the (valid) coverage is low, I can see how many positions may have a difference in %-methylation $\gt 20%$. Consider for example, if you have coverage of 2, the (+)-strand could have 100% 5mC, and the (-)-strand could have 50% 5mC - a difference of 50% but I think you'd agree the true difference in 5mC rates is probably not 50%. I know this seems obvious, just checking :).

**Comment by weishwu** [comment]
Hi Arthur,

The median coverage on the CpGs with data from only one strand is 6, while the coverage is 59 on the CpGs supported by both strands.

The data is from an AS run. When I looked at only the CpGs within the ROIs, only 13% CpGs are left, but 99% of them have data from both strands, out of which 87% have bias lower than 20.

Previously I only filtered the BAM by requiring the reads to intersect with the ROIs. Since the reads are pretty long, a lot of off-target CpGs were included. I think it makes more sense to use only the on-target CpGs for my downstream analysis.

Thanks,
Weisheng

________________________________
