### ISSUE TITLE
reagrding modkit output

### ISSUE THREAD

**Issue by dasn588** [nanoporetech/modkit#253]
Hi,
I have few queries regarding Modkit output file.
1) what does the values (h and m) in fourth column of the bedmethyl file represent? How to interpret this?
2) What all base modification types are included under "Nother_mod" column when we call 5mC_5hmC and 6mA methylation type?

**Comment by ArtRand** [comment]
Hello @dasn588,

> what does the values (h and m) in fourth column of the bedmethyl file represent? How to interpret this?

There is a description of the table schema in the [documentation](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#bedmethyl-column-descriptions). This column describes the base modification code. The specification of base modification codes can be found [here](https://samtools.github.io/hts-specs/SAMtags.pdf) section 1.7. 

> What all base modification types are included under "Nother_mod" column when we call 5mC_5hmC and 6mA methylation type?

This is described in the [documentation](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#definitions) as well.

* N<sub>other mod</sub> - Number of calls passing filters that were classified as modified, but where the modification is different from the listed base (and the corresponding canonical base is equal). For example, for a given cytosine there may be 3 reads with
`h` calls, 1 with a canonical call, and 2 with `m` calls. In the bedMethyl row for `h` N<sub>other_mod</sub> would be 2. In the
`m` row N<sub>other_mod</sub> would be 3.
