### ISSUE TITLE
Issue with interpreting pileup output

### ISSUE THREAD

**Issue by sumudu-rangika** [nanoporetech/modkit#254]
Hi Arthur,

I have attached a part of a pileup output someone else has generated. I have few things to clarify and appreciate your input. 

1) The strand info is not combined here. Is there a way to combine the methylation calls from + and - strands per each position without rerunning pileup with --combine-strands parameter? 
2) The 5th column Score is said to be equal to Nvalid_cov. But column 10 which is defined as the Nvalid_cov is different. 
3) The documentation says colour should be 255,0,0. Here it is 0,0,0. Can I still consider this result correct? Is there a parameter to assign colour when running pileup? 
4) Is it enough to remove the rows with score 0 or have low Nvalid_cov? Are there any other parameters to filter the output before downstream analysis? 
5) I want the 5mC methylation information for selected regions in the genome, For example promoters of genes. To make the process faster I can use --region to generate methylation data for those regions. But in this case the filter thresholds will be calculated from the information in these regions only. Is this accurate? Should I give a threshold value when running with --region? 
6) If my original BAM has 5hmC methylated positions but I only call methylation for 5mC using modkit pileup, does this output has any impact from 5hmC presence? Compared to a BAM with zero 5hmC methylation? 

My apologies for long questions. I am new to this and just trying to understand. 

[example.txt](https://github.com/user-attachments/files/16824050/example.txt)

Thank you very much.
Best
Sumudu

**Comment by ArtRand** [comment]
Hello @sumudu-rangika,

The bedmethyl file you've attached was not produced by modkit. I would find out which program (maybe [modbam2bed](https://github.com/epi2me-labs/modbam2bed)) produced this output and review its documentation. I can try and answer some of your questions, however. 

> The strand info is not combined here. Is there a way to combine the methylation calls from + and - strands per each position without rerunning pileup with --combine-strands parameter?

You could write some code to do this manually where you sum the appropriate columns of each (+)-strand and (-)-strand position. Depending on the nature of the table, this could be a pretty straight forward task. I'd give you a little caution, however, that there are plenty of annoying gotchas when combining strands and it might be easier to just run `modkit pileup --combine-strands --cpg` which has been thoroughly tested.

> Is it enough to remove the rows with score 0 or have low Nvalid_cov? Are there any other parameters to filter the output before downstream analysis?

Actually, `modkit` will never output a bedmethyl row with 0 valid coverage. You can filter for positions with $\gte$ some minimum coverage if you like (I usually use 3 or 5 depending on what I'm doing). If you're going to run `modkit dmr` or any of the commands in `modkit` that use bedMethyl tables, they should all have `--min-coverage` arguments that will do this filtering for you.

> I want the 5mC methylation information for selected regions in the genome, For example promoters of genes. To make the process faster I can use --region to generate methylation data for those regions. But in this case the filter thresholds will be calculated from the information in these regions only. Is this accurate? Should I give a threshold value when running with --region?

I would use `--include-bed` with a BED file of the regious you're interested in: 

```text
      --include-bed <INCLUDE_BED>
          BED file that will restrict threshold estimation and pileup results to positions
          overlapping intervals in the file. (alias: include-positions)
```

> If my original BAM has 5hmC methylated positions but I only call methylation for 5mC using modkit pileup, does this output has any impact from 5hmC presence? Compared to a BAM with zero 5hmC methylation?

If you have a modBAM with 5hmC but want to only use 5mC calls, we generally recommend using either `--ignore h` or `--preset traditional`. There are some more details in the [documentation](https://nanoporetech.github.io/modkit/collapse.html) about how 5hmC probabilities can be handled. Using the `--preset` option is documented [here](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#narrowing-output-to-cpg-dinucleotides).

**Comment by sumudu-rangika** [comment]
Hi Arthur,

Thanks a lot for the response. That helped me understand the confusion with the output. I ran modkit pileup with --combine-strands and got the expected results. 

Best
Sumudu

**Comment by ArtRand** [comment]
Great, feel free to re-open this issue if you have additional questions.
