### ISSUE TITLE
differnt CpG sites when using different threads parameter

### ISSUE THREAD

**Issue by DarwishAl** [nanoporetech/modkit#27]
Hi, thanks for this nice tool.
I got totally different number of CpG sites for the same BAM file when using modkit pileup with --preset traditional and default threads and when using the same modkit pileup (--preset traditional) but with thread 50 (-t 50). 
The difference is about 1 million sites!
Is there any explanation?
Thanks

**Comment by ArtRand** [comment]
Hello @DarwishAl ,

I have not observed this. I ran some tests on 10, 20, 40, and 60 threads on a ~8GB bam using `--preset traditional` to check and the outputs are always the same.

Do you get more sites with `-t 50` or more sites with the default (4)? Could you post the log `--log-filepath`? 

A couple things to check:
1. Confirm that you get the same estimated threshold value between multiple runs, you should see a log like similar to this: `[src/commands.rs::739][2023-06-07 14:54:14][INFO] Using filter threshold 0.7470703 for C.`. Different estimated threshold values will produce different results.
2. It's possible that some of the threads are panicing for some reason (OOM or other resource problems), this may show up in the logs, if not try adding the `--suppress-progress` flag and see if you get any errors in stderr.

**Comment by DarwishAl** [comment]
Thanks @ArtRand  
I just realized that I was using the old version of modkit, in which I got more sites when i use -t 50.
am not sure if this explain? but I am reproducing what I did with the last version of modkit, hope this will solve the issue.

**Comment by ArtRand** [comment]
Hard for me to say without seeing the logs or knowing which versions you're comparing. If you let me know those, happy to help out.

**Comment by ArtRand** [comment]
@DarwishAl , 

Feel free to re-open if you have any additional questions.
