### ISSUE TITLE
filter-threshold vs mod-threshold

### ISSUE THREAD

**Issue by bencarty2** [nanoporetech/modkit#271]
Hello, 

I'm running modkit pileup to get m6A/A values from my DiMelo-seq data. But having read the documentation I'm still somewhat confused as to what exactly the difference is between --filter-threshold and --mod-threshold are. I have exogenous m6A methylation that I wish to filter and then plot and view on e.g. igv. 

My question is what is the exact difference between e.g --filter-threshold and --mod-threshold? I noticed if I try to run --mod-threshold without the --filter-threshold it estimates a filter threshold automatically. Why does it need to do this? 

Is the filter-threshold A:0.9 (for example) only outputting adenines with >= 90% of reads at that position modified? But not in any way filtering based on 0-255 mod likelihood/ML? 

If I could be directed to the best practices for working with these filter and mod thresholds that would be great. 

Thanks, 
Ben

**Comment by ArtRand** [comment]
Hello @bencarty2, 

> My question is what is the exact difference between e.g --filter-threshold and --mod-threshold? 

There is [documentation](https://nanoporetech.github.io/modkit/filtering.html) with examples online. Briefly, `--filter-threshold` assigns either a "default threshold" (`--filter-threshold 0.9`) or a threshold to use for a canonical base (and, optionally its modifications). On the other hand `--mod-threshold` only assigns threshold values for a modification code. Here's an example:

```text
# 1. assign a threshold of 0.8, to be used for all primary sequence bases, modified and canonical calls.
--filter-threshold 0.8
# 2. assign a threshold of 0.8 for just A primary sequence bases, all modification calls on 
#    all other bases will _not_ be filtered, this behavior is logged as well.
--filter-threshold A:0.8
# 3. assign a threshold of 0.9 to 6mA and 0.75 to canonical A
--filter-threshold A:0.75 --mod-threshold a:0.75
```

> I noticed if I try to run --mod-threshold without the --filter-threshold it estimates a filter threshold automatically. Why does it need to do this?

If you pass `--mod-threshold` only, `modkit` estimates the threshold value to use for canonical calls and all other primary sequence bases. I appreciate that this is a little inconsistent with (2) above. Let me skip to this point:

> If I could be directed to the best practices for working with these filter and mod thresholds that would be great.

The recommended configuration is to let `modkit` estimate the thresholds for each primary sequence base. However, for more applications like DiMeLo, what I usually see is that first folks run `modkit sample-probs --hist` and inspect the output probability histograms. Then they pick a threshold value for every modification and canonical base in their sample - this gives the most fine tuned control. 

If you're using IGV, you can actually specify a threshold value for a modification to be visible, this skips the `modkit call-mods` step, then you can take this threshold value and use it downstream after inspecting it qualitatively. 

> Is the filter-threshold A:0.9 (for example) only outputting adenines with >= 90% of reads at that position modified?

Not quite. This setting will require that any modification call on an adenine is at least has a probability >=90%. So for example if $P_{6mA} = 0.1$ then $P_{canonical} = 1.0 - P_{6mA} = 0.9$, passes. The documentation has more examples.

> But not in any way filtering based on 0-255 mod likelihood/ML?

Not currently. Obviously there is a 1:1 mapping and you can see this in the sample-probs output.

**Comment by bencarty2** [comment]
Thanks very much for the thorough answer - much appreciated!
