### ISSUE TITLE
uncertain strand direction in the pileup bed file

### ISSUE THREAD

**Issue by SimonChen1997** [nanoporetech/modkit#274]
Hi,

I found a significant issue in the pileup file where some positions have both "+" and "-" directions. However, a specific position cannot have two A bases. it should be either A or T. This issue makes the downstream analysis difficult.

<img width="743" alt="image" src="https://github.com/user-attachments/assets/f6c07ab5-2d9f-4bd6-aa30-0700353e567f">

**Comment by SimonChen1997** [comment]
> Hi,
> 
> I found a significant issue in the pileup file where some positions have both "+" and "-" directions. However, a specific position cannot have two A bases. it should be either A or T. This issue makes the downstream analysis difficult.
> 
> <img alt="image" width="743" src="https://private-user-images.githubusercontent.com/131575296/372709320-f6c07ab5-2d9f-4bd6-aa30-0700353e567f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MTM1NjIsIm5iZiI6MTcyNzkxMzI2MiwicGF0aCI6Ii8xMzE1NzUyOTYvMzcyNzA5MzIwLWY2YzA3YWI1LTJkOWYtNGJkNi1hYTMwLTA3MDAzNTNlNTY3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQyMzU0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjk5MzUwMmIwOTM1OGEzZDRkZGZiYzFlYWVlYTcyMGI4ZjIwOGY4MDZlODA2MzkyZjJjZDcyMzU2ODEzZmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wphrbqdYYEeyT-7WQQwYk1fmbK2Jpo19Op9QVGzeUh4">

This result was generated from v0.3.2. Then I reanalyzed the data generated from v0.4.1, looks like it didn't have this issue anymore.

**Comment by SimonChen1997** [comment]
> Hi,
> 
> I found a significant issue in the pileup file where some positions have both "+" and "-" directions. However, a specific position cannot have two A bases. it should be either A or T. This issue makes the downstream analysis difficult.
> 
> <img alt="image" width="743" src="https://private-user-images.githubusercontent.com/131575296/372709320-f6c07ab5-2d9f-4bd6-aa30-0700353e567f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MTc1MTMsIm5iZiI6MTcyNzkxNzIxMywicGF0aCI6Ii8xMzE1NzUyOTYvMzcyNzA5MzIwLWY2YzA3YWI1LTJkOWYtNGJkNi1hYTMwLTA3MDAzNTNlNTY3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QwMTAwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMThjOTRjZjIwY2Q1ZmZlMmNkZjhlZjEwZTIxY2E1NGQwYWJkZGE4ZDExMWI2YmNhYmFlN2Q0ZGIwMDQ4OTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gmTwMknLeA9UscRizZCL1aQuKdm-3-4r5M6mP1JW5GQ">

I already tried the latest version 0.4.1, and the issue is still there.

**Comment by ArtRand** [comment]
Hello @SimonChen1997, 


This may happen when you have a few reads that have a mis-call at a position causing them to have a base modification call. You can suppress emitting these records by using the `--motif` and `--include-bed` arguments.

You can see this with the test data using the following commands:

```bash

ref=tests/resources/CGI_ladder_3.6kb_ref.fa
bam=tests/resources/bc_anchored_10_reads.sorted.bam
${modkit} pileup ${bam} pileup.bed --with-header
${modkit} pileup ${bam} pileup_cg0.bed --with-header --motif CG 0 --ref ${ref}
```

produces the following

```text
# pileup.bed
oligo_1512_adapters 63  64  h   5   +   63  64  255,0,0 5   20.00   1   0   4   0   1   0   0
oligo_1512_adapters 63  64  m   5   +   63  64  255,0,0 5   80.00   4   0   1   0   1   0   0
oligo_1512_adapters 63  64  h   1   -   63  64  255,0,0 1   100.00  1   0   0   0   0   3   0
oligo_1512_adapters 63  64  m   1   -   63  64  255,0,0 1   0.00    0   0   1   0   0   3   0

# pileup_cg0.bed
oligo_1512_adapters 63  64  h   5   +   63  64  255,0,0 5   20.00   1   0   4   0   1   0   0
oligo_1512_adapters 63  64  m   5   +   63  64  255,0,0 5   80.00   4   0   1   0   1   0   0
```

The output you have posted is a little hard for me to parse, however. It looks like there are repeat records for a genomic position, which shouldn't happen. Could you show me the commands you're running to produce this output?

**Comment by SimonChen1997** [comment]
> Hello @SimonChen1997,
> 
> This may happen when you have a few reads that have a mis-call at a position causing them to have a base modification call. You can suppress emitting these records by using the `--motif` and `--include-bed` arguments.
> 
> You can see this with the test data using the following commands:
> 
> ```shell
> ref=tests/resources/CGI_ladder_3.6kb_ref.fa
> bam=tests/resources/bc_anchored_10_reads.sorted.bam
> ${modkit} pileup ${bam} pileup.bed --with-header
> ${modkit} pileup ${bam} pileup_cg0.bed --with-header --motif CG 0 --ref ${ref}
> ```
> 
> produces the following
> 
> ```
> # pileup.bed
> oligo_1512_adapters 63  64  h   5   +   63  64  255,0,0 5   20.00   1   0   4   0   1   0   0
> oligo_1512_adapters 63  64  m   5   +   63  64  255,0,0 5   80.00   4   0   1   0   1   0   0
> oligo_1512_adapters 63  64  h   1   -   63  64  255,0,0 1   100.00  1   0   0   0   0   3   0
> oligo_1512_adapters 63  64  m   1   -   63  64  255,0,0 1   0.00    0   0   1   0   0   3   0
> 
> # pileup_cg0.bed
> oligo_1512_adapters 63  64  h   5   +   63  64  255,0,0 5   20.00   1   0   4   0   1   0   0
> oligo_1512_adapters 63  64  m   5   +   63  64  255,0,0 5   80.00   4   0   1   0   1   0   0
> ```
> 
> The output you have posted is a little hard for me to parse, however. It looks like there are repeat records for a genomic position, which shouldn't happen. Could you show me the commands you're running to produce this output?

Hi, 

Thanks for your reply. The repeat records are from biological replicates. However, the uncertain strand happed within one biological replicates. I'm doing bacteria methylation, so just wondering if ```--motif``` flag also works for bacteria, because there are many motifs in bacteria and there is no m6A bed for bacteria to my current knowledge. 

the command I used were
```
modkit pileup $minimap2_primary/ecoli_${SLURM_ARRAY_TASK_ID}_primary.sorted.bam $modkit_pileup_primary/ecoli_${SLURM_ARRAY_TASK_ID}_pileup.bed
```

**Comment by ArtRand** [comment]
Hello @SimonChen1997,

Yes the `--motif` argument will work for bacterial genomes. (You may also be interested in `modkit motif search`). You can use a single base "motif" to narrow to a specific strand, e.g. `--motif A 0` will only emit bedmethyl records for reads aligning to adenine bases (on either the sense or antisense strands).

**Comment by SimonChen1997** [comment]
> Hello @SimonChen1997,
> 
> Yes the `--motif` argument will work for bacterial genomes. (You may also be interested in `modkit motif search`). You can use a single base "motif" to narrow to a specific strand, e.g. `--motif A 0` will only emit bedmethyl records for reads aligning to adenine bases (on either the sense or antisense strands).

Hi ArtRand,

By using the ```--motif A 0```, mis-call results were suppressed. Thank you so much.

Cheers,
Ziming

**Comment by ArtRand** [comment]
@SimonChen1997 great, happy to help.
