### ISSUE TITLE
IGV shows Coverage not methylation values from BedMethyl

### ISSUE THREAD

**Issue by sahuno** [nanoporetech/modkit#275]
i want to see methylation values (column 11) not coverage (column 5, score) when i upload my bedMethyl file to IGV. how can i do that? 
i'm following the issue with IGV and it seems everything is working good. https://github.com/igvteam/igv/issues/1396

<img width="1262" alt="Screenshot 2024-10-03 at 1 04 44 PM" src="https://github.com/user-attachments/assets/7566adae-9683-4ce5-a803-f123ccbc36f6">

**Comment by ArtRand** [comment]
Hello @sahuno, 

I apologize for the slow response, I've been OOO. 

I'm using IGV 2.17.4 and if I name by file with the extension `.bedmethyl` then IGV will show me all of the data fields.

![image](https://github.com/user-attachments/assets/8b481c6d-340c-49c8-b40b-fa2238650f59)

**Comment by sahuno** [comment]
thanks
