### ISSUE TITLE
`error: unexpected argument '--collapse' found` for modkit 0.1.8

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/modkit#28]
Hi,
I tried to  run `modkit 0.1.8`with the options:
`modkit pileup --cpg --ref <reference.fasta> --collapse h --combine-strands`

But I got the error: 
```
error: unexpected argument '--collapse' found

  tip: to pass '--collapse' as a value, use '-- --collapse'
```
I assume that the online document is out of date due to version upgrades?

**Comment by ArtRand** [comment]
Ah shoot, [these docs](https://nanoporetech.github.io/modkit/intro_bedmethyl.html) are out of date. Thanks for the note. The option you want is `--ignore h`. I'll make an alias in the next release (and update the docs).
