### ISSUE TITLE
Understanding strand information

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#280]
Hi @ArtRand 

I just wanted to make sure I understand where the strand information comes from.

The FASTA file is the sense strand. You detect a modification on a nucleotide position. If that nucleotide can be methylated (A or C) then you assume the methylated position to be the sense (+) strand. Otherwise if it's a T or C you assume the anti-sense strand to be methylated (i.e. the A or C on the other side). 

Is this correct?

**Comment by ArtRand** [comment]
Hello @Ge0rges 

>  Otherwise if it's a T or ~C~ **G** you assume the anti-sense strand to be methylated (i.e. the A or C on the other side).

Correct.

**Comment by Ge0rges** [comment]
Thanks for catching that typo, and as usual, the prompt reply.
