### ISSUE TITLE
modkit and unmapped reads in bam file from guppy

### ISSUE THREAD

**Issue by Pigrenok** [nanoporetech/modkit#30]
Hello!

I am running a modified base calling using Guppy without alignment.

I have a BAM file from Guppy 
[bam_runid_ca07d29b288c9f8881387334d8fc7d195fb11339_0_0.bam.gz](https://github.com/nanoporetech/modkit/files/11801557/bam_runid_ca07d29b288c9f8881387334d8fc7d195fb11339_0_0.bam.gz)
It is gzipped just to be able to add it here. I use it just as a .bam file.

I sort and index it using `samtools` and then run `modkit pileup` as follows (including output from `modkit`)

```
$ samtools sort -M -o barcode1.sorted.bam -O bam bam_runid_ca07d29b288c9f8881387334d8fc7d195fb11339_0_0.bam
$samtools index barcode1.sorted.bam
$modkit pileup --include-unmapped --no-filtering barcode1.sorted.bam barcode1.bed
> not performing filtering
> Done, processed 0 rows. Processed ~0 reads and skipped zero reads.
```

At the same time, if I run `modkit summary` on the original file (not indexed), I get the following
```
$ modkit summary bam_runid_ca07d29b288c9f8881387334d8fc7d195fb11339_0_0.bam 
> sampling 10042 reads from BAM
> calculating threshold at 10% percentile
> calculated thresholds: C: 0.75390625
# bases             C 
# total_reads_used  3894 
# count_reads_C     3894 
# pass_threshold_C  0.75390625 
 base  code  pass_count  pass_frac    all_count  all_frac 
 C     h     461         0.016623994  1051       0.0341123 
 C     -     26492       0.9553208    28241      0.916618 
 C     m     778         0.028055245  1518       0.049269717
```
The same output is obtained if I run `modkit summary` on `barcode1.sorted.bam` (for which the index exists).

I tried to convert bam to sam and inspect it in a text editor and every line contains MM and ML records.

I accept that barcode1.sorted.bam is empty. I suspect it is because samtools index it by reference positions, which does not exist in the original bam file (it contains only unmapped reads).

Also, please note that it is just simple tutorial data, and the modifications are probably not real. The point is to make the workflow work at this stage.

I use `modkit` version 0.1.9.

What am I doing wrong here? Or is it a bug/feature in `modkit`?

Thank you very much in advance.

**Comment by ArtRand** [comment]
Hello @Pigrenok,

The `modkit pileup` commands requires that reads are mapped so it can aggregate base modification counts per reference position. A similar question was [asked before](https://github.com/nanoporetech/modkit/issues/21). The `--include-unmapped` flag only indicates that you want to use unmapped base modification calls when estimating the pass-threshold. It shouldn't be allowed to use `--include-unmapped` with `--no-filtering` so I'll fix that on the next release. As you've found, `modkit summary` (and `modkit extract`) will operate on unaligned modBAMs. Hope this clears up the confusion, happy to answer any additional questions.

**Comment by Pigrenok** [comment]
Thank you very much. I see now the reasons. BED would require reference positions, but without mapped reads it is not possible to assign coordinates to modification positions from a uniform coordinate system.
