### ISSUE TITLE
modkit installation in wsl

### ISSUE THREAD

**Issue by newbiezubi** [nanoporetech/modkit#303]
I am a total newbie in using command line and wsl and so on. (please be gentle)
I am trying to install the modkit on wsl to later use the modkit pileup command.
I downloaded the zip file from the release page and extracted it into a folder in wsl. 
I don't know how to proceed now.
I have a /dist_modkit_v0.4.1_cec0a0b directory and in it there these files:
licence.txt readme.md docs modkit

thank you in advance

**Comment by ArtRand** [comment]
Hello @newbiezubi,

Welcome to the command line! I'm not an expert on WSL, and I don't have easy access to an environment to test with. But here are some suggestions of things to try. 

1. Try to execute the pre-compiled binary that you've downloaded 
```bash
$ cd dist_modkit_v0.4.1_cec0a0b
$ ./modkit --version
```
If this prints `mod_kit 0.4.1`, you can use the binary that you've downloaded. 

2. You could [install rust](https://www.rust-lang.org/tools/install) in WSL or natively in Windows and compile Modkit. If it were me, I'd try the WSL route.

3. You could try to install `modkit` through the ONT [conda channel](https://anaconda.org/nanoporetech/modkit). You'll have to install some kind of `conda` in your WSL environment - and I don't have experience with how to do that.

**Comment by newbiezubi** [comment]
hey.
so I am already in the right directory dist_modkit_v0.4.1_cec0a0b
how do i execute it? this is where i am stuck.
Thank you

**Comment by ArtRand** [comment]
Hello @newbiezubi 
Executing 
```bash
./modkit
```
in that directory should run the program.

**Comment by newbiezubi** [comment]
hello @ArtRand,
I run ./modkit and I got a help page with all the commands ,so I think it works now,
thank you ,cheers
