### ISSUE TITLE
Converting modbam to modification-aware nucleotides

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/modkit#304]
Kind of a strange question, but is there a suggested workflow for converting the aligned sequence from a modbam to ACGT + mods (eg, m for 5mC, h for 5hmC)? I was thinking of two methods: extracting the per read aligned region from extract calls, turning that into nucleotides, and using the modified base calls to change C->m,h. Or, I could work directly on the bam but that would require doing the mod probability thresholding manually. Any suggestions?

**Comment by ArtRand** [comment]
Hello @billytcl, 

Not so strange, I've also been experimenting with something like that (but with reference sequences). What I've done is use a reference FASTA and a BED with the annotations. You could probably convert the output table from `extract calls` into a similar BED file - but it probably gets untenable quickly. What tools are you using downstream? My hesitation to expanding the alphabet has been that many tools won't read them (e.g. samtools if I recall correctly). I think Jalview will take them as FASTA though.

**Comment by billytcl** [comment]
I’m trying to feed it as sequences in a language model or similar NLP
workflow! So basically ACGTmh as my alphabet instead of ACGT. I think
converting into a bed may be the easiest way…

**Comment by ArtRand** [comment]
Good luck!
