### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by shakti83kumar** [nanoporetech/modkit#309]
Hello Friends,
I am getting below mentioned error while installation.  Please help me in installation.
Thanks & regards
Shakti Kumar

shaktikumar@shaktikumar-N7-B650E:~/Softwares$ sudo cargo install --git https://github.com/nanoporetech/modkit.git
[sudo] password for shaktikumar: 
    Updating git repository `https://github.com/nanoporetech/modkit.git`
  Installing mod_kit v0.4.1 (https://github.com/nanoporetech/modkit.git#cec0a0bb)
    Updating crates.io index
  Downloaded bitflags v2.6.0
  Downloaded either v1.13.0
  Downloaded destructure_traitobject v0.2.0
  Downloaded fs-utils v1.1.4
  Downloaded doc-comment v0.3.3
  Downloaded equivalent v1.0.1
  Downloaded fxhash v0.2.1
  Downloaded log-mdc v0.1.0
  Downloaded number_prefix v0.4.0
  Downloaded nalgebra-macros v0.1.0
  Downloaded icu_provider_macros v1.5.0
  Downloaded block-buffer v0.10.4
  Downloaded anstyle v1.0.10
  Downloaded peroxide-ad v0.3.0
  Downloaded newtype_derive v0.1.6
  Downloaded bit-vec v0.6.3
  Downloaded anstyle-query v1.1.2
  Downloaded bytecount v0.6.8
  Downloaded byteorder v1.5.0
  Downloaded rawpointer v0.2.1
  Downloaded reborrow v0.5.5
  Downloaded bit-set v0.5.3
  Downloaded anstream v0.6.18
  Downloaded clap_lex v0.7.3
  Downloaded cfg-if v1.0.0
  Downloaded approx v0.5.1
  Downloaded cpufeatures v0.2.16
  Downloaded crossbeam-deque v0.8.5
  Downloaded crypto-common v0.1.6
  Downloaded enum-map-derive v0.17.0
  Downloaded crossbeam-queue v0.3.11
  Downloaded derive-new v0.6.0
  Downloaded common_macros v0.1.1
  Downloaded colorchoice v1.0.3
  Downloaded core_affinity v0.8.1
  Downloaded funty v2.0.0
  Downloaded fnv v1.0.7
  Downloaded derive-new v0.5.9
  Downloaded feature-probe v0.1.1
  Downloaded fixedbitset v0.4.2
  Downloaded write16 v1.0.0
  Downloaded dirs-next v2.0.0
  Downloaded cmake v0.1.52
  Downloaded lru v0.9.0
  Downloaded enum-map v2.7.3
  Downloaded digest v0.10.7
  Downloaded nanorand v0.7.0
  Downloaded lazy_static v1.5.0
  Downloaded glob v0.3.1
  Downloaded form_urlencoded v1.2.1
  Downloaded log-once v0.4.1
  Downloaded itertools-num v0.1.3
  Downloaded itoa v1.0.14
  Downloaded multimap v0.9.1
  Downloaded linear-map v1.2.0
  Downloaded generic-array v0.14.7
  Downloaded futures-sink v0.3.31
  Downloaded heck v0.4.1
  Downloaded heck v0.5.0
  Downloaded num v0.4.3
  Downloaded crossbeam v0.8.4
  Downloaded ansi_term v0.12.1
  Downloaded futures-core v0.3.31
  Downloaded autocfg v1.4.0
  Downloaded pest_generator v2.7.14
  Downloaded num-iter v0.1.45
  Downloaded editdistancek v1.0.2
  Downloaded num-integer v0.1.46
  Downloaded humantime v2.1.0
  Downloaded anstyle-parse v0.2.6
  Downloaded libdeflater v0.12.0
  Downloaded radium v0.7.0
  Downloaded bio-types v1.0.4
  Downloaded rustversion v1.0.18
  Downloaded rand_chacha v0.3.1
  Downloaded scopeguard v1.2.0
  Downloaded zerofrom v0.1.5
  Downloaded order-stat v0.1.3
  Downloaded typemap-ors v1.0.0
  Downloaded serde-value v0.7.0
  Downloaded anyhow v1.0.93
  Downloaded num_cpus v1.16.0
  Downloaded ieee754 v0.2.6
  Downloaded rand_core v0.6.4
  Downloaded tap v1.0.1
  Downloaded paste v1.0.15
  Downloaded shlex v1.3.0
  Downloaded clap_derive v4.5.18
  Downloaded console v0.15.8
  Downloaded quick-error v1.2.3
  Downloaded ordered-float v2.10.1
  Downloaded custom_derive v0.1.7
  Downloaded crc32fast v1.4.2
  Downloaded dirs-sys-next v0.1.2
  Downloaded csv-core v0.1.11
  Downloaded ordered-float v3.9.2
  Downloaded rustc_version v0.1.7
  Downloaded puruspe v0.2.5
  Downloaded errno v0.3.10
  Downloaded percent-encoding v2.3.1
  Downloaded rustc-hash v1.1.0
  Downloaded random_color v1.0.0
  Downloaded ppv-lite86 v0.2.20
  Downloaded iana-time-zone v0.1.61
  Downloaded displaydoc v0.2.5
  Downloaded utf8_iter v1.0.4
  Downloaded utf16_iter v1.0.5
  Downloaded unsafe-any-ors v1.0.0
  Downloaded strum v0.25.0
  Downloaded is-terminal v0.4.13
  Downloaded thread-id v4.2.2
  Downloaded substring v1.4.5
  Downloaded ahash v0.8.11
  Downloaded getrandom v0.2.15
  Downloaded idna_adapter v1.2.0
  Downloaded tinystr v0.7.6
  Downloaded icu_locid_transform v1.5.0
  Downloaded once_cell v1.20.2
  Downloaded bytemuck v1.20.0
  Downloaded bv v0.11.1
  Downloaded prettytable-rs v0.10.0
  Downloaded strsim v0.11.1
  Downloaded utf8parse v0.2.2
  Downloaded writeable v0.5.5
  Downloaded special v0.10.3
  Downloaded pkg-config v0.3.31
  Downloaded version_check v0.9.5
  Downloaded spin v0.9.8
  Downloaded pin-project-internal v1.1.7
  Downloaded strum_macros v0.26.4
  Downloaded yoke-derive v0.7.5
  Downloaded is_terminal_polyfill v1.70.1
  Downloaded stable_deref_trait v1.2.0
  Downloaded synstructure v0.13.1
  Downloaded lock_api v0.4.12
  Downloaded jobserver v0.1.32
  Downloaded clap v4.5.21
  Downloaded crossbeam-utils v0.8.20
  Downloaded crossbeam-epoch v0.9.18
  Downloaded derivative v2.2.0
  Downloaded num-rational v0.4.2
  Downloaded num-complex v0.4.6
  Downloaded thiserror v1.0.69
  Downloaded terminal_size v0.4.1
  Downloaded wyz v0.5.1
  Downloaded smallvec v1.13.2
  Downloaded icu_provider v1.5.0
  Downloaded icu_locid_transform_data v1.5.0
  Downloaded icu_normalizer_data v1.5.0
  Downloaded quote v1.0.37
  Downloaded parking_lot_core v0.9.10
  Downloaded sha2 v0.10.8
  Downloaded arc-swap v1.7.1
  Downloaded thread-tree v0.3.3
  Downloaded semver v0.1.20
  Downloaded vec_map v0.8.2
  Downloaded bytes v1.9.0
  Downloaded zerovec-derive v0.10.3
  Downloaded zerofrom-derive v0.1.5
  Downloaded flume v0.10.14
  Downloaded log v0.4.22
  Downloaded pest_derive v2.7.14
  Downloaded proc-macro2 v1.0.92
  Downloaded num-traits v0.2.19
  Downloaded parking_lot v0.12.3
  Downloaded ucd-trie v0.1.7
  Downloaded simba v0.6.0
  Downloaded pest_meta v2.7.14
  Downloaded term v0.7.0
  Downloaded icu_properties v1.5.1
  Downloaded icu_normalizer v1.5.0
  Downloaded rust-lapper v1.1.0
  Downloaded zerocopy-derive v0.7.35
  Downloaded ryu v1.0.18
  Downloaded thiserror-impl v1.0.69
  Downloaded yoke v0.7.5
  Downloaded unicode-ident v1.0.14
  Downloaded encode_unicode v1.0.0
  Downloaded log4rs v1.3.0
  Downloaded matrixmultiply v0.3.9
  Downloaded pin-project v1.1.7
  Downloaded icu_locid v1.5.0
  Downloaded icu_collections v1.5.0
  Downloaded rand_distr v0.4.3
  Downloaded litemap v0.7.4
  Downloaded rayon-core v1.12.1
  Downloaded strum_macros v0.25.3
  Downloaded typenum v1.17.0
  Downloaded triple_accel v0.4.0
  Downloaded cc v1.2.2
  Downloaded crossbeam-channel v0.5.13
  Downloaded handlebars v4.5.0
  Downloaded unsafe-libyaml v0.2.11
  Downloaded openssl-sys v0.9.104
  Downloaded indicatif v0.17.9
  Downloaded serde_derive v1.0.215
  Downloaded flate2 v1.0.35
  Downloaded serde v1.0.215
  Downloaded hashbrown v0.13.2
  Downloaded serde_yaml v0.9.34+deprecated
  Downloaded indexmap v2.7.0
  Downloaded minimal-lexical v0.2.1
  Downloaded wide v0.7.30
  Downloaded safe_arch v0.7.2
  Downloaded rand v0.8.5
  Downloaded itertools v0.12.1
  Downloaded url v2.5.4
  Downloaded hashbrown v0.15.2
  Downloaded num-bigint v0.4.6
  Downloaded memchr v2.7.4
  Downloaded idna v1.0.3
  Downloaded zerovec v0.10.4
  Downloaded itertools v0.11.0
  Downloaded clap_builder v4.5.21
  Downloaded libm v0.2.11
  Downloaded nom v7.1.3
  Downloaded rust-htslib v0.46.0
  Downloaded statrs v0.16.1
  Downloaded aho-corasick v1.1.3
  Downloaded pest v2.7.14
  Downloaded pulp v0.18.22
  Downloaded bio v1.6.0
  Downloaded bitvec v1.0.1
  Downloaded chrono v0.4.38
  Downloaded portable-atomic v1.10.0
  Downloaded serde_json v1.0.133
  Downloaded libdeflate-sys v0.12.0
  Downloaded zerocopy v0.7.35
  Downloaded syn v1.0.109
  Downloaded peroxide v0.32.1
  Downloaded rayon v1.10.0
  Downloaded icu_properties_data v1.5.0
  Downloaded rv v0.16.0
  Downloaded unicode-width v0.2.0
  Downloaded unicode-width v0.1.14
  Downloaded ndarray v0.15.6
  Downloaded charming v0.3.1
  Downloaded vcpkg v0.2.15
  Downloaded regex v1.11.1
  Downloaded syn v2.0.90
  Downloaded nalgebra v0.29.0
  Downloaded rustix v0.38.41
  Downloaded regex-syntax v0.8.5
  Downloaded bzip2-sys v0.1.11+1.0.8
  Downloaded csv v1.3.1
  Downloaded regex-automata v0.4.9
  Downloaded lzma-sys v0.1.20
  Downloaded petgraph v0.6.5
  Downloaded libc v0.2.167
  Downloaded libz-sys v1.1.20
  Downloaded curl-sys v0.4.78+curl-8.11.0
  Downloaded gzp v0.11.3
  Downloaded linux-raw-sys v0.4.14
  Downloaded hts-sys v2.2.0
  Downloaded openssl-src v300.4.1+3.4.0
  Downloaded 255 crates (39.0 MB) in 1m 06s (largest was `openssl-src` at 9.9 MB)
   Compiling proc-macro2 v1.0.92
   Compiling unicode-ident v1.0.14
   Compiling libc v0.2.167
   Compiling autocfg v1.4.0
   Compiling shlex v1.3.0
   Compiling libm v0.2.11
   Compiling cfg-if v1.0.0
   Compiling pkg-config v0.3.31
   Compiling byteorder v1.5.0
   Compiling crossbeam-utils v0.8.20
   Compiling serde v1.0.215
   Compiling thiserror v1.0.69
   Compiling memchr v2.7.4
   Compiling syn v1.0.109
   Compiling stable_deref_trait v1.2.0
   Compiling vcpkg v0.2.15
   Compiling once_cell v1.20.2
   Compiling bytemuck v1.20.0
   Compiling writeable v0.5.5
   Compiling litemap v0.7.4
   Compiling itoa v1.0.14
   Compiling ryu v1.0.18
   Compiling smallvec v1.13.2
   Compiling icu_locid_transform_data v1.5.0
   Compiling lazy_static v1.5.0
   Compiling rawpointer v0.2.1
   Compiling rustversion v1.0.18
   Compiling heck v0.5.0
   Compiling semver v0.1.20
   Compiling version_check v0.9.5
   Compiling ucd-trie v0.1.7
   Compiling scopeguard v1.2.0
   Compiling paste v1.0.15
   Compiling icu_properties_data v1.5.0
   Compiling either v1.13.0
   Compiling serde_json v1.0.133
   Compiling regex-syntax v0.8.5
   Compiling equivalent v1.0.1
   Compiling safe_arch v0.7.2
   Compiling utf8_iter v1.0.4
   Compiling utf16_iter v1.0.5
   Compiling hashbrown v0.15.2
   Compiling icu_normalizer_data v1.5.0
   Compiling typenum v1.17.0
   Compiling quick-error v1.2.3
   Compiling write16 v1.0.0
   Compiling rustc_version v0.1.7
   Compiling rustix v0.38.41
   Compiling fs-utils v1.1.4
   Compiling rayon-core v1.12.1
   Compiling parking_lot_core v0.9.10
   Compiling feature-probe v0.1.1
   Compiling utf8parse v0.2.2
   Compiling glob v0.3.1
   Compiling anyhow v1.0.93
   Compiling linux-raw-sys v0.4.14
   Compiling num-traits v0.2.19
   Compiling matrixmultiply v0.3.9
   Compiling lock_api v0.4.12
   Compiling ahash v0.8.11
   Compiling bitflags v2.6.0
   Compiling bv v0.11.1
   Compiling anstyle-parse v0.2.6
   Compiling doc-comment v0.3.3
   Compiling newtype_derive v0.1.6
   Compiling wide v0.7.30
   Compiling aho-corasick v1.1.3
   Compiling csv-core v0.1.11
   Compiling anstyle v1.0.10
   Compiling radium v0.7.0
   Compiling anstyle-query v1.1.2
   Compiling portable-atomic v1.10.0
   Compiling colorchoice v1.0.3
   Compiling is_terminal_polyfill v1.70.1
   Compiling unicode-width v0.1.14
   Compiling destructure_traitobject v0.2.0
   Compiling peroxide v0.32.1
   Compiling percent-encoding v2.3.1
   Compiling unsafe-any-ors v1.0.0
   Compiling anstream v0.6.18
   Compiling substring v1.4.5
   Compiling crc32fast v1.4.2
   Compiling futures-sink v0.3.31
   Compiling fixedbitset v0.4.2
   Compiling quote v1.0.37
   Compiling form_urlencoded v1.2.1
   Compiling bit-vec v0.6.3
   Compiling crossbeam-channel v0.5.13
   Compiling crossbeam-epoch v0.9.18
   Compiling indexmap v2.7.0
   Compiling spin v0.9.8
   Compiling tap v1.0.1
   Compiling custom_derive v0.1.7
   Compiling syn v2.0.90
   Compiling strsim v0.11.1
   Compiling heck v0.4.1
   Compiling order-stat v0.1.3
   Compiling puruspe v0.2.5
   Compiling clap_lex v0.7.3
   Compiling unsafe-libyaml v0.2.11
   Compiling iana-time-zone v0.1.61
   Compiling futures-core v0.3.31
   Compiling bit-set v0.5.3
   Compiling jobserver v0.1.32
   Compiling getrandom v0.2.15
   Compiling num_cpus v1.16.0
   Compiling crossbeam-deque v0.8.5
   Compiling dirs-sys-next v0.1.2
   Compiling console v0.15.8
   Compiling is-terminal v0.4.13
   Compiling thread-id v4.2.2
   Compiling wyz v0.5.1
   Compiling dirs-next v2.0.0
   Compiling cc v1.2.2
   Compiling rand_core v0.6.4
   Compiling thread-tree v0.3.3
   Compiling nanorand v0.7.0
   Compiling parking_lot v0.12.3
   Compiling term v0.7.0
   Compiling core_affinity v0.8.1
   Compiling crossbeam-queue v0.3.11
   Compiling typemap-ors v1.0.0
   Compiling terminal_size v0.4.1
   Compiling special v0.10.3
   Compiling itertools v0.11.0
   Compiling clap_builder v4.5.21
   Compiling fxhash v0.2.1
   Compiling fnv v1.0.7
   Compiling arc-swap v1.7.1
   Compiling num-integer v0.1.46
   Compiling num-complex v0.4.6
   Compiling approx v0.5.1
   Compiling ordered-float v2.10.1
   Compiling petgraph v0.6.5
   Compiling chrono v0.4.38
   Compiling itertools-num v0.1.3
   Compiling ordered-float v3.9.2
   Compiling strum v0.25.0
   Compiling log-mdc v0.1.0
   Compiling minimal-lexical v0.2.1
   Compiling encode_unicode v1.0.0
   Compiling humantime v2.1.0
   Compiling number_prefix v0.4.0
   Compiling rayon v1.10.0
   Compiling num-bigint v0.4.6
   Compiling num-iter v0.1.45
   Compiling linear-map v1.2.0
   Compiling bytecount v0.6.8
   Compiling funty v2.0.0
   Compiling reborrow v0.5.5
   Compiling unicode-width v0.2.0
   Compiling bytes v1.9.0
   Compiling ieee754 v0.2.6
   Compiling editdistancek v1.0.2
   Compiling cmake v0.1.52
   Compiling openssl-src v300.4.1+3.4.0
   Compiling triple_accel v0.4.0
   Compiling pulp v0.18.22
   Compiling regex-automata v0.4.9
   Compiling nom v7.1.3
   Compiling rust-lapper v1.1.0
   Compiling simba v0.6.0
   Compiling crossbeam v0.8.4
   Compiling itertools v0.12.1
   Compiling common_macros v0.1.1
   Compiling rustc-hash v1.1.0
   Compiling ansi_term v0.12.1
   Compiling bitvec v1.0.1
   Compiling ndarray v0.15.6
   Compiling libz-sys v1.1.20
   Compiling openssl-sys v0.9.104
   Compiling lzma-sys v0.1.20
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling curl-sys v0.4.78+curl-8.11.0
   Compiling libdeflate-sys v0.12.0
   Compiling hts-sys v2.2.0
   Compiling num-rational v0.4.2
   Compiling num v0.4.3
   Compiling indicatif v0.17.9
   Compiling regex v1.11.1
   Compiling synstructure v0.13.1
   Compiling nalgebra-macros v0.1.0
   Compiling peroxide-ad v0.3.0
   Compiling derivative v2.2.0
   Compiling derive-new v0.5.9
   Compiling serde_derive v1.0.215
   Compiling zerocopy-derive v0.7.35
   Compiling zerofrom-derive v0.1.5
   Compiling thiserror-impl v1.0.69
   Compiling yoke-derive v0.7.5
   Compiling zerovec-derive v0.10.3
   Compiling displaydoc v0.2.5
   Compiling icu_provider_macros v1.5.0
   Compiling pin-project-internal v1.1.7
   Compiling derive-new v0.6.0
   Compiling strum_macros v0.26.4
   Compiling enum-map-derive v0.17.0
   Compiling strum_macros v0.25.3
   Compiling flate2 v1.0.35
   Compiling clap_derive v4.5.18
   Compiling libdeflater v0.12.0
   Compiling enum-map v2.7.3
   Compiling zerocopy v0.7.35
   Compiling pin-project v1.1.7
   Compiling flume v0.10.14
   Compiling pest v2.7.14
   Compiling zerofrom v0.1.5
   Compiling ppv-lite86 v0.2.20
   Compiling yoke v0.7.5
   Compiling bio-types v1.0.4
   Compiling gzp v0.11.3
   Compiling hashbrown v0.13.2
   Compiling zerovec v0.10.4
   Compiling clap v4.5.21
   Compiling rand_chacha v0.3.1
   Compiling rand v0.8.5
   Compiling lru v0.9.0
   Compiling pest_meta v2.7.14
   Compiling tinystr v0.7.6
   Compiling icu_collections v1.5.0
   Compiling rand_distr v0.4.3
   Compiling random_color v1.0.0
   Compiling icu_locid v1.5.0
   Compiling nalgebra v0.29.0
   Compiling pest_generator v2.7.14
   Compiling icu_provider v1.5.0
   Compiling icu_locid_transform v1.5.0
   Compiling pest_derive v2.7.14
   Compiling icu_properties v1.5.1
   Compiling rv v0.16.0
   Compiling log v0.4.22
   Compiling csv v1.3.1
   Compiling vec_map v0.8.2
   Compiling multimap v0.9.1
   Compiling serde_yaml v0.9.34+deprecated
   Compiling serde-value v0.7.0
   Compiling log-once v0.4.1
   Compiling prettytable-rs v0.10.0
   Compiling icu_normalizer v1.5.0
   Compiling handlebars v4.5.0
   Compiling idna_adapter v1.2.0
   Compiling idna v1.0.3
   Compiling log4rs v1.3.0
   Compiling url v2.5.4
   Compiling charming v0.3.1
   Compiling statrs v0.16.1
   Compiling bio v1.6.0
   Compiling rust-htslib v0.46.0
   Compiling mod_kit v0.4.1 (/root/.cargo/git/checkouts/modkit-29a79722a38395c9/cec0a0b)
error[E0658]: use of unstable library feature 'file_create_new'
   --> src/writers.rs:585:13
    |
585 |             File::create_new(fp).context("refusing to overwrite {fp:?}")?
    |             ^^^^^^^^^^^^^^^^
    |
    = note: see issue #105135 <https://github.com/rust-lang/rust/issues/105135> for more information

error[E0658]: use of unstable library feature 'file_create_new'
   --> src/localise/subcommand.rs:230:45
    |
230 |                     Box::new(BufWriter::new(File::create_new(out_fp)?))
    |                                             ^^^^^^^^^^^^^^^^
    |
    = note: see issue #105135 <https://github.com/rust-lang/rust/issues/105135> for more information

error[E0658]: use of unstable library feature 'file_create_new'
   --> src/localise/subcommand.rs:287:17
    |
287 |                 File::create_new(p)?
    |                 ^^^^^^^^^^^^^^^^
    |
    = note: see issue #105135 <https://github.com/rust-lang/rust/issues/105135> for more information

error[E0658]: use of unstable library feature 'file_create_new'
  --> src/stats/subcommand.rs:67:13
   |
67 |             File::create_new(&self.out_table)?
   |             ^^^^^^^^^^^^^^^^
   |
   = note: see issue #105135 <https://github.com/rust-lang/rust/issues/105135> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `mod_kit` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mod_kit v0.4.1 (https://github.com/nanoporetech/modkit.git#cec0a0bb)`, intermediate artifacts can be found at `/tmp/cargo-installdLeZyG`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by ArtRand** [comment]
Hello @shakti83kumar, 

Could you tell me what `$ cargo --version` and `$ rustc --version` show you? Also how did you install rust? The `File::create_new` function requires rust >= 1.77.0, but I would expect that cargo should pick that up from the `rust-toolchain.toml`.

**Comment by shakti83kumar** [comment]
Hi @ArtRand,
I have rectified the mod-kit installation problem and successfully installed. 
first of all, I have uninstall the rustc from synaptic package manager and follow the 
 rustc the instruction from page https://www.rust-lang.org/tools/install.
Next I follow the https://nanoporetech.github.io/modkit/quick_start.html for successful installation especially  by this "cargo install --git https://github.com/nanoporetech/modkit.git"
Thanks for your support
