### ISSUE TITLE
pileup warning "double added base mod calls for base C..."

### ISSUE THREAD

**Issue by santanaw** [nanoporetech/modkit#31]
Hi all.  Thank you for developing modkit. I am having the same warning as reported in #18 . I’m running `modkit pileup` (command at the bottom) using modkit v0.1.9 and I’m getting the next warnings:

```
[src/read_ids_to_base_mod_probs.rs::56][2023-06-16 11:30:54][DEBUG] double added base mod calls for base C and read e910bc1f-271e-42d1-a18b-b2ef58c48e1f;e5c15025-43f1-4093-b276-859c90e98349,potentially a logic error, please submit an issue.
[src/read_ids_to_base_mod_probs.rs::56][2023-06-16 11:30:54][DEBUG] double added base mod calls for base C and read bb36d4b8-1e66-49dd-a9da-f3b51959ccf5;fa4c1b4d-7e65-42ab-9422-87a077ca76e7,potentially a logic error, please submit an issue.
```
My bam file has only duplex reads with modifications in both strands as produced by `remora duplex_from_pod5_and_bam`. Interesting, all the read ids are listed in log file with the aforementioned warning. I also tried with a bam file that is made of simplex and duplex reads  and only the ids of duplexes are logged in the file, also with the same warning. In all cases I have previously discarded there secondary, supplementary alignments, etc.

Are duplex reads with modifications supported?

Thanks
```
modkit pileup --cpg --threads 5 --seed 1234 --ref tmp.fasta --log-filepath tmp.log dx.bam dx.bedmethyl
```

**Comment by ArtRand** [comment]
Hello @santanaw,

This message is emitted when sampling reads to estimate the pass-threshold value before performing pileup. I was able to reproduce the behavior you're seeing, it's a bug in the sampler, I'll get a patch release out very soon.

In the mean time, the bug should not affect the results of `pileup` unless you're seeing a very low estimated pass threshold (should be in a log line). Duplex reads with modifications _are_ supported. Thanks for reporting the issue!

**Comment by ArtRand** [comment]
@santanaw (sorry github auto-closed the issue)

Version [0.1.10](https://github.com/nanoporetech/modkit/releases/tag/v0.1.10) should have this bug fixed, let me know if you still encounter any issues.

**Comment by santanaw** [comment]
Hi @ArtRand. Thanks a lot for the rapid patch release! I have tested the version [0.1.10](https://github.com/nanoporetech/modkit/releases/tag/v0.1.10) and the previously reported logs are gone. As a side note, the passing threshold increased from 0.7597656 to 0.7792969. Thanks again!
