### ISSUE TITLE
SSL invalid error

### ISSUE THREAD

**Issue by baibhav-bioinfo** [nanoporetech/modkit#311]
Hello,
i was using the Dorado for m6A methylation calling from DRS data.

time   dorado    basecaller    rna004_130bps_hac\@v5.1.0    /pod5/    --modified-bases-models 
   rna004_130bps_hac\@v5.1.0_m6A_DRACH\@v1/    --device cuda:all    --reference    ref.fa   >    1_sup.bam

then i was using modkit for downstream analysis from obtained "bam" file.
but there was error while installing "modkit". 

$ cargo install --verbose --git https://github.com/nanoporetech/modkit.git
INFO:    gocryptfs not found, will not be able to use gocryptfs
    Updating git repository `https://github.com/nanoporetech/modkit.git`
error: failed to fetch into /home1/10185/baibhav/.cargo/git/db/modkit-29a79722a38395c9

Caused by:
  [16/-17] The SSL certificate is invalid

Even the "cargo install --path ." is giving same error

**Comment by ArtRand** [comment]
Hello @baibhav-bioinfo,

How did you install rust? Maybe try either re-installing with `rustup` or cleaning out the caches. Can you use the [pre-built binary](https://github.com/nanoporetech/modkit/releases) releases?

**Comment by baibhav-bioinfo** [comment]
hello @ArtRand, thanks for the reply
i was able to install it using "conda install nanoporeech::modkit"

**Comment by ArtRand** [comment]
Great.
