### ISSUE TITLE
known motif table in modkit find-motifs

### ISSUE THREAD

**Issue by hannan666666** [nanoporetech/modkit#324]
I noticed that the --known-motif option allows users to provide specific motifs of interest, excluding the CG motif. I was wondering if there are any precompiled or commonly used motif lists that I can directly use, rather than defining/de-_novo_ search them manually.

If anyone has a collection of summarized motifs or knows where I can find one, I would appreciate it if you could share that information.

**Comment by ArtRand** [comment]
Hello @hannan666666, 

You may try [REBASE](http://rebase.neb.com/rebase/rebase.charts.html), for example this [list](http://rebase.neb.com/rebase/rebase_methylase_recseqs.txt).

**Comment by hannan666666** [comment]
Hi @ArtRand ,

Thank you so much for the suggestion! I'll definitely check out it. I really appreciate your help!

**Comment by ArtRand** [comment]
Great!
