### ISSUE TITLE
incomplete output using duplex and bed with modkit extract

### ISSUE THREAD

**Issue by santanaw** [nanoporetech/modkit#33]
Hi @ArtRand . I’m running `modkit extract` using duplex reads with modifications on both strands and using a bed file to restrict output to CpG’s  (see below). The bed file was produced with the `modkit motif-bed` as seen in the documentation.
```modkit extract dx.bam mods.tab --ref my_fasta.fa --include-bed my_cg_motifs.bed```

 However, the command only reports the information of one  (e.g. position **155575**)  of the two cytosine bases (e.g position **155574** and **155575**)  within the CpG context for both strands.  Output using bed:
 ```
1e309936-8d76-45f5-b1ab-1b81a856718e;f313897e-af24-4cb2-affe-befaee892059       22281   155575  1       +       -       47      10      22303   0.001953125     h       34      CCGAC   GTCGG   C
1e309936-8d76-45f5-b1ab-1b81a856718e;f313897e-af24-4cb2-affe-befaee892059       22281   155575  1       +       -       47      10      22303   0.001953125     m       34      CCGAC   GTCGG   C
1e309936-8d76-45f5-b1ab-1b81a856718e;f313897e-af24-4cb2-affe-befaee892059       22245   155611  1       +       -       47      10      22303   0.009765625     h       50      TCGGG   CCCGA   C
1e309936-8d76-45f5-b1ab-1b81a856718e;f313897e-af24-4cb2-affe-befaee892059       22245   155611  1       +       -       47      10      22303   0.001953125     m       50      TCGGG   CCCGA   C
```
This is not the case when I run the command without the bed file, both cytosine bases of the CpGs are reported (i.e. position **155574** and **155575**) -in the cases where a CpG exists of course. Output not using bed:
```
1e309936-8d76-45f5-b1ab-1b81a856718e;f313897e-af24-4cb2-affe-befaee892059       22282   155574  1       -       -       47      10      22303   0.001953125     h       39      CCCGA   CCCGA   G
1e309936-8d76-45f5-b1ab-1b81a856718e;f313897e-af24-4cb2-affe-befaee892059       22282   155574  1       -       -       47      10      22303   0.001953125     m       39      CCCGA   CCCGA   G
1e309936-8d76-45f5-b1ab-1b81a856718e;f313897e-af24-4cb2-affe-befaee892059       22281   155575  1       +       -       47      10      22303   0.001953125     h       34      CCGAC   GTCGG   C
1e309936-8d76-45f5-b1ab-1b81a856718e;f313897e-af24-4cb2-affe-befaee892059       22281   155575  1       +       -       47      10      22303   0.001953125     m       34      CCGAC   GTCGG   C
1e309936-8d76-45f5-b1ab-1b81a856718e;f313897e-af24-4cb2-affe-befaee892059       22246   155610  1       -       -       47      10      22303   0.017578125     h       39      CTCGG   CTCGG   G
```
1. Is there any reason why could this be happening?

2. I notice that in the ```modkit extract``` command example in the [documentation](https://nanoporetech.github.io/modkit/intro_extract.html) the `--include-bed` is not used but the `--include-only` option is, which will thrown an error in the latest versions.

Extra question:
I am puzzled about the modifications probabilities conversion. For instance,  the last output example (position **155574**) the converted  probability is 0.001953125. However,  if I convert this probability back  ( 0.001953125*256), I get 0.5 and the bam encoded is 0 at this modification position.  Is it because taking the middle point between the two integers (e.g. [0,1]) is the safest for remapping between the two scale probabilities ranges (  [0,255] -> [0,1]  )?

Thank you for any information!

**Comment by ArtRand** [comment]
Hi @santanaw,

I'll take a look at using the `--include-bed` with duplex. I'll update the docs as well. Thanks for bringing this to my attention!

For your extra question. Yes `modkit` adjusts the ML tag "qualities" by 0.5 so that all of the reported probabilities will land in the middle of the bins [0,255] as you guessed. There is perhaps a small precedent for doing this in the [SAM-tags tests](https://github.com/samtools/hts-specs/blob/master/test/SAMtags/parse_mm.pl#L88)

Thanks for hammering on `modkit` with duplex!

**Comment by santanaw** [comment]
Hi @ArtRand,

It's a pleasure :grinning:, modkit is great to use as make things simpler.

I had the feeling  the problem was arising because of the change in strands and the strand that is expected in bed(?). Particularly for reverse reads(?).

Thanks again for the prompt response and the information!

**Comment by ArtRand** [comment]
Hello @santanaw ,

I've made a 0.1.11 release candidate ([0.1.11-rc1](https://github.com/nanoporetech/modkit/releases/tag/v0.1.11-rc1)). In my tests it fixes the issue you're seeing. Please confirm at your convenience.

**Comment by santanaw** [comment]
Hi @ArtRand. Thanks again for the prompt fix! I tested the [0.1.11-rc1](https://github.com/nanoporetech/modkit/releases/tag/v0.1.11-rc1) version, and the output files are now complete.

Some final thoughts/questions regarding the output fields of `modkit extract` :

I am aware that fields in the output follows the conventions of the htslib environment for the modifications (e.g. forward_read_position, mod_strand, etc.) . However, would you consider reorienting the “mod_strand” field particularly for duplexes reported in the reverse strand? For instance,  the records I shared map to the reverse strand and positions  **155574** and **155575**  would correspond to nucleotides GC (the complement of CpG in forward strand) as correctly shown by the “canonical_base” column for positions. However by definition from the “mod_strand” field description in the documentation, the strand reported in this field is the “strand of the molecule the base modification is on” which might not necessarily  hold for these records (again, sticking to field definition ) as the modifications are occurring on Cytosines for **+** at **155574** and **-** at **155575**, instead the table shows  the opposite **-** for **155574** and **+** for **155575** (in a more similar spirit of the BAM tags). Alternatively, a modification of the field definition or the addition of notes could work. However I will be a strong supporter of reorienting these cases (`modkit pileup`  does it), as I see more scenarios where the reorientation might be more handy (at least I would need to do it for my downstream analyses). 

Might some additional notes be helpful in the documentation for the “query_kmer” field concept?

**Comment by ArtRand** [comment]
Hi @santanaw 

I'm open to this idea. Just for clarification the `mod_strand` is the strand of the _sequenced_ molecule that the modification was on (you figured this out), I can update the documentation. In general, duplex reads are "template oriented" which in practice is probably somewhat arbitrary, but should be the strand that's captured first.

Perhaps a solution is to add another column, `ref_mod_strand` (maybe instead of `ref_strand`), specifying which reference strand the base modification is on. So in your example, `155574` would be `+` since it's the forward `C` in the CpG, and `155575` would be `-` since it's the complement to the following `G`. This way, the (`forward_read_position`, `mod_strand`) tuple wouldn't change when you go from an unaligned BAM to an aligned one.

**Comment by santanaw** [comment]
Hi @ArtRand

Thanks for your thorough explanations and for considering this idea. Yes, having a "ref_mod_strand" as an additional column or substitution of "ref_strand" would be helpful. Also, I do see the value of keeping a "mod_strand" to relate with the unaligned BAM. Thank you!

**Comment by ArtRand** [comment]
@santanaw Great, I opened a new issue to track this feature request. I expect it will be in the forthcoming version 0.1.11. Thanks for the input.
