### ISSUE TITLE
Extract mods option --exclude-bed (-v)

### ISSUE THREAD

**Issue by marcpaga** [nanoporetech/modkit#36]
In the `extract` subcommand there's the option to exclude regions based on a bed file. The argument can either be `--exclude-bed` or the short version `-v`. I find it a bit weird that this `-v` exists since `--include-bed` does not have a short argument. And the other short arguments are quite general options (number of threads, interval size and help). Maybe a copy-paste remain from another part of the code? 
Feel free to close this, since I could very well be wrong here and there's a good reason for this.

**Comment by ArtRand** [comment]
Hello @marcpaga,

The `-v` short option is partially an homage to [bedtools](https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html#v-reporting-the-absence-of-any-overlapping-features). If having short options for all options would be helpful to your workflow, I can look into adding those. Thanks for the input! 

A

**Comment by marcpaga** [comment]
Ah, I seem makes sense!
