### ISSUE TITLE
Question about cytosine count discrepancy in modified basecalling process

### ISSUE THREAD

**Issue by bayraktar1** [nanoporetech/modkit#37]
Hello,

I wanted to bring up a question regarding the cytosine count discrepancy that I encountered during the basecalling and modified basecalling process. I would appreciate any insights or clarification.

Here's a summary of the steps I followed:

1. I used the following command to perform basecalling:
`dorado basecaller dna_r9.4.1_e8_hac@v3.3 --modified-bases-models dna_r9.4.1_e8_fast@v3.4_5mCG@v0 pod5/ > calls.bam`

2. Next, I aligned the resulting BAM file using the dorado aligner with the following command:
`dorado aligner genome.fa calls.bam -t 16 > calls_aligned.bam`

3. I sorted the BAM file with samtools

4. Finally, I ran the modkit pileup command to process the aligned BAM file and generate a bed file:
`modkit pileup --filter-threshold 0.0 calls_aligned_sorted.bam dorado_methyl_no_filt.bed`

Now, here's the issue I encountered: The genome of the organism I sequenced contains a total of 19,505,736 cytosines (forward and reverse strands), out of which I expected 5,059,256 to be in a CG context (not necessarily methylated). However, the resulting bed file contains 11,365,547 cytosines.

If we basecall first and then check if bases in CG context are modified, wouldn't we then expect a count closer to 19 million cytosines found, regardless of them being methylated or not? 

I suspect that I might be misunderstanding the basecalling or modified basecalling process, and I would greatly appreciate any insights or explanations.

**Comment by bayraktar1** [comment]
Hello @ArtRand,

Thank you for your response and explanation.

I followed your recommendation and used the `--cpg` and `--ref` options during the bed file creation. This reduced the total number of cytosines in the bed file to 5M, which aligns with the expected count of CG sites in the genome. Do I understand correctly that the remaining 6M reads that were filtered out may indicate instances where there was a CG in the read but not in the reference, or potentially indels? It does seem like a relatively high number.

I would like to clarify that the reason I initially set `--filter-threshold 0.0` was to enable downstream analysis, where I perform my own filtering to determine methylated cytosines.

Furthermore, I have one final question. When the filtering is not applied, where does this number of 11M cytosines come from? Why would you not expect the CpG model to find all 19M cytosines? My understanding was that Dorado should detect and report all cytosines, regardless of their methylation status, and then determine if a given CpG site was methylated or not.

**Comment by ArtRand** [comment]
> Do I understand correctly that the remaining 6M reads that were filtered out may indicate instances where there was a CG in the read but not in the reference, or potentially indels? It does seem like a relatively high number.

Correct. It may seem like a high number but consider that as soon as a single read reports a CG (and base modification probability) at a location, it will get a row in the output table. Especially with `--filter-threshold 0.0` you will see all of the low-confidence base modification calls. 

>When the filtering is not applied, where does this number of 11M cytosines come from? Why would you not expect the CpG model to find all 19M cytosines?

Sorry, I should have been more clear. When using the CG model, dorado will only report on the CpGs in the reads. In this case you should see the 5M CpGs (plus the miscalls as we've discussed). I would not expect that you'll see the 19M because only 5M are CpG dinucleotides.

>My understanding was that Dorado should detect and report all cytosines, regardless of their methylation status, and then determine if a given CpG site was methylated or not.

This is not true. If you're using a CpG model, dorado will only report methylation status of CpGs in the reads. To report on all cytosines, you need to use the "all-context" model.

**Comment by bayraktar1** [comment]
Thank you for the clarification
