### ISSUE TITLE
binaries are not up-to-date

### ISSUE THREAD

**Issue by jayaprakash087** [nanoporetech/modkit#39]
I'm trying to install modkit v0.1.11 from the pre-compiled binaries. I realized from the `CHANGELOG.md` and `CARGO.toml` files that it was indeed still v0.1.10. Can you please update the binaries to v0.1.11?

**Comment by ArtRand** [comment]
Hello @jayaprakash087, 

If you download the pre-compiled artifact from [0.1.11](https://github.com/nanoporetech/modkit/releases/tag/v0.1.11) and run 
```
dist/modkit --version
mod_kit 0.1.11
```
the version according to the binary appears to be correct. However, somehow the tag to the repo is pointed at the wrong commit. I've updated the tag and now the source downloads will download the correct files. Thanks for noticing this and sorry about the confusion.
