### ISSUE TITLE
output different context (CG, CHG, CHH) in separate files

### ISSUE THREAD

**Issue by yusmiatiliau** [nanoporetech/modkit#41]
Hi,
Is there any plan to enable bed output separately for each context (CG, CHG, CHH) as in modbam2bed? I currently use Bedtools intersect, but it is quite slow and I have multiplexed samples, so it is taking a long time. I think it would save time if this can be done in modkit too. Thanks

**Comment by ArtRand** [comment]
Hello @yusmiatiliau, 

Allowing any motif in addition to `--cpg` is on the roadmap. This functionality would allow you to specify CHH and/or CHG motifs and the output would be as through you'd performed the `bedtools intersect` with the motif-BED. We may annotate the rows in such a way that would allow the output BED to be partitioned into multiple files per motif, but that specification hasn't been finalized yet. You may also consider using the `-sorted` bedtools intersect [option](https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html) it may make your procedure faster.

**Comment by yusmiatiliau** [comment]
Thanks @ArtRand, looking forward to it. And yes, adding -sorted does speed up significantly

**Comment by ArtRand** [comment]
@yusmiatiliau we have user-specified motifs enabled now, you can use `--motif CHH 0` for example. The output is still all a single file - and this will likely stay the case. However the motifs are annotated in the output file an [example is in the documentation](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#narrowing-output-to-specific-motifs). Please feel free to re-open this issue if you have any additional questions.

**Comment by vidsvur** [comment]
Hi,

I have been facing an issue with looking at methylation in al contexts (CHH, CHG, and CG), and I wanted to check to see if there is an error in how I've been approaching the issue.

I created pileup reads with 
```
~/modkit_v0.2.5/modkit pileup -k --combine-strands --cpg --ignore h  --ref myref.fasta my.bam ./pileup_cpg_edge_filter.bed

~/modkit_v0.2.5/modkit pileup -k --ignore h --motif CHG 0 --motif CHH 0 --ref myref.fasta my.bam ./pileup_chg_cgg_try5.bed
```

and then parsed the `./pileup_chg_cgg_try5.bed` file for CHH and CHG using grep, so now I have a directory like so:
```
-rw-r--r--  1 vvuruputoor ebpproject 1.1G Apr  3 21:52 pileup_chg_try5.bed
-rw-r--r--  1 vvuruputoor ebpproject 4.4G Apr  3 21:51 pileup_chh_try5.bed
-rw-r--r--  1 vvuruputoor ebpproject 732M Apr  3 20:14 pileup_cpg_try4.bed
```

Now, as a sanity check before plotting anything, I wanted to check the overall sites with a non-zero value for methylation frequency (which I presume I can take from the 11th column of the pileup bed file ACC to the docs):

```
-bash-4.2$ awk '{print $11}' pileup_chg_try5.bed | sort | uniq -c | head -5
5993484 0.00
      1 0.15
      1 0.21
      1 0.23
      1 0.26
-bash-4.2$ awk '{print $11}' pileup_chh_try5.bed | sort | uniq -c | head -5
22754659 0.00
      1 0.13
      1 0.18
      1 0.21
      1 0.22
-bash-4.2$ awk '{print $11}' pileup_cpg_try4.bed | sort | uniq -c | head -5
 126316 0.00
      2 0.14
      1 0.15
      1 0.16
      7 0.18
```

So, this looks as expected- we expect methylation freq at CG sites > CHG > CHH 
But- bear with me, as I think this may be where my logic may be wrong: The overall number of lines in the pileup beds are:
```
-bash-4.2$ wc -l *.bed
  12456556 pileup_chg_try5.bed
  53006858 pileup_chh_try5.bed
   8655606 pileup_cpg_try4.bed
```

And if you subtract the zero values from all of the pileup beds,
```
## CHG
12456556 - 5993484 = 6,463,072 
##CHH
53006858 - 22754659 = 30,252,199 
##CPG
8655606 - 126316 = 8,529,290 
```
which shows the overall % methylation freq is CHH > CG > CHG

Is CHH over-represented? And if so, can this file be filtered down to the expected number of methylated sites (one would expect CG > CHG > CHH)? 
Or am I generating the files incorrectly by any chance?
