### ISSUE TITLE
Error in --include-bed: "Improperly formatted BED line"

### ISSUE THREAD

**Issue by makise58** [nanoporetech/modkit#47]
Hi, 

I'm attempting `modkit pileup --include-bed`.

```
$ modkit --version
mod_kit 0.1.12
```

`$ modkit pileup input.bam output.bed --ref hg38.fa`
This worked.

But

`$ modkit pileup input.bam output.bed --ref hg38.fa  --include-bed target.bed`
This did not work.

```
> improperly formatted BED line chrX    55613399        55636192
> improperly formatted BED line chrX    71085850        71152454
> improperly formatted BED line chrX    71229623        71265146
> improperly formatted BED line chrX    71523103        71585892
> improperly formatted BED line chrX    72291637        72317187
> improperly formatted BED line chrX    77494879        77796233
> improperly formatted BED line chrX    101339446       101400796
> improperly formatted BED line chrX    129971106       130068071
> improperly formatted BED line chrX    148490616       149010663
> improperly formatted BED line chrX    154418632       154446516
> processed 0 BED lines
> attempting to sample 10042 reads
> Error! zero reads found in bam index
```

What is proper format of BED line?
Thanks.

**Comment by ArtRand** [comment]
Hello @makise58,

The `pileup` program needs to know the strand, so it requires fields 1-6 ([wiki](https://en.wikipedia.org/wiki/BED_(file_format))), you can make name anything and score 0, just to fill it out. I'll update the docs on this requirement.

**Comment by makise58** [comment]
@ArtRand 

It worked perfectly.
Thank you for your help!
