### ISSUE TITLE
Q: compared to modbam2bed?

### ISSUE THREAD

**Issue by sklages** [nanoporetech/modkit#5]
Just curious .. which one is the tool of choice when converting modified BAM file to `bedMethyl` format?
In our current workflows I use [modbam2bed](https://github.com/epi2me-labs/modbam2bed).
`modkit` seems to perform similar tasks .. 

What are the main differences?

**Comment by cjw85** [comment]
As noted in the modbam2bed README, it is now deprecated in preference of modkit. The former will not receive updates or ongoing support.
