### ISSUE TITLE
How to use the mod_qual in the modkit extract output?

### ISSUE THREAD

**Issue by sahuno** [nanoporetech/modkit#50]
Dear Developers,

Your tool has been very useful. Thanks for making it widely available to the scientific research community.
Context: I'm doing analysis at read level. For `modkit extract` done at CpG context,  2 consecutive rows gives information about 5mc & 5hmc at the column 11, mod_qual.

Que: If h=0.005859375 & m=0.001953125 at position chr1:146581135 does that automatically make Canonical prob (C) = 0.9921875 ? Which implies that site (chr1:146581135) is most likely is C.

do i have to do extra filtering to reveal the real identity of the genomic site (chr1:146581135)?

Thanks in advance
-S

```
> dt
                                read_id forward_read_position ref_position
1: 1f6c2b71-bb44-4f6f-a164-3ada21d8c7b2                 19290    146581135
2: 1f6c2b71-bb44-4f6f-a164-3ada21d8c7b2                 19290    146581135
3: 1f6c2b71-bb44-4f6f-a164-3ada21d8c7b2                 18593    146581827
4: 1f6c2b71-bb44-4f6f-a164-3ada21d8c7b2                 18593    146581827
5: 1f6c2b71-bb44-4f6f-a164-3ada21d8c7b2                 18481    146581939
6: 1f6c2b71-bb44-4f6f-a164-3ada21d8c7b2                 18481    146581939
7: 1f6c2b71-bb44-4f6f-a164-3ada21d8c7b2                 18215    146582203
8: 1f6c2b71-bb44-4f6f-a164-3ada21d8c7b2                 18215    146582203
9: 1f6c2b71-bb44-4f6f-a164-3ada21d8c7b2                 17843    146582575
   chrom mod_strand ref_strand ref_mod_strand fw_soft_clipped_start
1:  chr1          +          -              -                    32
2:  chr1          +          -              -                    32
3:  chr1          +          -              -                    32
4:  chr1          +          -              -                    32
5:  chr1          +          -              -                    32
6:  chr1          +          -              -                    32
7:  chr1          +          -              -                    32
8:  chr1          +          -              -                    32
9:  chr1          +          -              -                    32
   fw_soft_clipped_end read_length    mod_qual mod_code base_qual ref_kmer
1:                  11       19415 0.005859375        h        19    ACGTG
2:                  11       19415 0.001953125        m        19    ACGTG
3:                  11       19415 0.017578125        h        16    TCGGA
4:                  11       19415 0.005859375        m        16    TCGGA
5:                  11       19415 0.150390630        h        31    ACgtt
6:                  11       19415 0.009765625        m        31    ACgtt
7:                  11       19415 0.005859375        h        50    TCGGT
8:                  11       19415 0.001953125        m        50    TCGGT
9:                  11       19415 0.017578125        h        45    ACGtt
   query_kmer canonical_base modified_primary_base
1:      CACGT              C                     C
2:      CACGT              C                     C
3:      TCCGA              C                     C
4:      TCCGA              C                     C
5:      AACGT              C                     C
6:      AACGT              C                     C
7:      ACCGA              C                     C
8:      ACCGA              C                     C
9:      AACGT              C                     C
> 
```

**Comment by ArtRand** [comment]
Hello @sahuno 

Yes, you're correct that the canonical probability is one minus the sum of the modified probabilities. So in you're example position `146581135` is most likely a canonical C.

**Comment by sahuno** [comment]
@ArtRand your swift response amazes me. thanks for being generous with your and insight. 
one last clarification before i move to close. 

Que: so there's no need to apply filtering thresholds at read level? like the one you showed in aggregate reads methylation tables?
```
thresh_5mC = 0.9
thresh_5hmC = 0.9
thresh_C = 0.7

5mc, 5hmc, Can_C
0.75, 0.10, 0.15 - called canonical
0.15, 0.10, 0.75 - called failed
```

**Comment by ArtRand** [comment]
Hello @sahuno, 

If you want to get only the most confident calls from `modkit extract` I would recommend running `modkit sample-probs` on the modBAM first, this will give you the threshold values (I generally recommend using the 10 percentile threshold value). Then you can filter the calls, after calculating the canonical probability, to ones where the most probable call is >= the threshold. Currently, there is no way to filter these calls within `modkit extract`. It wouldn't be too hard to add it.

**Comment by sahuno** [comment]
Dear @ArtRand 
your suggestion was very neat. 
is there any way i could also catch the 10th percentile  threshold for modified bases (5mc & 5hmc)? like you did for the unmodified bases (C)?

```
$ modkit sample-probs -t 12 --percentiles 0.1 --out-dir outdir/D-A-1 --prefix "D-A-1" --hist --log-filepath D-A-1/D-A-1_log.txt D-A-1_5mCG_5hmCG_calls_sorted.bam

[sahuno-2  data]$ cat D-A-1_thresholds.tsv
 base  percentile  threshold 
 C     10          0.8496094 
```

**Comment by ArtRand** [comment]
Hello @sahuno, 

The two methods will give the same calls, yes. Obviously, `pileup` is better designed to aggregate the calls per genome position, but you could convert the extract table. It's a long thread, but https://github.com/nanoporetech/modkit/issues/46 goes over some this kind of thing.

**Comment by ArtRand** [comment]
@sahuno There is an option in `modkit extract`, `--read-calls` that will output the base modification _call_ at each position in the read as well as the probability of the call. Please feel free to re-open this issue if you have any questions.
