### ISSUE TITLE
Modkit with bams generated from fast5 and not pod5

### ISSUE THREAD

**Issue by assafgrw** [nanoporetech/modkit#51]
Hello,

There seems to be an issue with bam files originated from fast5 and not pod5, am I right?
Is there a way to solve this?

**Comment by ArtRand** [comment]
Hello @assafgrw,

ModBAMs generated from fast5-basecalled data should work, what error are you seeing? Could you paste some or all of the log (use the --log-filepath option).

**Comment by assafgrw** [comment]
Hi and thanks for prompt reply, there is no error but the results don't make sense. using the summary option I get very low modification numbers for results from fast5 data while results that make sense from data obtained from pod5 data.

Here are the contents of a log file:
[src/logging.rs::54][2023-09-14 13:17:19][DEBUG] command line: modkit summary /Data/NB_project/runs/bams/PBL_230723_all_hac_hg19_sorted.bam --log-filepath /Data/NB_project/runs/bams/pileup.log
[src/commands.rs::121][2023-09-14 13:17:19][INFO] sampling 10042 reads from BAM
[src/reads_sampler/mod.rs::41][2023-09-14 13:17:19][DEBUG] found BAM index, sampling reads in 1000000 base pair chunks
[src/reads_sampler/sampling_schedule.rs::127][2023-09-14 13:17:19][DEBUG] derived sampling schedule, sampling total 10094 reads from 93 contigs, 591 unmapped reads
[src/reads_sampler/sampling_schedule.rs::137][2023-09-14 13:17:19][DEBUG] schedule: SQ: 1, 796 reads SQ: 3, 733 reads SQ: 10, 667 reads SQ: 0, 665 reads SQ: 8, 524 reads SQ: 2, 494 reads SQ: 4, 480 reads SQ: 6, 480 reads SQ: 5, 432 reads SQ: 9, 402 reads SQ: 11, 382 reads SQ: 12, 331 reads SQ: 16, 318 reads SQ: 7, 296 reads SQ: 17, 266 reads SQ: 21, 246 reads SQ: 15, 237 reads SQ: 13, 233 reads SQ: 14, 228 reads SQ: 18, 202 reads SQ: 20, 193 reads SQ: 19, 157 reads SQ: 48, 136 reads SQ: 23, 132 reads SQ: 22, 128 reads SQ: 91, 70 reads SQ: 34, 31 reads SQ: 51, 29 reads SQ: 46, 21 reads SQ: 39, 14 reads SQ: 56, 12 reads SQ: 26, 10 reads SQ: 55, 9 reads SQ: 29, 9 reads SQ: 42, 9 reads SQ: 30, 9 reads SQ: 25, 8 reads SQ: 27, 8 reads SQ: 24, 8 reads SQ: 31, 7 reads SQ: 28, 5 reads SQ: 54, 5 reads SQ: 43, 4 reads SQ: 33, 4 reads SQ: 35, 4 reads SQ: 36, 4 reads SQ: 44, 3 reads SQ: 52, 3 reads SQ: 40, 3 reads SQ: 59, 3 reads SQ: 47, 3 reads SQ: 49, 2 reads SQ: 37, 2 reads SQ: 38, 2 reads SQ: 32, 2 reads SQ: 82, 2 reads SQ: 66, 2 reads SQ: 60, 2 reads SQ: 67, 2 reads SQ: 61, 1 reads SQ: 92, 1 reads SQ: 86, 1 reads SQ: 80, 1 reads SQ: 74, 1 reads SQ: 68, 1 reads SQ: 62, 1 reads SQ: 50, 1 reads SQ: 87, 1 reads SQ: 81, 1 reads SQ: 75, 1 reads SQ: 69, 1 reads SQ: 63, 1 reads SQ: 57, 1 reads SQ: 45, 1 reads SQ: 88, 1 reads SQ: 76, 1 reads SQ: 70, 1 reads SQ: 64, 1 reads SQ: 58, 1 reads SQ: 89, 1 reads SQ: 83, 1 reads SQ: 77, 1 reads SQ: 71, 1 reads SQ: 65, 1 reads SQ: 53, 1 reads SQ: 41, 1 reads SQ: 90, 1 reads SQ: 84, 1 reads SQ: 78, 1 reads SQ: 72, 1 reads SQ: 85, 1 reads SQ: 79, 1 reads SQ: 73, 1 reads 
[src/reads_sampler/mod.rs::80][2023-09-14 13:18:25][DEBUG] sampled 10362 mapped records, sampling unmapped records
[src/reads_sampler/mod.rs::103][2023-09-14 13:18:50][DEBUG] sampled 291498 unmapped records
[src/reads_sampler/mod.rs::110][2023-09-14 13:18:50][DEBUG] sampled 301860 records
[src/commands.rs::747][2023-09-14 13:18:50][INFO] calculating threshold at 10% percentile
[src/thresholds.rs::77][2023-09-14 13:18:50][DEBUG] calculating per base thresholds
[src/thresholds.rs::80][2023-09-14 13:20:08][DEBUG] probs per base took 77s
[src/thresholds.rs::97][2023-09-14 13:20:08][DEBUG] filter thresholds took 0s
[src/thresholds.rs::107][2023-09-14 13:20:08][INFO] calculated thresholds: C: 0.859375
[src/summarize.rs::234][2023-09-14 13:20:09][DEBUG] computing summary took 0s

**Comment by ArtRand** [comment]
Hello @assafgrw, 

Could you give me a little more detail about what doesn't make sense as well as the basecalling and base modification calling you're performing upstream?

**Comment by assafgrw** [comment]
I expect to get mC fraction of 0.5-0.7 as in all my samples, but i get very low mC fractions  (below 0.1) in all of these fast5 originated experiments . I am quite sure this is a modkit issue as both in IGV and modbam2bed I see normal mC levels.

**Comment by ArtRand** [comment]
@assafgrw,

It could be the pass threshold values that `modkit` uses. You could try running `modkit pileup ` with the `--no-filtering` flag. The pass threshold you're getting: 0.859375 is about what I expect, but is higher than what modbam2bed uses (and IGV, depending on the version you have IGV may not be giving you the same metric as pileup). For highest accuracy, we recommend using the on-the-fly threshold.

**Comment by assafgrw** [comment]
But how come that in very similar samples generated with data from pod5
files I get different results with the same threshold?
I am quite sure that there is something different in the bam files.

**Comment by ArtRand** [comment]
@assafgrw 

If you're seeing a difference in the base modification calls for a single sample when you use fast5 or pod5, that's an issue. Could you run that experiment and see? If the base modification calls are different (you could inspect them with `modkit extract`) then it's an upstream problem.

**Comment by assafgrw** [comment]
I dont have an experiment containing both pod5 and fast5 files but the results are very clear. Again, I have about 10 similar experiments about half has fast5 files and the other pod5. It is very clear that results are different for experiment of both file types. I think that you really should check this.

**Comment by ArtRand** [comment]
@assafgrw did you find out the source of the difference? Feel free to re-open this issue if you find that the processing in modkit is causing the problem.
