### ISSUE TITLE
Modkit and modbam2bed

### ISSUE THREAD

**Issue by rowanhowellGE** [nanoporetech/modkit#52]
Is the output of `modkit pileup --preset traditional` identical to modbam2bed? 

I understand a similar issue was raised here https://github.com/nanoporetech/modkit/issues/14 but seems to have gone silent for a few months. 

Thanks

**Comment by ArtRand** [comment]
Hello @rowanhowellGE, 

The output from `modkit` may be slightly different depending on the settings you use. The largest difference is `modkit` will estimate the passing confidence thresholds directly from your input data, whereas modbam2bed uses default values. If you specify the `--filter-threshold` to the same value used in modbam2bed, the results should be very close. As you may guess, to get the highest accuracy, we recommend estimating the pass threshold on-the-fly. Another difference is `modkit` will not output a row in the bedMethyl if there aren't any passing base modification calls at that position. Finally, the way modbam2bed counts "no call" reads is slightly different, but I believe this does not change the calculation of the fraction of modified bases.
