### ISSUE TITLE
modkit skipping reads

### ISSUE THREAD

**Issue by FraukeHuth** [nanoporetech/modkit#53]
Hello,

I have the issue of modkit skipping a certain number of reads for each of my samples, but the log file doesn't make it clear why they are being skipped.

For example, the command:
modkit pileup -r {reference-genome} --motif CG 0 --only-tabs {input.sample}  {output.sample}

gives me the bed file I want, but the coverage is very low (1 or 2 for each genomic coordinate). The log file informs me, that indeed some reads are being skipped.

In one sample (sample1) the log file says:
```
> calculated chunk size: 6, interval size 100000, processing 600000 positions concurrently
> attempting to sample 10042 reads
> Using filter threshold 0.8417969 for C.
> Threshold of 0.66171885 for base A is low. Consider increasing the filter-percentile or specifying a higher threshold.
> Done, processed 29439 rows. Processed ~22 reads and skipped ~150825 reads.
```

In sample2 it skips no reads and I get decent coverage:
```
> calculated chunk size: 6, interval size 100000, processing 600000 positions concurrently
> attempting to sample 10042 reads
> Using filter threshold 0.8144531 for C.
> Threshold of 0.6308594 for base A is low. Consider increasing the filter-percentile or specifying a higher threshold.
> Done, processed 86 rows. Processed ~74705 reads and skipped zero reads.

```
I tried to use:

`modkit pileup  --max-depth 2147483646 -r {reference-genome} --motif CG 0 --only-tabs {input.sample}  {output.sample}`

`modkit pileup  --sampling-frac 1.0 -r {reference-genome} --motif CG 0 --only-tabs {input.sample}  {output.sample}`

or

`modkit pileup  --force-allow-implicit -r {reference-genome} --motif CG 0 --only-tabs {input.sample}  {output.sample}`

to influence how many reads are processed, but the numbers stay the same (always 150825 skipped for sample1 and 0 skipped in sample2).

`modkit extract` and `modkit summary` behave in the same way. I would like to process all reads/as many reads as possible for each of my samples. Do you know what causes/influences this behavior and what I need to change?

**Comment by ArtRand** [comment]
Hello @FraukeHuth, 

There are a few reasons that reads will be skipped, so it's hard to enumerate them all. Records that are secondary or have zero length SEQ will be silently skipped. All other skipped reads should emit a debug line in the log, could you run pileup with the `--log-filepath` option?

**Comment by FraukeHuth** [comment]
Hello @ArtRand,

thank you for your answer. In the log file it said: `Bad Input: malformed MM delta list` for all the reads which weren't processed. Could you please explain to me what this means and possibly how I could fix it?

**Comment by ArtRand** [comment]
@FraukeHuth, 

Have you performed any trimming or other sequence-altering procedures? Sometimes that can cause this. It can also be caused by hard-clipping. Could you post a small modBAM that where `modkit` skips the reads?

**Comment by FraukeHuth** [comment]
@ArtRand 

Thank you for your time. Unfortunately, I haven't done the initial processing steps myself. I merely recieved the processed fastq files. I know that dorado was used as a basecaller. I included the bam header below; just in case it is helpful:

```
@HD	VN:1.6	SO:coordinate
@SQ	SN:puc19_ftz	LN:5769
@SQ	SN:pFMP233	LN:7596
@SQ	SN:pGP546	LN:7371
@SQ	SN:chrI	LN:230208
@SQ	SN:chrII	LN:813178
@SQ	SN:chrIII	LN:316616
@SQ	SN:chrIV	LN:1531916
@SQ	SN:chrV	LN:576869
@SQ	SN:chrVI	LN:270148
@SQ	SN:chrVII	LN:1090946
@SQ	SN:chrVIII	LN:562642
@SQ	SN:chrIX	LN:439885
@SQ	SN:chrX	LN:745666
@SQ	SN:chrXI	LN:666454
@SQ	SN:chrXII	LN:1078174
@SQ	SN:chrXIII	LN:924429
@SQ	SN:chrXIV	LN:784331
@SQ	SN:chrXV	LN:1091287
@SQ	SN:chrXVI	LN:948062
@SQ	SN:chrm	LN:85779
@PG	ID:minimap2	PN:minimap2	VN:2.17-r941	CL:minimap2 -ax map-ont -y --secondary=no /work/project/ext_012/fhuth/reference/edited_yeast.fasta /work/project/ext_012/fhuth/snakemake_output/realignment/oberbeckmann/symlinks/barcode04.fastq
```

I picked three example reads from the same bam file. The first two were skipped; the last one was processed by modkit without a problem. 

### The skipped reads:
`cd154aa2-5f3d-4665-9db0-5466a59dd67c	0	chrm	85537	60	60M1D52M1D14M1D78M	*	0	0	TAGTATAAATAAATAATATGAAAATAAAACTTAATAAATATATAAATATAGTCCGGCCCGCCCCCCGCGGCGGGCGGACCCCGAAGGAGTGAGGGACCCCTCCCTAATGGGAGGGGACCGAACCCCTTTTAAGAAGGAGTCCATATATATATATTAATAAAAAAAAGTAATATATATATATATATTGGAATAGTTATATTATTA	FLISSQILNGHJSMJLHSKOSSSLSLSKHGOMGSNLLGSSSGKKNMLLJLSLJSJJIIHHSSNF>HGB@ACBDB@:('&&%&&,///.-,('((42267=DA=;5JFGFDB>A=<97=>>>77;;BC@;0+<EEEMHSOHKIGFKKMSKSKSKFDFDEHIGMKSSLRSHFFMSLNNKSJJSJSSKRISSIJJHSKHSNGGIGIL	NM:i:3	ms:i:390	AS:i:390	nn:i:0	tp:A:P	cm:i:28	s1:i:188	s2:i:63	de:f:0.0145	rl:i:0	qs:i:12	du:f:1.0964	ns:i:5482	ts:i:10	mx:i:4	ch:i:1523	st:Z:2023-06-02T23:34:29.061+00:00	rn:i:48176	fn:Z:PAO84123_b320c893_395226da_3177.pod5	sm:f:97.1716	sd:f:27.9595	sv:Z:quantile	dx:i:0	MM:Z:A+a.,0,0,0,0,0,1,2,0,0,0,0,6,0,0,14,2,0,16,0,0,0,0,0,1,0,0,0,0,30,1,9,0,0;C+m.,0,1,0,4,7,0,1,3,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,3,0,0,6,0,1;	ML:B:C,191,65,106,95,13,148,121,122,87,95,41,150,32,91,36,17,19,171,172,214,20,193,22,15,18,48,218,80,45,24,153,15,34,32,19,15,50,255,15,255,150,255,255,255,16,179,234,255,34,31,23,20,21,25,26,255,19,15,13,21,22,17,45,12,204	RG:Z:395226dac2ef66005564626fdd2bae268dadb5c9_dna_r10.4.1_e8.2_400bps_sup@v4.2.0-6C5839AD runid=unknown barcode=barcode04`

`d347bf7c-0cfd-4442-8757-9cc38ddc4006	16	chrXVI	869245	60	3S321M2I82M3D27M1I4M1D405M3D79M1D221M1D1223M	*	0	0	AATCAGTCAATATCAACTTCTTCTCTTTCTCTTCTTGGACCTCTGAAGTTAGAACCTCTAGCGGCACCCCAATCAAGATCTGGTGCATCTTCTCTTCCATCACCTTGGAAATTGGAGCCTCTAGCACTACTCCAATCAACATCTGCACCTCCCCCTCTTCTTGTAGCTGGAACAGAAACGTAAACAGTTCTCTCATTCAATTTAGTACCGTTGAACTTCAGAACGGCGACCAAATCTGCTCTTTCTTTCAAAGTAACGAAAGCATTACCCTTTAATCTTGTTGGGTCTCTTAGATTCTTTGGCAAAACAACTTCTTCAACGACTTCTCAGGCTTAACTAAACCATCTTCAACCCAGGCTTGAACACCCTCTGGGGTAATATCCCATGGAATGTTGTTTATGACAGCCCATGGTGGAGCATCTGGAACAGGGTATTCCCTCCTTCTATCGGAAGAACCGCCCCCCAAAGCAGGGTCTAATCTAGATCTACCTCCAAAACTGCCACCAAAGCCGCCTGAACGCGTGTTATTGCTGTTGTTTTTAGCATGAGCCAATTCGGACAATGGAATAGTGTTTGCATTAGCGGTTTCAATAGGAATTGTGATCTTATTCAAATCGACATCTTCTTCAGCCCAAGATGAACCAAAGGTGTCATCATTTAAAAATGACGTAAGGTCCATCTTCTTTACGGTTTTCTTTGGTGGAGCCATGATGTGTCCTTTTTATTATGGAATTATTTTCCTAAAGACAGATGAAAGCTAATATAAACTCGAGTTTTATGATAATCCCGCTTATTGGTCTACTGATCTTCTCTAACTCTGTAGTTATATCTATCTCTTCTGCTTCTTCTGCTTTTCTTTAGCGATGCTGATTTCCGCAAAAAAATTTTCATTCCGTGGTGCGTGATCTGATGAGAAATAAAGCCAAAAGAAAAAAAGACAAGAAGACAAAAAGGTTGGGCGGCTAAGTAGCGCCAGGATATAAAAAGCAACATAGATTTCAGTACCCTATTATCCTGCCAAAATTTACTTTAAGAAGTCTCTATGAATATACAGGCTAAATTTGGAAACATGAGAAAGGAAAGATGAAGATACAAAGATTGCAAGCAGTCAAGAAGATTTAGGAAAAAAGGAAAAAGCAAAAAATTCGATTTTTATGACTTACAAACTAAATTGATATGTTCGAAATAATTTTGAGAAGCTGAGCTCAATCTGGTACTAATCACTTCAAGTTAGATGTGCAAAGAAAGAGAATAGCATAAATTCAAAACCAAAGGAAGTGCGAGGCATTACCCGCATATTATCGGGAAACAGAAGCCATGTTAGAGTGATTTCCAACAAATGGCCCTTTGCCAGAGATGGGCTCTGCAAAAGAATTGGAAGAAGAGAAGAAATCGCTTCACATTCCGTTTCGTTTCTGGGTCTAATTAAAGTAGTACGGTGTCAATTAGGTATGCTAGGTTTGCGAACTCATGGTTTAGACAGGTATGAACATTATATTCGTCGCCCGTCGGATTTTGGCAAACTTGAGCTGCAAGATTGGTTGAATCATAAGTCATTCCGAGTTTCCCCCAATTTATTAATTGATTCAAGCACCACACGTGAGTGGAATGAACCTGAGCTTTTTTATCAAAATACCGAGGATGAAACTTGGGTGAGACCTTGTGTAGGGCCAAAGCTAGAACCATCAATGATGATGCTCAGATATCACGATTCGAATATTGGTCAAATGCCTCAATTTTGTTATCCAATCTCAAGTCCGATAAATTTTAAACCAGTATTAAAATACATTTTGCAAGAACGTTCTGAACTGTCAGACGGCTTCCCTCAAAAGTATAACACACTAATAGGTAGTCTTTTTGATATTGATAAAAACCCAGAAACCTTAGATGATTCAGATATAGAAGCATTGGATGACATAGAAATGAGCAGTGACAGCGGTAATGTTAAAGAACCAAAAATTGAATTGCAGGCGCTGGAAGAAATCCAACAAAAGCATTTCAGTTTAATAGTATCCAACAATGGAATCTTTCAAACAGGTAGCACTTCAATAACATACATACAGTCTGGCATATCTGGCAGCATAGCTATAAAACCCAACAACGTTGCAATTTTAATATTACTCACTCAACCAAGTGGTCACTTATTGTCTATTTTACCGCTTGATGACGGTAAAGAGACATATTTGCTACAATATTGGAACCTGGGACAAAAAGGTCAGTGGAACATAATCAAGCACCAAAACGAGAAGCAGTTTGTTCTTATACATAAGGAACTAGGCATTTGCAAATTTTTTGAATTCCATTTACCATTTACTTTTCAATTAGTAAACAATTTAACATTGACCGATTCCGTGATTATGAACGGATC	&)/4;EBBKFGHJKSSHIJSHKGEEHGLGDHGFSGSIMSGSKSLQNJKIJNSJSS???DIFELSPJNSKSHHMJSQJSSHJJHMJJHJHSJKSQJSKKSFLNLFFCGA;;;;;C@42212,,,:ACCCGFIFKNOSMHKKSNGJKJQSSLIEC?7.---(''''''''*+/////ABCDDCC77544895+**+EGHHLHJSFIJGH655555SIKRSGHKJMJOMSISNLGKGSESSKEDFFMJJIGFHNHJRKJHJSPRSLGHLNIIIHKIKIILFHKJNLJLHJIGJFINHJIJJGHJJISSHSGIEEB:965&&%%&)(*+-01:@BCHKLISOSNSSSGJSPIMJKKKRSIHCDDEHPSKSHGGGGFSHIQJLIOKSNSKJISSFJKJQSAABA@ASJC))((234HSGOLSIFNA???=>=77530/''((&%&((''(47988:::>>??BOLLJNQJLRILLKJHDJGHHNNHSGHJPFGLH----->CCFSSJKSIISEGGFKGSGGLFILISKJSFGSKJGMJLIHSSJSLSHISNHJSHSSGSMKSJFKQSJJGSMGHSISSSFSGSFGIEOJIS@@@@@E?@>=5446-,,+++@CBCDBNGNKSSSGPSGSFCIGKIJSLHIHLINRN::>HOHLSJHMIPSKSSOHSJNHJSMKKKKGSMHSEGFENGGGFSMNSRNJSSIIGGKGKQMJIKHNLISKSHSOKMSMHHG?=.*))()(**++-++,((6DFGLPKKSHKHSSHSIJGOJPSOSGJQLJMJHHISGLQLNIJHPHSKGIHSLIIKMSOFGSILLILFLJKISLIFISKMFEJSNLESPHHGE=;))((+,1544KJSRGLHKJKIISHSJG*****FLSJKSLISSSSMIJJGFGHLNRILHHHHHJIDCFCCDCAA@@C0GGSPSJSSHGSGBFKJGFSGDSLJSKNKLLJSIKSOLHFFEABB;10//0566666B>>?SSHSSKEHSDBBDFDFBFEJJISSSJSSISKKNSGSKHHKIGSRJSSMLRHJNSCCEFSHKPSKGFHSNSSSSJSKLJSOSSMSSLLLIISSOSOSJNC9CDCQRSKFGCNLGIJMKOISLNJSIOSSMLJLHSJGSHLSSNSKGFC@0000*,;;HSPHGEFEC20+(&'()ASJJHKMKSSSSSHJJSSHSSHPKHHGNIHJSGJSISIGLMSSSIHSJLPFSKKPKSISSJSJHMFKSFGHIGJJKIOJPIJIMKHSPHILBBIHB;EMJHLMGGKNRSSSSGSKOJKKRNLLMSMILINESSJMGIGJGMKMMNJIISSSSLSKDSCACKSHSOSSPHSKHRHKSJSLPSIKHJNSHPL;;;;;SSJFHHSSSSSLSJIKSISKQMHGJKLIJJSHFCDGJ<<@GISSSSNSSOHHJSJIMHGOSPSGGGPGISOLJLMJGRPRIHKSKHJSGIDHSGGOMSJISSSSSSNGHSKSNSSMRLIMCBB<6555DEHDJHIJNSHGJSFGJIJSGSSLSSHFKISSSJJGMFSISKSLKHFMEPSJHEADCGOSSSLHSFABAABCDHMJHI;;:4422510014@AEKMNSFG@IJSNKSKJJPHIJGHFSSISNSSKSJGJSMSJHKGMGKSSKGSGFDEFEGL::9DCFHSHIOIGFEFDDCCDECCBBDCEHDEDCAAA@BCJDKMFEED>4<>CQGKFEDBBDCDHHCDDED==<0///::@@BCCDDJEKGDIKHDCDCDDDHKGDDDDEGHLFEIEEFBCDEFEDFECEDDBBBCBFDDHHHGJGIDICDCAAABBGFLJGGSPFEFJEFGKFEGGIHHGBAABCSGEFBBBBADCIFGFSHHDHKMFOOFGEIEEFEFDEJEEEGDDDFGM.+***+,,46=DFSHGJIHJSFFHCHDEDDDGGLJEISDODFFFEDDDDDCFDDCDDDINGSIHSHKIFJCBABBFEDEDEGGEDFEFFGHSSJIFFKJSSPIIRFKINNISPGJHIOSHSLIHNILMSFHSSMSSISJISFGIOJLKSHJSHHHSSGDENEGOJIGPHHKMIHSKKQNSSILISGJNSEEAAAAJHKISLHHMJIRKOIFECIDGHA==>?>111*****+SSGSKISKJKSQLGHKGKKMMSGSGIMGNJLISFSHIKKJGFGESSSHQQHESHJJEC>;;;8-7----6=AACBLILISISSKSMLIIGHPNOSLSMSSMSKSSOSJSSHLMMSSSIGISNSEHSJSSJISOSJILISSHKJHSHKMLOLSMMSSSHHSGDDC><+***)((*/1=@GGSSNIJSLNOKKGSIKLSMLLKSSJSSKSLISSSHSJSGSSHIGNHSKSGJJISJSJGMSSSSJINMSSSSJSMMHLLSSKSSFCNSKGKMSOISSSJGKGI	NM:i:19	ms:i:4630	AS:i:4630	nn:i:0	tp:A:P	cm:i:405	s1:i:2270	s2:i:0	de:f:0.0059	rl:i:0	qs:i:19	du:f:6.1298	ns:i:30649	ts:i:10	mx:i:4	ch:i:1762	st:Z:2023-06-03T03:01:45.751+00:00	rn:i:69896	fn:Z:PAO84123_b320c893_395226da_3467.pod5	sm:f:98.5652	sd:f:27.8603	sv:Z:quantile	dx:i:0	MM:Z:A+a.,0,0,0,0,0,0,0,6,0,0,1,1,0,0,7,0,18,13,0,1,3,13,0,0,0,0,0,0,1,0,0,2,2,9,2,1,4,4,0,6,27,0,0,0,8,4,1,0,0,13,22,24,5,4,0,0,0,5,2,1,0,0,0,0,1,12,1,15,0,4,6,9,1,2,0,37,0,28,0,8,4,0,0,0,2,5,0,0,0,0,0,5,0,0,0,0,1,0,20,4,8,0,0,0,0,0,0,27,8,0,1,4,0,0,0,1,25,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,2,1,1,6,3,0,0,2,0,0,1,0,0,0,1,3,20,0,1,1,0,1,0,4,2,0,1,1,0,3,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,4,0,0,19,0;C+m.,0,0,0,0,3,1,0,0,0,4,12,1,3,3,0,2,2,0,0,3,4,0,0,0,0,1,0,1,3,0,0,1,0,8,0,17,0,0,1,12,1,0,0,0,3,0,1,3,5,0,0,0,0,0,0,1,0,3,0,2,3,0,0,6,19,7,0,0,0,0,0,0,2,2,2,1,0,0,0,0,1,10,0,35,1,0,0,0,0,0,1,0,0,11,1,1,1,0,0,7,13,0,1,0,2,1,4,0,0,13,6,1,0,0,0,0,0,0,3,0,0,0,0,0,0,0,2,0,0,0,0,6,0,0,0,0,0,0,0,1,4,5,0,0,0,0,0,4,1,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1,0,0,0;	ML:B:C,87,168,132,25,45,32,84,36,86,37,24,21,12,14,17,48,17,12,160,27,14,47,16,124,184,139,108,32,18,20,22,12,15,13,62,65,184,142,13,20,14,67,109,25,14,12,18,15,14,43,16,17,163,63,205,80,110,14,12,35,99,183,14,28,51,45,36,37,75,13,14,72,27,81,14,13,160,12,72,125,214,42,83,43,84,22,17,252,231,26,20,27,17,154,26,18,50,50,21,13,124,103,143,230,153,72,169,64,13,43,15,93,103,85,163,27,227,221,41,209,62,44,87,14,12,12,14,76,48,138,163,126,23,17,17,12,65,68,155,13,16,12,37,20,23,33,18,14,18,13,24,59,26,18,18,214,34,15,27,105,13,78,25,39,26,14,20,76,19,16,12,86,18,16,18,12,12,12,26,23,22,249,113,64,116,12,14,15,14,15,17,12,15,17,13,15,16,16,13,14,15,24,20,69,52,14,14,12,15,14,28,20,16,19,23,16,13,14,25,12,28,20,12,15,12,12,28,17,26,18,18,13,15,14,21,25,15,13,16,149,12,14,36,255,255,18,14,13,20,18,22,21,16,22,41,17,14,255,20,19,25,14,19,127,13,16,16,13,26,16,23,26,16,23,25,15,255,20,255,13,22,255,249,14,17,128,70,13,255,18,25,15,12,16,255,255,180,255,73,33,19,22,49,48,34,16,16,14,17,12,34,24,63,68,16,16,18,14,34,27,32,12,20,12,13,18,27,23,24,12,15,12,12,254,220,246,20,17,12,19,20,17,21,44,33,37,12,29,16,14	RG:Z:395226dac2ef66005564626fdd2bae268dadb5c9_dna_r10.4.1_e8.2_400bps_sup@v4.2.0-31651226 runid=unknown barcode=barcode04`

### The processed read:
`f6121647-629d-4656-b87c-5968e2e5f26a	16	chrII	253171	60	2S651M2D32M	*	0	0	ATATATAGAGATCAAAAGCCAAAATTGCAGGCTCTTTGATAATCATTTTGAGAGGCCTATACAAAGTATTGATCAAAAAAGTTCTTGCATCAACTTCTCTATCGAGTTTATCCTGTTCAGTATAGTACCTGTCATCACCAGTTTCTTTTCTCAATTTCAAAGCACGGCGGTACAAAATATTATGGTGTTGTGTTTCAGGGAAGAAAAATGCCAACAAGATAAAAGTGGCAGCACTTAACCACATTAATAACCAAAATATGAATCGCCAATTTTTAGCATCGACCATAGCAGCGCCTAGTAAGGGAGCCAAGACTGGCGCAGCAACAGCACCGGCTGACCACATACCTAAAACGAGAGGAACCATTTCTGGTGAAATGATATCAGCCACTGTACCGCCACCAGTGGCCAACGATGGGCTGCACAGTATGCCACTGATGAAACGCATGACGATTAAACCGCCGATGTTATGCACAGTAGCACAACCAACTTGAAAGATCATGAAAAAAAATAAAGTCACCATGTACAGATTTAGACGGCCATAGCGTGCAGTTTCTGATAGCGGTGAAAAAATGATGGGACCTAGACCATAACCAAGAACATATAAAGAAAGATTTAATGTTGCCACTACATGACCAACGTGGAACTCTTCTTGAATATTCCTGGCCAGGTGTGTAAATGGAGGATC	/.222299;;AIHSSSKHMMPSSLSNSKSJGJLNOKFSSNJSPSHSKSSSSJLIFJHIESJJLSSHSSMMLHJSSJQIFCCSILIIGPJSHMISSLJIMIPHSMJMLFKISJSSSQIKGFMIMJHSSMSLKKJSSHIMIMJKOSKSLSSKLGLSIINHGSKPNSMSSILSSHLSSRFIEPIKIMHINEJGOHJMSMNLJDEGHOSFMFHKOSSMGKHLSKHMKSSMLJSISHSJGLNJHSLSSQHKSNIHKJSJSLOPKKIJOIJKRSHSSHJRNSIKGJLGGKGKSGIJSKKEEGGEKPLIGJKKOISEIRSFSGMIJISSKKIISKJSHOKLIJSGGSGISSHSLSLLHISKSPLLNJGNHIMHSHSSKOSHHISKMSIMHSHKSSLSHSNKLNQGHCDFFJFICEDDDHSHSHSHJSKJJSMSMFHSKNKISIJSLSIHHLSISHKHSKSSMJHILSJILSKISKHJHJGHLLHKNLSKOIKKSSHKKJGEINKHSJKSSSJFSGGJKHJGKPIGE8888888889AAAGSSHOJSJNJIGIPGSSSKJSJLSKLSH:;:@AA@DBCC432210//009999:SSKISRSMNLGLGSKHSSIKSNLLGCBBGGISHKSHQNLHLLMIJMKHQGE@?55BAACC>((''',*((((*10/001CCDBCDDDEEGLKFSFGFCF	NM:i:2	ms:i:1358	AS:i:1358	nn:i:0	tp:A:P	cm:i:119	s1:i:667	s2:i:0	de:f:0.0015	rl:i:0	qs:i:20	du:f:1.987	ns:i:9935	ts:i:10	mx:i:1	ch:i:2119	st:Z:2023-06-03T09:29:53.482+00:00	rn:i:93847	fn:Z:PAO84123_b320c893_395226da_3988.pod5	sm:f:112.399	sd:f:26.7697	sv:Z:quantile	dx:i:0	MM:Z:A+a.,0,1,2,4,0,2,0,0,0,3,4,0,0,0,0,0,4,0,1,6,0,0,0,10,6,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,6,0,0,0,0,0,49,1,0;C+m.,0,0,0,0,1,2,1,1,0,1,0,2,1,0,0,0,0,0,0,0,0,4,0,0,0,7,0,0,0,1,2,3,2,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,5,10,0,1,0,0,0,3;	ML:B:C,207,13,26,24,112,24,12,59,13,15,80,211,231,71,34,49,24,17,19,45,43,26,14,23,21,13,25,17,16,19,25,25,18,19,29,76,63,29,30,47,14,13,14,76,29,29,16,24,17,90,22,139,219,30,22,12,12,13,16,14,21,17,13,17,29,59,154,26,28,12,80,20,41,13,14,12,12,19,18,12,12,15,22,19,16,85,15,22,20,15,22,20,30,43,12,236,29,25,39,31,73,16,14,17,19,22,34,40,36,59,46,26,44,52,34,13,40,24,18,20,14,20,30,18,22,19,15,15,12,18,12,23,14	RG:Z:395226dac2ef66005564626fdd2bae268dadb5c9_dna_r10.4.1_e8.2_400bps_sup@v4.2.0-7B0FE457 runid=unknown barcode=barcode04`

A subset of the bam file is here: https://syncandshare.lrz.de/getlink/fi3FS2QpG4eEmwwfiaKyS3/subset.bam

Please let me know what you think.

**Comment by ArtRand** [comment]
Hello @FraukeHuth, 

I quickly took the two skipped reads and the processed read, put them into a SAM file and tried to use the [modified bases ](https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignedSegment.modified_bases) functionality in pysam (as an orthogonal test). Pysam also complains about the MM tag: [W::bam_next_basemod] MM tag refers to bases beyond sequence.

Is it possible that there was some trimming performed upstream (it's a common culprit)? Bottom line is that the MM tags and/or the sequences have been altered in some way that they can't be used. One remedy is, if you can get the original basecalls/modcalls, you can use `modkit repair` to fix the MM tags in the modBAM you have. You can find the docs [here](https://nanoporetech.github.io/modkit/intro_repair.html).

**Comment by FraukeHuth** [comment]
Modkit repair did work, but in this case only on bam files which had no MM or ML tag at all. Thank you for your help.
