### ISSUE TITLE
What is the best practice workflow after Dorado?

### ISSUE THREAD

**Issue by weishwu** [nanoporetech/modkit#56]
I've run modified base calling using `Dorado` which generated a BAM file with MM/ML tags. Since `Dorado` does not do trimming I had to convert BAM to Fastq and then ran `NanoFilt` to trim the reads. Now I have to use `modkit repair` to repair the MM/ML tags, but I'm not sure what the best route should be. I have two options:
1. Align the trimmed Fastq to the genome using Minimap2. This will generate an aligned BAM file, which can then be repaired. My concern with this approach is that some reads will be unrepairable because they may be split or somehow transformed after alignment.
2. Convert the trimmed Fastq to BAM and repair it. I kind of prefer this way so that I can be sure that all reads will be repaired, but I'm not sure which tool is the best for this conversion. I right now have all the original BAM tags in the read name line in the Fastq. `Picard FastqToSam` emits an error with this. I can cut the read names but wonder if I'm not using the right tools or not following the correct route.

**Comment by ArtRand** [comment]
Hello @weishwu,

Thanks for the thoughtful question. 

I believe the dorado team is adding trimming soon, so hopefully this advice will become obsolete soon. What I would recommend is trim the reads with NanoFilt if that's the tool you feel does the best job. Convert the trimmed FASTQ to uBAM (unaligned BAM, read-sorted) and repair with `modkit repair`. At this point you have a uBAM with trimmed reads and correct MM/ML tags. Then use `dorado aligner` to map the reads to your genome. You should get aligned reads with MM/ML tags in tact.

**Comment by weishwu** [comment]
Thanks!
