### ISSUE TITLE
modkit dmr pair with replicates

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#58]
Hello,

Very excited to use the DMR feature. I was wondering if it includes support for replicates? For example, let's say I have two treatments, cancer and control, but many samples for each. Can modkit account for pairing identical treatments?

**Comment by ArtRand** [comment]
Hello @Ge0rges,

The `modkit dmr` command is mostly designed for exploratory data analysis and currently there is no explicit support for replicates. However, you could use the tool, for example, to find differentially methylated regions between replicates and exclude them from downstream analysis. You could also combine the replicates together (the modBAMs) and run `modkit dmr` on the combined bedMethyls. The model in `modkit dmr` should account for increased variability if you combine your replicates together.
