### ISSUE TITLE
modkit dmr output

### ISSUE THREAD

**Issue by aganezov** [nanoporetech/modkit#61]
When running `modkit dmr pair` allow for output file to be in not-yet-existing directory.
Example (assumint `output` does not exist) 
```
modkit dmr pair -a normal.bed.gz -b target.bed.gz --regions-bed regions.bed -o output/output.bed
```
currently dies with `> Error! No such file or directory (os error 2)`
Proposed behavior -- create `output` directory and write program output into `output/output.bed`

**Comment by ArtRand** [comment]
Fixed in https://github.com/nanoporetech/modkit/releases/tag/v0.2.1.
