### ISSUE TITLE
Modkit Extract Query Kmer and Ref Kmer Size

### ISSUE THREAD

**Issue by andrewgalbraith21** [nanoporetech/modkit#62]
Hello, 

I am wondering if you have thought on introducing a parameter for modkit extract which designates the size of the kmer query. Something like --kmer-size [int before] [int after] with the default being --kmer-size 2 2 for a kmer of five. Looking at the source code this doesn't look too tricky to implement and I think would be helpful to have. Let me know your thoughts thank you!

All the best,
Andrew Galbraith

**Comment by ArtRand** [comment]
Hello @andrewgalbraith21,

Yes, that's something I can add, it may not make it into the next release - but likely the one following.

**Comment by andrewgalbraith21** [comment]
Hello @ArtRand perfect thanks so much!

**Comment by ArtRand** [comment]
@andrewgalbraith21 sorry about the delay, the [latest release](https://github.com/nanoporetech/modkit/releases/tag/v0.2.2) has this feature!

**Comment by andrewgalbraith21** [comment]
Hello @ArtRand! Awesome, this will streamline the analysis I have wanted to do. Thank you so much for adding the feature!
