### ISSUE TITLE
Matching of mods in modkit extract output to modkit pileup-hemi output

### ISSUE THREAD

**Issue by getopt** [nanoporetech/modkit#63]
Hello modkit developers,

Thank you for adding `modkit pileup-hemi` program. I am excited to start using it for research and wanted to understand settings that control which modification calls are represented in the output. 

For this, I run `modkit extract` (with default options to start with) and `modkit pileup-hemi`  on the example BAM file [duplex_modbam.sorted.bam](https://github.com/nanoporetech/modkit/blob/master/tests/resources/duplex_modbam.sorted.bam) in test/resources. Then I looked for events identified with `modkit extract` in `modkit pileup-hemi` output. I started with crosschecking modification events that have "mode_code" value "m" and value "+" in "ref_strand", "mod_strand" and "ref_mod_strand" in `modkit extract` output. There are 542 such modifications, and of them 94 are not represented in `modkit pileup-hemi` output when it is run with default options.

I then tested `modkit pileup-hemi` relaxing filtration with `--filter-percentile 0.00001`. Number of modifications not represented in `modkit pileup-hemi` output went down to 18. 

Below are plots of "m" v "h" modification qualities ("mod_qual" values) for the 542 mods, highlighting modifications not included in `pileup-hemi` outputs with orange color:

<img width="400" alt="image" src="https://github.com/nanoporetech/modkit/assets/6395469/4e3c5a16-5965-4482-a35c-7872f3246344">
<img width="400" alt="image" src="https://github.com/nanoporetech/modkit/assets/6395469/adf9f14d-a289-4e5b-b980-477610ea5c3c">

I would appreciate if someone could clarify how `--filter-percentile` works, as it seems that many of the modifications filtered out from the output of `pileup-hemi` due to `--filter-percentile` default setting seem to have fairly high mod_qual values. After relaxing to `--filter-percentile 0.00001` there remain 18 modifications filtered out. It would be helpful to get a hint for what other default options controls filtering of these modifications from `pileup-hemi` output. For example, one of them seems to have quite high mod_qual (orange point in the top left corner on the plot on the right). This is how that modification looks in `modkit extract` output:

```
5ed19b88-f9e2-40da-9296-931c81846371    8119    7698732 chr17   +       +       +       6       1       24561   0.025390625     h       90      gccgg   GCCGG   C       C       false
5ed19b88-f9e2-40da-9296-931c81846371    8119    7698732 chr17   +       +       +       6       1       24561   0.9746094       m       90      gccgg   GCCGG   C       C       false
```
 
Thank you in advance!

**Comment by ArtRand** [comment]
Hello @getopt were you able to get your hands on some duplex modification data? You can perform duplex base modification calling in [dorado now](https://github.com/nanoporetech/dorado/?tab=readme-ov-file#modified-basecalling). Feel free to re-open this issue if you have any problems.
