### ISSUE TITLE
trimmed.bam required for modkit repair

### ISSUE THREAD

**Issue by Flower9618** [nanoporetech/modkit#66]
Hi, Thank you so much for sharing this useful tool.

Is the trimmed.bam generate after mapping to the reference? or it does not need to a coordinate in reference.

**Comment by ArtRand** [comment]
Hello @Flower9618 ,

I'm going to assume you're referring to the [documentation](https://nanoporetech.github.io/modkit/intro_repair.html) example. The trimmed reads (in BAM format) can be aligned or unaligned, as long as they are sorted by read name. I recommend using `samtools sort -n` for both the "donor" and "acceptor" files to be sure you get the same ordering rules for both files.

**Comment by ArtRand** [comment]
@Flower9618 , 

Let me know if you have additional questions about using `modkit repair`.
