### ISSUE TITLE
How to get only CpG sites from modkit extract output 

### ISSUE THREAD

**Issue by weishwu** [nanoporetech/modkit#67]
The output of `modkit extract` includes non-CpG C-methylation, such as:
```
read_id	forward_read_position	ref_position	chrom	mod_strand	ref_strand	ref_mod_stranfw_soft_clipped_start	fw_soft_clipped_end	read_length	mod_qual	mod_code	base_qual	ref_kmer	query_kmer	canonical_base	modified_primary_base	inferred
a767616d-8e87-4a75-bea3-ad9e8612d62f	1807	10423	chr1	+	+	+	1362	0	16015	0.9824219	m	38	CCCTA	CCCGT	C	C	false
```
The reference context sequence is CCCTA. There is no CpG here. I guess I can use the `ref_kmer` column to select only the ones containing CG, but is there an easier way to tease out the CpG sites only?

**Comment by ArtRand** [comment]
Hello @weishwu,

Probably the easiest thing is to use `modkit motif-bed <ref.fasta> CG 0` to generate a BED file of stranded CG positions, then pass that file to `modkit extract --include-bed <cg_0.bed>`.

**Comment by weishwu** [comment]
@ArtRand Thanks! Will you consider adding the functionality to `modkit extract` for CpG-only output? It seems to be an option in `modkit pileup`.

**Comment by ArtRand** [comment]
@weishwu , yes we can add that.

**Comment by weishwu** [comment]
@ArtRand Thanks!

**Comment by ArtRand** [comment]
Just keeping this open to track the work, should be out in 0.2.3.

**Comment by ArtRand** [comment]
This feature was added in [0.2.3](https://github.com/nanoporetech/modkit/releases/tag/v0.2.3)
