### ISSUE TITLE
Issue with remora models/dorado

### ISSUE THREAD

**Issue by jorisbalc** [nanoporetech/modkit#69]
Are there known issues on modkit not working as intended on .bam files acquired via dorado+remora models? I recently trained a brand new remora model and basecalled it with the newest version of dorado. While this used to work previously, none of the commands seem to be working for me. I abbreviated the modification as 5caC, and it shows up just fine on the same files used in different tools such as IGV. Did I miss something? 

`modkit summary can_calls_dorado.bam`

```
> sampling 10042 reads from BAM
[00:00:00] ----------------------------------------       0/1       contigs
[00:00:00] #---------------------------------------       5/727     records samp[00:00:00] #---------------------------------------      10/727     records sampled> modbase info empty!
[00:00:00] ####------------------------------------      68/727     records sampled> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!
[00:00:00] #######---------------------------------     122/727     records sampled> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!
[00:00:00] ############----------------------------     213/727     records sampled> modbase info empty!
> modbase info empty!
> modbase info empty!
[00:00:00] ################------------------------     279/727     records sampled> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!
> modbase info empty!

```
The data is aligned to a reference and basecalled with 400bps_sup_v4.2.0 model and the trained remora model via --modified-bases-models argument. As I said before it opens just fine in IGV and shows the correct modifications. What could be the cause of this? This is using the latest modkit version.

**Comment by ArtRand** [comment]
@jorisbalc could you show me an example of the MM tag your BAM has (modkit is finicky about the codes you use). I'm worried that the code your using for carboxy cytosine may be causing a  problem. The next version of modkit will be a lot more flexible to these codes (and allow chEBI [codes](https://nanoporetech.github.io/modkit/limitations.html)).

This error message means that there aren't any probabilities found in the record, i.e. the MM and ML tags are present but empty. The logging should be debug-level instead of error-level. I'll release a release candidate with the logging fix asap.

**Comment by jorisbalc** [comment]
This is a singular read from the .bam. As far as I understand it seems fine?

```
d7a58be7-c253-402c-8c53-2389565ade2f	16	JB0001.0	2067999	60	50S289M68S	*	0	0	GACGTATCGCTAAGGTTAACAGACGACTACAAACGGATCTCACAGCACCTAGCATGATATTGCTCGAGTATTAAGGTTTTCAGTTCCGCTTCTTTTAAACCGCCCTGTTTATCGACAGGGGTAAAGAACACCGGACTTTGCCAGCTAATTTCGCGTTTAATGAATTCGTAGCGCGGCACCTGCGACACCGCCGCACGGTTAACCAGCTCCAGCCGGGAGAAAATCACCTGGGTGGTGGTGGTGCCGATATCGATACCGACGCTCAATAGCTGGCGAGTGTTCACGATTGTGCCTCCGCTTCGGTTTTAGTCGCGGTCGCGTCTTCTTTTGGCACCAGCAGGTGCTGTCGATTCCGTTTGTAGTCGTCTGTTTAACCTTAGCAATACGTAACTGAACGAAGTAGTCAT	$',)((((666ISHI00;<<<<=<>@:932310---*))*+IIJSSHMGESLLSGNIGSHMBBCBBOHKFHKHQKKJJMLHNSSKNLJIKHHCFLDJKDFGQKHHMSLJKGKSSIHKNLLKIHSMIPHLCCCCBIFSJMHGCDDDELKHSKJSILPRKKSIKSJKKGSSLJMPJKIMSKIQHOGB==;+*+*)**)../12>?@GGCDC<:<<>CGINLSIKJHSFKHESJISKSLOSGHGIISQHSLKJEIHPJJJQJSGKLGIFLHMJRSKIIKSKLQSSSEDCCDIKJIHNKOKIABDHGKKFIHKFKIGLHJKDCCIIKILMKIKSSJGNJISIGIJLSKB>??@DBAC2++6JHGGDDGIJHJLHHKSFKKIJLSJSSJPCC:9999=B-,*)&$#$$$$##	qs:i:19	du:f:1.9916	ns:i:9958	ts:i:10	mx:i:1	ch:i:303	st:Z:2023-06-15T22:39:56.658+00:00	rn:i:57864	fn:Z:FAW87775_skip__12b2e234_654d9491_19.pod5	sm:f:81.7839	sd:f:25.6375	sv:Z:quantile	dx:i:0	RG:Z:654d949156458929eb0d88decfead14747d14885_dna_r10.4.1_e8.2_400bps_sup@v4.2.0	MM:Z:C+c?,2,1,2,2,0,7,0,1,0,2,0,2,2,3,0,0,0,13,3,0,0,0,2,0,1,1,0,3,5,1,0,4,5,0,3,0;	ML:B:C,36,46,45,60,92,43,78,27,41,28,13,58,21,58,37,55,52,34,70,84,189,186,28,171,42,19,22,29,77,15,16,37,56,37,11,30	NM:i:0	ms:i:578	AS:i:578	nn:i:0	de:f:0	tp:A:P	cm:i:51	s1:i:289	s2:i:0	MD:Z:289	rl:i:0
```

**Comment by ArtRand** [comment]
Hello @jorisbalc, 

The released versions of `modkit` are picky about what codes you have. The `summary` function specifically won't accept the `c` code (I appreciate it's in the spec, but it's a limitation we're removing very soon). 

In the mean time run
```
modkit adjust-mods <in.bam> <out.bam> --convert c C
```
this command converts the `C+c?` tags into `C+C?` tags (`C` means "any mod" for cytosine). Then use `modkit summary` on the adjusted bam. 

You can use the [release candidate](https://github.com/nanoporetech/modkit/releases/tag/v0.2.2-rc1), it contains a fix that changes the log level from error to debug when a record with empty probabilities is encountered.

I'll be sure to ping this thread then the release is out and you can test it with the original modBAMs.

**Comment by jorisbalc** [comment]
Okay, I understand. What about the "modbase info empty!" error I get even when using C+m tags? What could cause this

**Comment by ArtRand** [comment]
Hello @jorisbalc,

With the release candidate, the record name is logged with the debug line, e.g. 

```
... 068ce426-129e-4870-bd34-16cd78edaa43 modbase info empty
```

This message is indicating that there are MM/ML tags, but no probabilities present. You can produce a modBAM like this with the data in the [test directory](https://github.com/nanoporetech/modkit/tree/master/tests/resources)

```
modkit adjust-mods \
  tests/resources/bc_anchored_10_reads.sorted.bam - \
  --convert h m \ # moves the prob from 5hmC to 5mC
  | modkit adjust-mods - - --ignore m \ # removes the 5mC prob
  | modkit summary stdin --log-filepath modkit_summary.log
```

If you pass a file path to `--log-filepath` you can find the record names and inspect them in the modBAM. I imagine they'll be something like `MM:Z:C+m?;      ML:B:C`. If not, let me know.

**Comment by ArtRand** [comment]
@jorisbalc  The [latest release ](https://github.com/nanoporetech/modkit/releases/tag/v0.2.2) no longer requires you to convert the `c` code to `C`. You should be able to use the BAM as-is.

**Comment by ArtRand** [comment]
@jorisbalc ,

Let me know if you have any additional issues.

**Comment by steven-solar** [comment]
I'm having a similar issue, and my modbam tags look like
```
Mm:Z:C+m?,2,1,3,0,12,16,3,11,3,6,6,2,3,11,9,1,...
Ml:B:C,57,3,255,252,250,252,91,4,250,88,242,255,...
```
not sure what could be causing this, as I think these tags look correct
