### ISSUE TITLE
modkit settings for rerio flip-flop modified base models

### ISSUE THREAD

**Issue by Yijun-Tian** [nanoporetech/modkit#7]
Hello,
Could modkit be used to summarize the mod_mapping BAM file generated from deprecated rerio modified base model, such as this guy:
res_dna_r941_min_modbases-all-context_v001.cfg? I have run a test on a negative sample but didn't expect the 6mA percentage will 15%.
```
modkit summary -t32 RWPE-1_5mC_6mA_nct/mod_mappings.adjusted.sorted.bam
> sampling 10042 reads from BAM
> calculating threshold at 10% percentile
> calculated thresholds: A: 0.5136719C: 0.5175781
> this output format will not be default in the next version, the table output (set with --table) will become default and this format will require the --tsv option
mod_bases	A,C
count_reads_A	8772
count_reads_C	8772
A_calls_unmodified	14606843
A_frac_unmodified	0.8461740726279702
A_filtered_unmodified	1544135
A_calls_modified_a	2655377
A_frac_modified_a	**0.1538259273720298**
A_filtered_modified_a	333031
A_total_mod_calls	17262220
A_total_filtered_mod_calls	1877166
C_calls_unmodified	6990544
C_frac_unmodified	0.5479038391510863
C_filtered_unmodified	795181
C_calls_modified_m	5768162
C_frac_modified_m	0.4520961608489137
C_filtered_modified_m	364560
C_total_mod_calls	12758706
C_total_filtered_mod_calls	1159741
total_reads_used	8772
```
Thanks,

**Comment by ArtRand** [comment]
Hello @Yijun-Tian,

In principal, yes modkit can be used for this purpose. It looks like the estimated thresholds are very low (~0.51), perhaps modkit isn't sampling enough reads to estimate the value. Could you run with `--log-filepath <log_file.txt>` and see how many reads it actually gets? You may consider running with `--sampling-frac 1.0` which will make `modkit` sample all of the reads when calculating the threshold _and_ generating the summary. You could also run `modkit sample-probs <bam> --percentiles 0.1,0.15,0.2,0.3 --sampling-frac 1.0` to get an idea of what filter percentile is suitable for this model. Let me know how it goes.

**Comment by Yijun-Tian** [comment]
Hi @ArtRand,

The thresholds are indeed wired. Here is the estimates for all reads:

```
modkit summary --sampling-frac 1.0 --log-filepath log.RWPE-1.txt -t32 RWPE-1_5mC_6mA_nct/mod_mappings.adjusted.sorted.bam
> sampling 100% of reads
> calculating threshold at 10% percentile
> calculated thresholds: C: 0.5175781A: 0.5097656
> this output format will not be default in the next version, the table output (set with --table) will become default and this format will require the --tsv option
mod_bases	C,A
count_reads_C	79206
count_reads_A	79211
C_calls_modified_m	57024021
C_frac_modified_m	0.48101209989945515
C_filtered_modified_m	3334654
C_calls_unmodified	61526055
C_frac_unmodified	0.5189879001005449
C_filtered_unmodified	7170289
C_total_mod_calls	118550076
C_total_filtered_mod_calls	10504943
A_calls_modified_a	22958833
A_frac_modified_a	0.1598939846211358
A_filtered_modified_a	1924504
A_calls_unmodified	120629014
A_frac_unmodified	0.8401060153788642
A_filtered_unmodified	9063562
A_total_mod_calls	143587847
A_total_filtered_mod_calls	10988066
total_reads_used	79212
```

And here is the sample-probs output:
```
modkit sample-probs --sampling-frac 1.0 --percentiles 0.1,0.15,0.2,0.3 -t32 RWPE-1_5mC_6mA_nct/mod_mappings.adjusted.sorted.bam
> sampling 100% of reads

C
q       p
0.10	0.518
0.15	0.518
0.20	0.525
0.30	0.549

A
q	p
0.10	0.510
0.15	0.521
0.20	0.521
0.30	0.525
```
[log.RWPE-1.txt](https://github.com/nanoporetech/modkit/files/11385212/log.RWPE-1.txt)

The calculation of ML probability should be correct. I did some calculation with bash grep and excel and they are roughly the same. Maybe it's a model issue?

**Comment by ArtRand** [comment]
One other thing to keep in mind is that `modkit summary` produces read-level metrics, so there can be 6mA calls which are in inserts or mismatches. If you have relatively eaven coverage you may get a better estimate of 6mA levels using pileup (followed by a `bedtools intersect`) as demonstrated [here](https://github.com/nanoporetech/modkit/issues/2#issuecomment-1507909590). 

Also, we're hard at work to produce a 6mA model for r10 that should be a lot better.

**Comment by Yijun-Tian** [comment]
Hi Rand,
Does the read level metrics mean that 15% of the read tested have at least 1 6mA in it? As my sample is from human genome, I expect the DNA m6A modification should be nearly zero percent. Also for all context 5mC, the modified percent is too high... Maybe it's a bad idea to use the flip-flop model in my scenario. 
About the CNN model for 6mA, is there a reason for not using R9 flow cell? In my R9.4.1 BAM, seems the the sequence between two modified bases shows a lot of deletion? Is train R9 model for all context modification, especially with high per read modifications, a bad idea?
Thanks for the insight!
