### ISSUE TITLE
Does pileup work with 6mA

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#70]
Dorado now supports 6mA calling. Does pileup support this already?

**Comment by ArtRand** [comment]
@Ge0rges Yes it does. In fact there is some demo/test data in the repo called [ecoli_reg.sorted.bam](https://github.com/nanoporetech/modkit/blob/master/tests/resources/ecoli_reg.sorted.bam). You'll have to run `modkit update-tags --mode implicit` first (it's test data and the MM tag is `A+a`) or pass `--force-allow-implicit`. It's a small dataset, but you'll get the idea.
