### ISSUE TITLE
`modkit dmr multi` parametres are confusing

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#71]
In the `dmr multi` [docs](https://nanoporetech.github.io/modkit/advanced_usage.html) it should be specified that the `-s` and `-i` flags should be repeated. `-s <SAMPLES> <SAMPLES>` implies the only one `-s` flag should be specified so change that to `-s <SAMPLE_PATH> <SAMPLE_NAME`. And add description text.

**Comment by ArtRand** [comment]
@Ge0rges I have added an [example command](https://nanoporetech.github.io/modkit/intro_dmr.html#running-multiple-samples) to the documentation.
