### ISSUE TITLE
`modkit dmr -o` should either create the output folder it doesn't exist or be clearer

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#73]
Currently if the output folder doesn't exist the command fails. It would be elegant to create the folder. It would be the bare minimum for the error to be descriptive rather than just `os error: folder does not exist` without specifying which folder we are talking about.

**Comment by ArtRand** [comment]
Hello @Ge0rges 

As of version [0.2.1](https://github.com/nanoporetech/modkit/releases/tag/v0.2.1) when the output directory for `modkit dmr` doesn't exist, it should attempt to create it. You should see a log like like:
```
> creating output directory /tmp/scratch/foo/bar
```

Let me know if this isn't the case in your hands.

**Comment by Ge0rges** [comment]
Ah i was on the older version, apologies.
