### ISSUE TITLE
Traditional is confusing.

### ISSUE THREAD

**Issue by mattloose** [nanoporetech/modkit#75]
https://github.com/nanoporetech/modkit/blob/acb9c117acc669bdc1ba47fb5637af4116219371/README.md?plain=1#L49-L67

Modkit is clearly powerful, but somewhat confusing.

My reading of this section of the readme is that traditional will output either C or 5mC and so a 5hmC call will be described as a C in the output?

Is that correct? 

If so - it's confusing as I would expect "traditional" to label either 5mC or 5hmC as methylated. 

Instead it appears that --combine-mods gives the behaviour I woudl expect to observe from "traditional".

**Comment by ArtRand** [comment]
Hello @mattloose,

`modkit` has two ways to reduce the number of base modifications reported in the output: 

1. Removing the probability of one or more classes prior to making a base modification call. Indicated by the `--ignore <mod_code>` option.
2. Combining all non-canonical calls. Indicated by the `--combine-mods` flag.

The differences are described in the [documentation](https://nanoporetech.github.io/modkit/collapse.html). We made the choice to make the `traditional` preset remove the base modification probability prior to making a base modification call. The difference is when the probabilities are transformed the next most likely state will be called, so for example:

p_m = 0.1
p_C = 0.3 // canonical
p_h = 0.6 

Normally the call would be `h` (5hmC), when the probability of 5hmC is redistributed over the other classes the resultant probabilities become:

p_m = 0.4
p_C = 0.6 // canonical

So the call would be canonical. On the other hand, when the `--combine-mods` flag is used, the call would be 5hmC, but all non-canonical calls would be summed together.

In practice, we've found the difference to be very small. 

Also you brought my attention to a typo, sorry about that 🤦 .

**Comment by mattloose** [comment]
Thanks for the explanation.

This is not doing what I expect. In "traditional" methylation calling, you would anticipate miscalling 5hmC as 5mC, not as shown here which results in a modified base being called as canonical. I would interpret traditional as being what is the probability a site is methylated (regardless of methylation type) versus not being methylated.

In this example, the site ends up being called as not methylated when - in fact - it is.

So I am clear - the traditional output for the following probabilities:

p_m = 0.3
p_C = 0.1
p_h = 0.6

would be:
p_m = 0.6
p_C = 0.4

and so for this site you would call 5mC?

**Comment by ArtRand** [comment]
@mattloose 
> So I am clear - the traditional output for the following probabilities:
 p_m = 0.3
 p_C = 0.1
 p_h = 0.6
 would be:
 p_m = 0.6
 p_C = 0.4
 and so for this site you would call 5mC?

Yes, that's correct. I chose my example to demonstrate how the two methods could arrive at different answers. In our experiments [comparing](https://labs.epi2me.io/how-to-mod/) to BS-seq, using `--combine-mods` vs `--ignore h` has a very small effect suggesting the overwhelming majority of the time the second most likely class to 5hmC is 5mC*. The choice of the term `traditional` applies to the output - perhaps not the method.



`*` Aside, I actually have some thoughts as to how consistent 5hmC really is in some of these samples and the difference could be indicative of that.

**Comment by mattloose** [comment]
Ok. But neither method gives me what I need - which is given a file with calls for 5mC and 5hmC I wish for all methylated sites (either 5hmC or 5mC) to be labelled as methylated and all canonical sites to be labelled as canonical. 

What I don't expect is for sites which are 5hmC to be distributed between canonical and methylated. I suppose
I don't follow why any of the probability that a base is 5hmC is assigned to the canonical state?

The reason I'm raising this is that I have seen it make a difference in analysis - and a significant difference at times.

**Comment by ArtRand** [comment]
@mattloose 
>given a file with calls for 5mC and 5hmC I wish for all methylated sites (either 5hmC or 5mC) to be labelled as methylated and all canonical sites to be labelled as canonical.

This is what `--combine-mods` will do. So for example you could:
```
modkit pileup ${in_bam} ${out_bed} --combine-mods [--cpg --ref ${ref}] [--combine-strands]
```

This will do exactly what you want.

**Comment by mattloose** [comment]
Thanks @ArtRand - appreciated.
