### ISSUE TITLE
Implicit-canonical mode

### ISSUE THREAD

**Issue by NickNCL** [nanoporetech/modkit#76]
Hi,

I wondered if the documentation could be updated to provide a better explanation of implicit-canonical mode? I couldn't get a good understanding from the documentation and couldn't find an explanation elsewhere (e.g. specifications for modbam format flags etc.)

I'm hoping to look at all context base modifications, particularly m6A (Dam methylation). I basecalled using the res_dna_r941_min_modbases-all-context_v001 model from guppy, which seems to have produced a bam file not compatible with modkit by default. In the log file, modkit is skipping all reads because of "unallowed-mod" with the option to ignore this flag with "--force-allow-implicit" option. 

I'm not sure if I'd be discarding information about modification probabilities by using --force-allow-implicit option. Or is it the case that modification probabilities are not available for modifications other than CpG? Would there be any measure of certainty in modification frequency when using --force-allow-implicit?

Any help would be much appreciated

**Comment by ArtRand** [comment]
Hello @NickNCL,

There is a description of the "modes" in section 1.7 of [this document](https://samtools.github.io/hts-specs/SAMtags.pdf).

Briefly, taking adenine modifications as an example:

1. `A+a.` => "probability of modification", adenines without base modification probabilities are assumed to be canonical.
2. `A+a?` => "ambiguous", no information regarding the base modification state adenines without base modification probabilities can be made
3. `A+a` => (notice there is no `.` or `?`), "implicit probability of modification". This is the old tag version. Modkit will prevent you from using a BAM with this form of the tag without the --force-allow-implicit` (as you discovered). Same as (1).

There are a couple things you can try:
1. Use `modkit update-tags --mode implicit` to update the mode tag.
2. Use `modkit adjust-mods --convert <old_code> a`

If you perform (1) you shouldn't need the `--force-allow-implicit` option. If your MM tags have an out-of-specification modification code such as `Z` or `Y` you may need to convert the code with (2). However, if you use the latest version of modkit (0.2.2) you shouldn't need to perform (2). 

Could you show me a single BAM record's MM tags?

**Comment by NickNCL** [comment]
Many thanks for all the info, this helped a lot

So from my understanding modkit will interpret the tags A+a. and A+a as essentially the same when using `--force-allow-implicit`? I guess that `modkit update-tags --mode implicit` will simply convert all my A+a type tags to A+a. ?

In which case is there any advantage to using `modkit update-tags --mode implicit` over the `--force-allow-implicit` option?

**Comment by ArtRand** [comment]
Hello @NickNCL 

> So from my understanding modkit will interpret the tags A+a. and A+a as essentially the same when using --force-allow-implicit? 

Correct.

> I guess that modkit update-tags --mode implicit will simply convert all my A+a type tags to A+a.

Also correct. 

> In which case is there any advantage to using modkit update-tags --mode implicit over the --force-allow-implicit option?

Depending on what you're doing, it may come back to bite you if you always pass this flag. For example, if you end up using a CG-motif model, missing base modification probabilities have a different meaning and those cytosines will be mis-interpreted as canonical. 

From the BAM record you've sent it looks like you have normal modification codes: A+a and C+m. Are you using an all-context A and and all-context C model? You can always run `modkit summary` to get a quick view into what's in the BAM file.

**Comment by ArtRand** [comment]
@NickNCL please feel free to re-open this issue if you have any problems with the implicit mode.
