### ISSUE TITLE
Nicer error when `--regions-bed` file not found

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/modkit#78]
Currently this just prints an OS error, it would be nice if the error could be more descriptive.

**Comment by ArtRand** [comment]
@Ge0rges Which command are you running? I thought I chased down all of the potential missing file places and added contextual information - I must have missed one.

**Comment by Ge0rges** [comment]
`mdr multi`

**Comment by ArtRand** [comment]
Ok, I'll make sure it's fixed up on the next release - should be a quicker turn around this time.
