### ISSUE TITLE
Options of 'summary'

### ISSUE THREAD

**Issue by qiangfu-eu** [nanoporetech/modkit#8]
For following two options of `summray` subcommand, it is unclear that it is use for threshold estimation or for the summary itself. I suggest that if it is for the threshold estimation, better change it accordingly (such as those in `pileup`) to make it clear.

```
-n, --num-reads <NUM_READS>                  Max number of reads to use, especially recommended when using a large BAM without an index. If an indexed BAM is provided, the reads will be sampled evenly
                                               over the length of the aligned reference. If a region is passed with the --region option, they will be sampled over the genomic region [default: 10042]
  
-f, --sampling-frac <SAMPLING_FRAC>          Instead of using a defined number of reads, specify a fraction of reads to sample, for example 0.1 will sample 1/10th of the reads
```

**Comment by ArtRand** [comment]
Hello @qiangfu-eu,

Both of these options will set the number of reads used for estimating the threshold _and_ calculating the summary. By default `modkit summary` samples 10K reads, I made this the default in case users have large BAM files and want an estimate quickly. If you want to run `modkit summary` on all of the reads, set `--sampling-frac 1.0`. If you want to estimate the threshold from a subset of the reads, then use it to summarize _all_ of the reads. I'd recommend using `modkit sample-probs <bam> [--num-reads N | --sampling-frac F]`, to get the threshold _then_ pass that to `modkit summary <bam> --filter-threshold <threshold> --sample-frac 1.0`. Let me know if this isn't clear or if I missed your usecase.

**Comment by qiangfu-eu** [comment]
Thanks that is more clear. It maybe useful to stress the default behavior is to estimate it from a fraction of sampled reads. However, I noticed that sometimes the difference are not that small. See below. Possibly, because the nanopore reads are long, each individual is different ...

```
> cat puc19.summary.1
mod_bases       C
count_reads_C   10042
C_calls_unmodified      97741
C_frac_unmodified       0.3437952866690116
C_filtered_unmodified   17745
C_calls_modified_m      186559
C_frac_modified_m       0.6562047133309884
C_filtered_modified_m   13663
C_total_mod_calls       284300
C_total_filtered_mod_calls      31408
total_reads_used        10042
```

```
> cat puc19.summary
mod_bases       C
count_reads_C   139229
C_calls_unmodified      1114267
C_frac_unmodified       0.39316085211485025
C_filtered_unmodified   172961
C_calls_modified_m      1719858
C_frac_modified_m       0.6068391478851497
C_filtered_modified_m   130193
C_total_mod_calls       2834125
C_total_filtered_mod_calls      303154
total_reads_used        139229
```

**Comment by ArtRand** [comment]
I've added some language in the summary [documentation](https://nanoporetech.github.io/modkit/advanced_usage.html#summary) about how sampling is used to generate the summary. Thanks for the suggestion on that.
