### ISSUE TITLE
Question about afterwork using modkit result & indexing bedMethyl files for igv

### ISSUE THREAD

**Issue by hyunjokoo** [nanoporetech/modkit#84]
Hello,

I have two questions. 

**Question 1.**

I could collect methylation information using `modkit pileup`. 

The result shows all the possible methylation sites, and most of them were not methylated as shown below.

> ptg000001l	86595	86596	h	16	-	86595	86596	255,0,0	16 0.00 0 16 0 0 1 0 0
> ptg000001l	86595	86596	m	16	-	86595	86596	255,0,0	16 0.00 0 16 0 0 1 0 0
> ptg000001l	86596	86597	h	15	+	86596	86597	255,0,0	15 0.00 0 13 2 0 0 0 0
> ptg000001l	86596	86597	m	15	+	86596	86597	255,0,0	15 13.33 2 13 0 0 0 0 0
> ptg000001l	86597	86598	h	16	-	86597	86598	255,0,0	16 0.00 0 16 0 0 0 0 1
> ptg000001l	86597	86598	m	16	-	86597	86598	255,0,0	16 0.00 0 16 0 0 0 0 1

Could you please introduce some tools that can be used to work with this result? For example, collecting highly methylated sites, etc. 
I think I can collect sited with highly methylated sited (e.g. 70%), etc, but I think people already made good tools (kind of standard tools) for the downsteam analysis. It will be much appreciated if you can introduce some good tools. 

(If I have two samples, I could use also `modkit dmr`, but I would like to know the downstream method when I have only one sample.)

**Question 2.**

To view methylated sites in igv. I need index file of bedMethyl files.
If I compress the medMethyl file first, and then index, at least the tabix process works. But I cannot load compressed medMethyl file in igv.
`bgzip modkit_pileup_result.bed` 
`tabix modkit_pileup_result.bed.gz`

However, if I try to make index file from uncompressed bedMethyl file, it does not work. 
`tabix -p bed modkit_pileup_result.bed`

Inside the IGV,  **igvtools** successfulled made index file (the idx file) and I could check methylated site in igv, which means my input bedMethyl file is ok. 

![image](https://github.com/nanoporetech/modkit/assets/68414973/d7b8c59d-3d91-47d8-a0ec-19dd8a6c845f)

I also tried gatk for indexing the bedMethyl file, but it did not work.
`gatk IndexFeatureFile --input modkit_pileup_result.bed`

Could you please tell me the best method to make the index of uncompressed bedMethyl file for igv?

Thank you.
HJK

**Comment by ArtRand** [comment]
@hyunjokoo let me know if you have any additional questions.
