### ISSUE TITLE
killed while using --bedgraph

### ISSUE THREAD

**Issue by JoukjeKloosterman** [nanoporetech/modkit#86]
Hello all,

The following command to get a bedgraph gets killed:

`"${WORK}/dist/modkit" pileup "${OUTPUT}/${RUN}_sorted.bam" "${OUTPUT}/bedgraph/" --cpg --ref "${ONT_DATA}/human_g1k_v37.fasta" --log-filepath "${OUTPUT}/modkit-pileup-${RUN}-cpg-1.log" --bedgraph`

Any idea what i am doing wrong?

**Comment by ArtRand** [comment]
Hello @JoukjeKloosterman, 

That command looks fine to me. Could you post the log file so I could take a look? Do you know that it's being killed from running out of memory or something else?

**Comment by JoukjeKloosterman** [comment]
Hello @ArtRand 

It appeared to be an out-of-memory issue, thank you for your comment.
