### ISSUE TITLE
dmr multi - error: 2 values required for '--sample <SAMPLES> <SAMPLES>' but 1 was provided

### ISSUE THREAD

**Issue by flokraft85** [nanoporetech/modkit#89]
Hi modkit team,
I have some issue running the dmr multi command. I try to adopt the command from the example in the documentation (https://nanoporetech.github.io/modkit/intro_dmr.html), however it did not work.
I used the following command:
modkit dmr multi  -s ./barcode08_methyl.bed.gz -s ./barcode09_methyl.bed.gz -s ./barcode10_methyl.bed.gz -o ./ -r ./genes.bed --ref /GRCh38_no_alt_analysis_set.fa --base C -t 20 -f --log_filepath ./dmr.log
and got this error:
error: 2 values required for '--sample <SAMPLES> <SAMPLES>' but 1 was provided
Usage: modkit dmr multi [OPTIONS] --regions-bed <REGIONS_BED> --out-dir <OUT_DIR> --ref <REFERENCE_FASTA>
For more information, try '--help'.

I used 3 samples in this command, so I did not understand why modkit complains, that there is only one sample.
Thanks in advance for your help!
Florian

**Comment by flokraft85** [comment]
Hi @ArtRand ,
thanks for the immediate help. So it was my fault. Adding the samples name helped and it now runs!
Thanks again!

**Comment by ArtRand** [comment]
@flokraft85 no problem, the documentation should have a better example.

**Comment by ArtRand** [comment]
Hello @flokraft85 

I've added more [language](https://nanoporetech.github.io/modkit/intro_dmr.html#running-multiple-samples) around how to use sample names for `modkit dmr multi` let me know if it is still unclear.

**Comment by flokraft85** [comment]
Hi @ArtRand,
thanks you very much! I think this is now much more clear in the documentation!

Best,
FLorian
