### ISSUE TITLE
Does the threshold estimation take into account edge-filter?

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/modkit#94]
Basically the title of the post -- does threshold estimation respect the edge-filter settings? This would normally not be that significant if the size to exclude is small, but I am guessing that it would be problematic if the edge-filter is comparable to the size of the read (eg. for cfDNA purposes as referenced in #87 and #88)

**Comment by ArtRand** [comment]
Hello @billytcl,

Yes when you use the `--edge-filter` it globally ignores base modification calls as you specify in the command. The behavior is described in [online documentation](https://nanoporetech.github.io/modkit/intro_edge_filter.html) but I will add it to the command help in the next release.
