### ISSUE TITLE
modkit extract "--include-bed" Error: improperly formatted BED line

### ISSUE THREAD

**Issue by pkerbs** [nanoporetech/modkit#97]
Hello,
I am trying to extract methylation information using `modkit extract` with the `--include-bed` option.
Here is an excerpt from my BED file (tab-separated, LF newlines):
```
chr11	2044	2045	cg14817997	1
chr11	2361	2362	cg26928153	1
chr11	2363	2364	cg16269199	1
chr11	7431	7432	cg13869341	1
```

An excerpt from the error message:
```
[src/position_filter.rs::71][2023-12-11 14:34:08][INFO] improperly formatted BED line chr11     2044    2045    cg14817997      1
[src/position_filter.rs::71][2023-12-11 14:34:08][INFO] improperly formatted BED line chr11     2361    2362    cg26928153      1
[src/position_filter.rs::71][2023-12-11 14:34:08][INFO] improperly formatted BED line chr11     2363    2364    cg16269199      1
[src/position_filter.rs::71][2023-12-11 14:34:08][INFO] improperly formatted BED line chr11     7431    7432    cg13869341      1
```

What am I doing wrong, why is modkit not accepting my BED file?
Thanks in advance.

Best,
Paul

**Comment by ArtRand** [comment]
Hello @pkerbs, 

The `--include-bed` needs to have strand information, so you need one more column with `+` if the modified base is on the top strand and `-` if the base is on the bottom strand. You can find an example if the [tests directory](https://github.com/nanoporetech/modkit/blob/master/tests/resources/CGI_ladder_3.6kb_ref_CG.bed). One note that `.` can be used to indicate both strands, (or as a work-around if you don't have a way to get the strand information). Hope this helps.

**Comment by pkerbs** [comment]
Thank you that helped, it runs now.

Maybe it would be good to have this mentioned in the docs/manual, because strand info is not a required field in BED format.
Apart from that, I think `modkit extract` should just use both strands by default and if a strand column is given in the BED, it should use the info given in the BED. What do you think?


Best,
Paul

**Comment by ArtRand** [comment]
Hello @pkerbs,

Yes, this is on the feature list for 0.2.4. Glad it's working for you now.
