### ISSUE TITLE
version reporting

### ISSUE THREAD

**Issue by mattloose** [nanoporetech/modkit#98]
Minor issue but running:

modkit -V

returns:

mod_kit 0.2.3

should it not return:

modkit 0.2.3?

**Comment by ArtRand** [comment]
Hello @mattloose, 

The name reported here is sourced from the [Cargo.toml](https://github.com/nanoporetech/modkit/blob/83c87689d3f39de8176fe4f511295ed70db3c800/Cargo.toml#L2). It's not an API change, I can look into changing it, we're looking into publishing the library to crates.io, after which changing the name will become more involved. So as always, naming things is hard - but thanks for noticing the inconsistency.
