### ISSUE TITLE
Performance on large bam files

### ISSUE THREAD

**Issue by mattloose** [nanoporetech/modkit#99]
When running modkit extract across human scale bam files the process hangs for a significant period of time at the end of each chromosome. Run time for modkit extract can end up taking hours even when running on multiple threads.

Any suggestions how performance can be improved?

**Comment by mattloose** [comment]
exact command being run is:

modkit extract --ignore h -t 96 32Gbhuman.bam 32Gbhumanbam.extract 

The machine it's being run on has 1Tb of RAM, 128 cores and a lot of SSD.

**Comment by ArtRand** [comment]
Hello @mattloose ,

Since you're able to see that the program hangs at the ends of chromosomes, I'm assuming you're using an indexed modBAM (correct?). Is the problem mitigatged when you use `--ignore-index`? This flag will force `modkit` to us a linear scan over the modBAM. 

You're on 0.2.3 right?

**Comment by mattloose** [comment]
Yep - running on 0.2.3

You are correct we are using an indexed bam file. 

I will see if the overall run time is faster using --ignore-index when this run has finised.... (it has been running since I opened this issue).

We were using the indexed bam as by eye it is sigificantly faster than not using an index over one chromosome - I hadn't spotted the big hang at the end of each chromosome until today when I was trying to solve why our pipeline is taking so long to finish!

**Comment by mattloose** [comment]
OK - so around 4 hours on 96 cores when using the bam...

**Comment by ArtRand** [comment]
During the hang, do you see

```
> 80042295 rows written
```

ticking up or is it just idle? Is there any evidence of something happening on `top`? What are the rough characteristics of your modBAM? I'm trying to reproduce with your command on a 214G modBAM and I'm not seeing the slowdown between chroms.

**Comment by mattloose** [comment]
Thanks - let me just idiot check myself...

modkit in this env is reporting 0.2.2

Would that be sufficient to explain the problem?

**Comment by mattloose** [comment]
I'm sorry - it looks like my fault! 

When I run correctly with 0.2.3 it is fast....

It's very fast.

**Comment by ArtRand** [comment]
Modkit version 0.2.2 had a significant performance regression (as you discovered). Starting with v0.2.3-rc1 it should be a lot faster (as you also happily discovered). Glad it's working now.

**Comment by ArtRand** [comment]
As an aside, the files that `modkit extract` generates will be quite large. I'm looking into alternative output formats. You could pipe through `bgzip` or something like that, but I could also output parquet or feather.. what do you think?

**Comment by mattloose** [comment]
Yeah - confirmed that this was me not updating when I thought I had updated.....

We do compress it - but you are correct - the file ends up slightly larger than the starting bam file. I'd actually like to remove the step entirely in this particular pipeline and I'm workign on that at the moment.

**Comment by ArtRand** [comment]
@mattloose, 

You may be interested in the `--read-calls` [option](https://nanoporetech.github.io/modkit/intro_extract.html#tabulating-base-modification-calls-for-each-read-position) in 0.2.3, it will produce the base modification _call_ at each position in the read the same way that `pileup` would.

**Comment by mattloose** [comment]
Ah - I will take a look!
Thanks!
